<?php // Set page title.
$this->headTitle($this->translate('Playbills') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Themenportal Theaterzettel im FID Darstellende Kunst</h2>
<!-- &filter[]=~format%3A"Theaterzettel" -->
<div class="flexing">
<div class="card item">
  <p>Der Fachinformationsdienst Darstellende Kunst stellt Ihnen eine Auswahl an Informationsquellen zur Gattung Theaterzettel zur Verfügung.
  Aktuell können Sie in den folgenden Datenbeständen recherchieren:
  <ul>
    <li>Theater und Musik in Weimar 1751-1990</li>
    <li><a href="<?=$this->url('search-results')?>?filter[]=~format%3A%22Theaterzettel%22&filter[]=~institution_facet%3A%220%2FUniversitäts-+und+Landesbibliothek+Düsseldorf%2F%22&type=AllFields">Digitalisierungsprojekt Düsseldorfer Theaterzettel der Universitäts- und Landesbibliothek Düsseldorf</a></li>
    <li>Theaterzettel-Sammlung der Lippischen Landesbibliothek</li>
  </ul>
  Darüber hinaus haben wir Ihnen eine Auswahl an Fachliteratur sowie weiterführende Links zu Projekten und Digitalen Sammlungen von Theaterzetteln im deutschsprachigen Raum zusammengestellt.</p>
  <p>Sie haben Ergänzungen zur Auswahl oder benötigen Hilfe bei Ihrer Recherche? Wenden Sie sich an <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>.</p>
</div>
<?php foreach ($this->results->getRecommendations('side') as $current):?>
  <?=$this->recommend($current);?>
<?php endforeach;?>
</div>
<div class="card">
  <h3>Theaterzettel</h3>
  <p><a target="_blank" href="https://de.wikipedia.org/wiki/Theaterzettel">Theaterzettel</a> sind Plakate bzw. Zettel, die ein theatrales Ereignis ankündigen. Zumeist sehr kurzfristig produziert wird der Theaterzettel
    am Tag der Aufführung (oder am Tag zuvor) im Theater und über die Stadt verteilt aufgehängt, sowie durch Zettelträger in einzelne Haushalte
    (z.B. <a target="_blank" href="https://de.wikipedia.org/wiki/Theaterabonnement">Abonnenten</a>) gebracht. Folgende Informationen kündigt der
    Theaterzettel an: der Name des Theaters bzw. Aufführungsort, das Datum der Aufführung, oft auch Beginn und Ende der Aufführung, der oder
    die Titel der Stück(e) sowie die Namen der Darsteller*innen und der Urheber eines Theaterabends. Hinzu können auch die Eintrittspreise
    und weitere Information, ob es sich beispielsweise um eine Vorstellung für Abonnenten handelt, vermerkt werden.</p>
  <p>Den Höhepunkt seiner Verbreitung hatte das Medium Theaterzettel im 18. und 19. Jahrhundert. Mit Beginn des 20. Jahrhunderts übernahm das
    Programmheft die Funktion des Theaterzettels. Die öffentlich ausgehängten Zettel wurden sukzessive durch großformatige Plakate ersetzt,
    und auch die Verteilung der Theaterzettel an einzelne Haushalte wurde eingestellt.</p>
    <br/>
  <h3>Forschung und Archivierung</h3>
  <p>Das Medium Theaterzettel ist eine zentrale Quelle für die Repertoireforschung. Sie geben Auskunft über den täglichen Theater- bzw.
    Spielbetrieb und vermitteln ein Bild der Aufführungspraxis. Neben der Theaterwissenschaft und -historiographie ist es vor allem die
    kulturhistorische Forschung, die das Medium Theaterzettel untersuchen.</p>
  <p>Auch wenn einzelne Theaterzettel für die Forschung von Relevanz sein können, so ist es doch vor allem die (lückenlose) Sammlung von
    Theaterzetteln einer oder mehrerer Spielstätten, die als Forschungsgegenstand genutzt wird.</p>
  <p>In den Gedächtnisinstitutionen – Archive, Bibliotheken und Museen – findet man  Theaterzettelsammlungen zumeist mit einem regionalen
    und/oder thematischen Schwerpunkt. Aufgrund der schieren Menge werden Theaterzettelsammlungen zumeist als Konvolute, nach Spielzeit
    und nicht einzelnen, erfasst. In einzelnen Digitalisierungsprojekten der letzten Jahrzehnte wurden Theaterzettelsammlungen systematisch
    erschlossen und teilweise mit weiterführenden Informationen angereichert. Einen Überblick – eine Art Topographie – über die
    Sammlungsbestände im deutschsprachigen Raum ist ein wünschenswertes Desiderat.</p>
  <p><a target="_blank" href="http://d-nb.info/gnd/4185060-9">GND-Eintrag Theaterzettel > http://d-nb.info/gnd/4185060-9</a></p>
</div>
<div class="card">
  <h3>Literaturhinweise</h3>
  <ul>
    <li>Cepl-Kaufmann, Gertrude: „Zum kulturellen Stellenwert von Theaterzetteln“, in: Flugblätter von der frühen Neuzeit bis zur Gegenwart als kulturhistorische
      Quellen und bibliothekarische Sondermaterialien, hg. von Christiane Caemmerer, Jörg Jungmayr und Eef Overgaauw. Frankfurt a. M. u. a.: Peter Lang 2010, S. 127–157.</a></li>
    <li><a href="<?=$this->url('search-results')?>?lookfor=Eder%2C+Ruth&type=AllFields">Eder, Ruth (Hg.): Theaterzettel. Dortmund: Harenberg 1980.</a></li>
    <li><a href="<?=$this->url('search-results')?>?join=AND&lookfor0%5B%5D=Die+Geschichte+des+Theaterzettels+&type0%5B%5D=AllFields&lookfor0%5B%5D=H%C3%A4nsel%2C+Johann-Richard&type0%5B%5D=Author">Hänsel, Johann-Richard: Die Geschichte des Theaterzettels und seine Wirkung in der Öffent-lichkeit. Berlin, Freie Universität, Hochschulschrift 1959.</a></li>
    <li><a href="<?=$this->url('search-results')?>?join=AND&lookfor0%5B%5D=Medien+der+Theatergeschichte+des+18.+und+19.+Jahrhunderts&type0%5B%5D=AllFields&lookfor0%5B%5D=Korte%2C+Hermann&type0%5B%5D=Author">Korte, Hermann, Hans-Joachim Jakob und Bastian Dewenter (Hgg.): Medien der Theatergeschichte des 18. und 19. Jahrhunderts. Heidelberg: Universitätsverlag
      Winter 2015 (= Proszenium. Beiträge zur historischen Theaterpublikumsforschung 3).</li>
    <li><a href="<?=$this->url('search-results')?>?join=AND&lookfor0%5B%5D=Theater+-+Zettel+-+Sammlungen+&type0%5B%5D=AllFields&lookfor0%5B%5D=Pernerstorfer%2C+Matthias+Johannes+&type0%5B%5D=Author">Pernerstorfer, Matthias J. (Hg.): Theater – Zettel – Sammlungen. Erschließung, Digitalisierung, Forschung. Wien: Hollitzer Verlag 2012 (= Bibliographica 1).</a></li>
    <li>Pernerstorfer, Matthias J. (Hg.): Theater – Zettel – Sammlungen 2. Bestände, Erschließung, Forschung. Vienna: Hollitzer 2015 (= Bibliographica 2).</li>
    <li>Pernerstorfer, Matthias: „Mit gnädigster Bewilligung wird heute…“ Aktuelle Entwicklungen in der Erschließung und Digitalisierung von Theaterzetteln. Erschienen in: Neuböck, Gregor (Hg.): Digitalisierung in Bibliotheken : viel mehr als nur Bücher scannen. Berlin; Boston : De Gruyter Saur 2018, S. 173-204.</li>
    <li><a href="<?=$this->url('search-results')?>?lookfor0%5B%5D=Einem+hocherfreuten+Publikum+wird+heute+pr%C3%A4sentiret+eine+kleine+Chronik+des+Theaterzettels&type0%5B%5D=Title">Pies, Eike: Einem hocherfreuten Publikum wird heute präsentiret eine kleine Chronik des Theaterzettels. Mit 29 Beispielen versetzt und vorgestellt von Eike Pies.
      Solingen: E.&U. Brockhaus 2000.</a></li>
  </ul>
  <br/>
  <h3>Digitale Sammlungen von Theaterzetteln (deutschsprachiger Raum)</h3>
    <ul>
      <li><a target="_blank" href="http://anno.onb.ac.at/">ANNO - AustriaN Newspapers Online</a>. Erläuterung: Umfangreiche digitale Sammlung von Theaterzetteln vom Wiener Burgtheater (zw. 1800-1949).</li>
      <ul>
        <li><a target="_blank" href="http://anno.onb.ac.at/cgi-content/anno?apm=0&aid=wtz">Wiener Theaterzettel der Oper und des Burgtheaters</a></li>
        <li><a target="_blank" href="http://anno.onb.ac.at/cgi-content/anno?apm=0&aid=taw">Theaterzettel vom Theater an der Wien</a></li>
      </ul>
      <li><a target="_blank" href="http://berlinerklassik.bbaw.de/BK/theater/Suche.html">Berliner Theaterzettel</a> via <a target="_blank" href="http://berlinerklassik.bbaw.de/BK/">Datenbanken Berliner Klassik</a></li>
      <li><a target="_blank" href="http://brema.suub.uni-bremen.de/suubtheater">Bremer Theaterzettel</a></li>
      <li><a target="_blank" href="http://www.llb-detmold.de/sammlungen/musiksammlung/theatersammlung.html">Detmolder Theaterzettel</a> Digitalisate auffindbar in der <a target="_blank" href="http://www.llb-detmold.de/literatursuche/regionaldok-lippe.html">Lippische Bibliographie</a></li>
      <li><a target="_blank" href="http://digital.ub.uni-duesseldorf.de/theaterzettel">Düsseldorfer Theaterzettel</a></li>
      <li><a target="_blank" href="https://digital.blb-karlsruhe.de/2949538">Karlsruher Theaterzettel</a></li>
      <li><a target="_blank" href="http://digital.lb-oldenburg.de/zs/nav/classification/365898">Oldenburger Theaterzettel</a></li>
      <li><a target="_blank" href="http://www.landesarchiv-bw.de/plink/?f=2-362879">Stuttgarter Theaterzettel</a></li>
      <li><a target="_blank" href="http://www.theaterzettel-weimar.de/home.html">Theater und Musik in Weimar 1754-1990</a></li>
      <li><a target="_blank" href="https://www.theatermuseum.at/onlinesammlung/">Theatermuseum Wien</a></li>
      <li><a target="_blank" href="http://www.archivinformationssystem.at/detail.aspx?ID=1451">Theaterzettelsammlung Emmerich Wagner</a></li>
      <li><a target="_blank" href="http://theaterzettel.franconica.uni-wuerzburg.de/">Würzburger Theaterzettel</a></li>
    </ul>
    <br/>
  <h3>Weiterführende Links</h3>
    <ul>
      <li><a target="_blank" href="https://www.theaterzettel.at/">THEO Theaterzettel Online. Ein Digitalisierungskonzept am Beispiel von Wiener Theaterzetteln des 19. Jahrhunderts</a></li>
      <li><a target="_blank" href="https://archiv.adk.de/bigobjekt/17289">Theaterzettel-Sammlung (gebunden)</a> im Archiv der <a target="_blank" href="https://de.wikipedia.org/wiki/Akademie_der_K%C3%BCnste_(Berlin)">Akademie der Künste, Berlin</a></li>
      <li><a target="_blank" href="http://staatsbibliothek-berlin.de/de/die-staatsbibliothek/abteilungen/historische-drucke/sammlungen/bestaende/theaterzettel/">Sammlung der Theaterzettel der Staatsbibliothek Berlin</a></li>
      <li><a target="_blank" href="https://www.libcrowds.com/collection/playbills">Theaterzettel der British Library</a></li>
      <li><a target="_blank" href="http://www.ulm.de/sixcms/media.php/29/G3_1670-1899.pdf">Findbuch zu Theaterzetteln des Stadtarchivs Ulm</a></li>
    </ul>
</div>
