<?php $this->info = $this->recommend->getAuthInfo($this->driver);
      $type = $this->driver->getAuthType();
if (!empty($this->info) || isset($driver)):
    $types = $this->info['type'];
    if (!empty($this->info['gndIdentifier'])):
      $dprov = '';
    else:
      $dprov = $this->driver->getInstitutionLinked();
    endif;
    if (in_array("ConferenceOrEvent",$types)):
      $moreInfo = isset($this->info['biographicalOrHistoricalInformation'])
           || isset($this->info['dateOfConferenceOrEvent'])
           || isset($this->info['placeOfConferenceOrEvent'])
           || isset($this->info['homepage'])
           || isset($this->info['spatialAreaOfActivity']);
    else:
      $moreInfo = isset($this->info['professionOrOccupation'])
           || isset($this->info['placeOfBusiness'])
           || isset($this->info['biographicalOrHistoricalInformation'])
           || isset($this->info['dateOfBirth'])
           || isset($this->info['dateOfDeath'])
           || isset($this->info['placeOfBirth'])
           || isset($this->info['placeOfDeath'])
           || isset($this->info['publication'])
           || isset($this->info['precedingCorporateBody'])
           || isset($this->info['dateOfEstablishment'])
           || isset($this->info['homepage'])
           || isset($this->info['spatialAreaOfActivity'])
           || isset($this->info['geographicAreaCode'])
           || isset($this->info['sameAs']);
    endif;
    $title = $this->info['preferredName'];
    $variant = isset($this->info['variantName']) ? $this->info['variantName'] : '';
    $id = $this->driver->getUniqueId();
    $this->agents = $this->driver->getDeduplicatedAuthors();
    //TODO: There can be more than one thumbnail??
    $thumbnail = isset($this->info['depiction'][0]['thumbnail']) ? $this->info['depiction'][0]['thumbnail'] : '';
      //$sameAs = $this->driver->getSameAs();
?>
<div class="card clearfix">
  <div class="flex-content flex-start">
  <?php if (!empty($thumbnail)):
    $picSource = $this->recommend->getPicSource($thumbnail);?>
    <div class="authority-meta thumb">
      <figure>
          <img class="pull-left flip" src="<?=$thumbnail?>" alt="<?=$title?>"/>
        <?php if (!empty($picSource)): ?>
          <figcaption><?=$this->transEsc("PicSource") . ": " . $picSource[0] . " | "?>
          <a href="<?=$picSource[1]?>">Wikimedia Commons</a>
          <?=" | "?><a href="<?=$picSource[1] . '#Licensing'?>"><?=$picSource[2]?></a></figcaption>
        <?php endif; ?>
      </figure>
    </div>
  <?php endif; ?>
    <div class="authority-meta">
      <h2><?=$title?></h2>
      <?php if ($type == "Personal Name" || $type == "Corporate Name"): ?>
        <?php if ($type == "Personal Name"): ?>
          <?=$this->render('Recommend/data-firstFacts.phtml');?><br/>
          <?=$this->render('Recommend/data-moreFacts.phtml');?><br/>
        <?php elseif ($type == "Corporate Name"): ?>
          <?=$this->render('Recommend/data-corporateFacts.phtml');?>
        <?php endif; ?>
        <?=$this->render('Recommend/data-relatedWorks.phtml',['type' => $type, 'count' => $this->driver->getWorkCount(),'id' => $id]);?>
        <?=$this->render('Recommend/data-relatedEvents.phtml',['type' => $type,'count' => $this->driver->getEventCount(),'id' => $id]);?>
      <?php elseif ($type == "event_gnd"): ?>
        <?=$this->render('Recommend/data-eventFields_gnd.phtml');?>
      <?php elseif ($type == "Event"): ?>
        <?=$this->render('Recommend/data-eventFields.phtml');?>
      <?php elseif ($type == "Work"): ?>
      <?=$this->render('Recommend/data-workFields.phtml');?>
    <?php endif; ?>
    <?php if (!empty($variant)) : ?>
       <br/><b><?=$this->transEsc('edm::skos:altLabel')?></b><br/>
        <?php $this->data = $variant; ?>
        <?=$this->render('RecordDriver/SolrEdm/data-collapsible_str.phtml');?>
    <?php endif; ?><br/>
    </div>
    <div class="authority-meta">
      <?php if ($type == 'Event'):
        if (!empty($this->info['description'])) : ?>
            <span property="description">
              <?php foreach($this->info['description'] as $descr): ?>
                  <?=$descr?><br />
              <?php endforeach; ?>
            </span><br/>
        <?php endif;
        $works = $this->driver->getWorks();
        if (!empty($works)) : ?>
          <b><?=$this->transEsc('RelatedWorksEve') . ':'?></b><br/>
          <?php foreach($works as $work_id => $work): ?>
            <span property="edm:isRelatedTo">
              <a href="<?=$this->url('workrecord') . urlencode($work_id);?>"><?=$work?></a>
            </span><br />
          <?php endforeach; ?>
          <br />
        <?php endif; ?>
      <?php endif; ?>
      <?php if (!empty($this->info['sameAs'])): ?>
        <?=$this->render('Recommend/data-sameAs.phtml');?>
      <?php endif; ?>
      <?php if ($type == "Work"): ?>
        <?=$this->render('Recommend/data-relatedEvents.phtml',['type' => $type,'count' => $this->driver->getEventCount(),'id' => $id]);?>
        <br />
      <?php endif; ?>
      <?php if (!empty($this->info['describedBy']) || isset($dprov)): ?>
        <?=$this->render('Recommend/data-source.phtml',['dprov' => $dprov, 'describedBy' => $this->info['describedBy']]);?>
      <?php endif; ?>
   </div>
 </div>
</div>
<?php endif;?>
