<?php $eventType = $this->driver->getEventType();
      $eventDates = $this->driver->getEventDate();
      $eventPlaces = $this->driver->getEventPlace();
      $lang = $this->plugin('translate')->getTranslator()->getLocale();?>
<?php if (!empty($eventType)) : ?>
  <b><?=$this->transEsc('Type of Event') . ':'?></b>
  <span property="performingArtsType">
    <?=implode($eventType,', ')?>
  </span><br />
<?php endif; ?>
<?php if (isset($this->info["genre"])) : ?>
  <b><?=$this->transEsc('Genre') . ':'?></b>
  <span property="genre">
    <?=implode($this->info["genre"],', ')?>
  </span><br />
<?php endif; ?>
<?php if (!empty($eventDates)) : ?>
  <b><?=$this->transEsc('DateOfEvent') . ':'?></b>
  <?php $normDates = [];?>
  <?php foreach ($eventDates as $eventDate): ?>
    <?php $normDates[] = $this->driver->translateDate($eventDate,$lang)?>
  <?php endforeach; ?>
  <span property="edm:occuredAt">
    <?=$this->escapeHtml(implode($normDates,', '))?>
  </span><br/>
<?php endif; ?>
<?php if (!empty($eventPlaces)) : ?>
  <b><?=$this->transEsc('PlaceOfEvent') . ':'?></b>
  <?php foreach($eventPlaces as $eventPlace): ?>
    <span property="edm:happenedAt">
      <?=$eventPlace?>
    </span><br />
  <?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($agents["primary"])):?>
  <br/>
  <b><?=$this->transEsc('Contributors')?></b><br/>
  <?php $formattedAuthors = [];
      foreach ($agents["primary"] as $author => $dataFields):
        if (!empty($author)):
          ob_start();
          // an authority link exists and that document exists in SolrAuthor
          if (isset($dataFields['id'][0])) : //&& $this->driver->checkExistence($dataFields['id'][0],"SolrAuth")) :
            $authorityLookfor = $this->url('agentrecord') . urlencode($dataFields['id'][0]);
          else :
            $authorityLookfor = $this->record($this->driver)->getLink('name', $author);
          endif; ?>
      <span class="author-data" property="<?=$this->escapeHtml($dataFields['role'][0])?>">
        <a href="<?=$authorityLookfor?>">
          <?=$this->escapeHtml($author)?>
        </a>
        <?='(' . implode(', ', array_map(function($role) {return $this->transEsc('edm::' . $role);},array_unique($dataFields['role']))) . ')'?>
      </span>
      <?php
        // Strip whitespace before close tags to avoid spaces in front of commas:
        $formattedAuthors[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
        ob_end_clean();
       endif;
     endforeach;?>
  <?=implode(', ', $formattedAuthors)?><br/>
<?php endif; ?>
