<?php $eventType = $this->driver->getEventType();
      $eventDates = $this->driver->getEventDate();
      $eventPlaces = $this->driver->getEventPlace();
      $lang = $this->plugin('translate')->getTranslator()->getLocale();?>
<?php if (!empty($eventType)) : ?>
  <b><?=$this->transEsc('Type of Event') . ':'?></b>
  <span property="performingArtsType">
    <?=implode($eventType,', ')?>
  </span><br />
<?php endif; ?>
<?php if (!empty($eventDates)) : ?>
  <b><?=$this->transEsc('DateOfEvent') . ':'?></b>
  <?php $normDates = [];?>
  <?php foreach ($eventDates as $eventDate): ?>
    <?php $normDates[] = $this->driver->translateDate($eventDate,$lang)?>
  <?php endforeach; ?>
  <span property="edm:occuredAt">
    <?=$this->escapeHtml(implode($normDates,', '))?>
  </span><br />
<?php endif; ?>
<?php if (!empty($eventPlaces)) : ?>
  <b><?=$this->transEsc('PlaceOfEvent') . ':'?></b>
  <?php foreach($eventPlaces as $eventPlace): ?>
    <span property="edm:happenedAt">
      <?=$eventPlace?>
    </span><br />
  <?php endforeach; ?>
<?php endif; ?>
