<?php if (isset($this->info['professionOrOccupation']) || isset($this->info['dateOfBirth'])
  || isset($this->info['dateOfDeath']) || isset($this->info['placeOfBirth'])
  || isset($this->info['placeOfDeath'])): ?>
    <?=$this->render('Recommend/data-firstFacts.phtml');?><br/>
  <?php endif; ?>
  <?php if (isset($this->info['biographicalOrHistoricalInformation'])
    || isset($this->info['publication']) || isset($this->info['placeOfActivity'])
    || isset($this->info['affiliation']) || isset($this->info['familialRelationship'])) : ?>
    <?=$this->render('Recommend/data-moreFacts.phtml');?><br/>
  <?php endif; ?>
  <?php if (isset($this->info['placeOfBusiness']) || isset($this->info['dateOfEstablishment'])
  || isset($this->info['homepage']) || isset($this->info['precedingCorporateBody'])
  || isset($this->info['broaderTermInstantial']) || isset($this->info['geographicAreaCode'])
  || isset($this->info['spatialAreaOfActivity'])) : ?>
    <?=$this->render('Recommend/data-corporateFacts.phtml');?><br/>
  <?php endif; ?>
