<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<?php if (isset($this->info['professionOrOccupation'])) : ?>
  <span property="professionOrOccupation">
    <?php if($this->info['gndIdentifier'] == "1043940596"):?>
    <?='Autor, Dramatiker, Schauspieler, Regisseur, Drehbuchautor'?>
    <?php else: ?>
    <?=implode(', ',array_column($this->info['professionOrOccupation'],'label'))?>
  <?php endif; ?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['dateOfBirth']) || isset($this->info['placeOfBirth'])) : ?>
  <?=$this->transEsc('born')?>
  <?php if (isset($this->info['dateOfBirth'])) : ?>
    <span property="birthDate">
      <?=implode('/',array_map(function($item) use($lang) {
          return $this->recommend->formatDisplayDate($item, $lang); },$this->info['dateOfBirth']))?>
    </span>
  <?php endif; ?>
  <?php if (isset($this->info['placeOfBirth'])) : ?>
    <?=$this->transEsc('in')?>
    <span property="birthPlace">
      <?=implode('/',array_column($this->info['placeOfBirth'],'label'))?>
    </span>
  <?php endif; ?>
  <br/>
  <?php if (!(isset($this->info['dateOfDeath']) || isset($this->info['placeOfDeath']))) : ?>
    <br/>
  <?php endif; ?>
<?php endif; ?>
<?php if (isset($this->info['dateOfDeath']) || isset($this->info['placeOfDeath'])) : ?>
  <?=$this->transEsc('died')?>
  <?php if (isset($this->info['dateOfDeath'])) : ?>
    <span property="deathDate">
      <?=implode('/',array_map(function($item) use($lang) {
          return $this->recommend->formatDisplayDate($item, $lang); },$this->info['dateOfDeath']))?>
    </span>
  <?php endif; ?>
  <?php if (isset($this->info['placeOfDeath'])) : ?>
    <?=$this->transEsc('in')?>
    <span property="deathPlace">
      <?=implode('/',array_column($this->info['placeOfDeath'],'label'))?>
    </span>
  <?php endif; ?>
  <br/><br/>
<?php endif; ?>
<?php if (isset($this->info['biographicalOrHistoricalInformation'])) : ?>
  <b><?=$this->transEsc('BiographicalDetails')?></b>
  <br/><span property="biographicalInformation">
    <?=implode('; ',$this->info['biographicalOrHistoricalInformation'])?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['description'])) : ?>
<?php foreach($this->info['description'] as $descr): ?>
    <?=$descr?><br/><br/>
<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->info['gender'])) : ?>
  <b><?=$this->transEsc('Gender') . ': '?></b>
  <span property="gender">
    <?=implode('/',array_column($this->info['gender'],'label'))?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['playedInstrument'])) : ?>
  <b><?=$this->transEsc('Instrument') . ': '?></b>
  <span property="playedInstrument">
    <?=implode('; ',array_column($this->info['playedInstrument'],'label'))?>
  </span><br />
<?php endif; ?>
<?php if (isset($this->info['affiliation'])) : ?>
  <b><?=$this->transEsc('Affiliation') . ': '?></b>
  <span property="affiliation">
    <?=implode('/',array_column($this->info['affiliation'],'label'))?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['placeOfActivity'])) : ?>
  <b><?=$this->transEsc('placeOfActivity') . ': '?></b>
  <span property="placeOfActivity">
    <?=implode('/',array_column($this->info['placeOfActivity'],'label'))?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['geographicAreaCode'])) : ?>
  <b><?=$this->transEsc('GeographicAreaCode') . ': '?></b>
  <span property="geographicAreaCode">
    <?=implode('; ',array_column($this->info['geographicAreaCode'],'label'))?>
  </span><br />
<?php endif; ?>
<?php if (isset($this->info['gndSubjectCategory'])) : ?>
  <b><?=$this->transEsc('gndSubjectCategory') . ': '?></b>
  <span property="Category">
    <?=implode(', ',array_column($this->info['gndSubjectCategory'],'label'))?>
  </span><br/>
<?php endif; ?>
<?php if (isset($this->info['publication'])) : ?>
  <b><?=$this->transEsc('Publications') . ':'?></b><br />
  <div class="publications">
    <?=implode(' | ',$this->info['publication'])?>
  </div>
<?php endif; ?>
<?php if (isset($this->info['familialRelationship'])) : ?>
<br/><b><?=$this->transEsc('Familial Relationship')?></b><br />
  <span property="familialRelationship">
    <?=implode('; ',array_column($this->info['familialRelationship'],'label'))?>
  </span>
<?php endif; ?>
<?php if (isset($this->info['professionalRelationship'])) : ?>
 <br/><b><?=$this->transEsc('Professional Relationship')?></b><br />
  <span property="professionalRelationship">
    <?=implode('; ',array_column($this->info['professionalRelationship'],'label'))?>
  </span>
<?php endif; ?>
