<div class="authority-meta">
  <h4><?=$this->transEsc('More Links')?></h4>
  <?php foreach ($this->info['sameAs'] as $k => $current):
      if (isset($current['id']) && isset($current['collection'])) :
        $abbr = isset($current['collection']['abbr']) ? $current['collection']['abbr'] : '';
        $name = isset($current['collection']['name']) ? $current['collection']['name'] : '';
        $icon = isset($current['collection']['icon']) ? $current['collection']['icon'] : '';
        ?>
      <a href="<?=$current['id']?>" target="_blank">
        <i class="external-icon"><img src="<?=$icon?>" alt="<?=$abbr?>"></i>
        <?=$name?>
      </a><br />
      <? if(array_key_exists($k+1,$this->info['sameAs'])):?>
         <hr/>
      <? endif;?>
    <?php endif; ?>
  <?php endforeach; ?><br />
  <?=$this->render('Recommend/data-source.phtml');?>
</div>
