<?php $description = $this->driver->getSummary();
      //$genre = $this->driver->getGenre(); bf:genreForm
      $lang = $this->plugin('translate')->getTranslator()->getLocale();
      //$edm = $this->driver->getXML('edm');?>
      <?//=\VuFind\XSLT\Processor::process('record-edm.xsl', $edm);?>
<?php if (!empty($description)) : ?>
  <br/><span property="description">
    <?=implode('; ',$description)?>
  </span><br/>
  <?php endif; ?>
<?php if (!empty($this->agents)) : ?>
  <br/>
  <b><?=$this->transEsc('Contributors')?></b><br/>
  <?php $formattedAuthors = [];
    if (!empty($this->agents["primary"])):
      foreach ($this->agents["primary"] as $author => $dataFields):
        if (!empty($author)):
          ob_start();
          // an authority link exists and that document exists in SolrAuthor
          if (isset($dataFields['id'][0])) : //&& $this->driver->checkExistence($dataFields['id'][0],"SolrAuth")) :
            $authorityLookfor = $this->url('agentrecord') . urlencode($dataFields['id'][0]);
          else :
            $authorityLookfor = $this->record($this->driver)->getLink('name', $author);
          endif; ?>
      <span class="author-data" property="<?=$this->escapeHtml($dataFields['role'][0])?>">
        <a href="<?=$authorityLookfor?>">
          <?=$this->escapeHtml($author)?>
        </a>
        <?='(' . implode(', ', array_map(function($role) {return $this->transEsc('edm::' . $role);},array_unique($dataFields['role']))) . ')'?>
      </span>
      <?php
        // Strip whitespace before close tags to avoid spaces in front of commas:
        $formattedAuthors[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
        ob_end_clean();
       endif;
     endforeach;
   endif; ?>
  <?=implode(', ', $formattedAuthors)?><br/>
<?php endif; ?>
