<?
  // Set up page title:
  $title = $this->driver->getTitle();
  $lookfor = $this->results->getUrlQuery()->isQuerySuppressed() ? '' : $this->params->getDisplayQuery();
  if (strpos($lookfor,  'gnd_') !== FALSE) {
    $lookfor = 'GND ' . explode('_', $lookfor)[1];
  }
  if (isset($this->overrideTitle)) {
      $this->headTitle($this->overrideTitle);
  } else {
      $this->headTitle($this->translate('Search Results') . (empty($title) ? '' : " - {$title}"));
  }

  $searchIndex = $this->params->getSearchHandler();
  $searchType = $this->params->getSearchType();
  $searchClassId = $this->params->getsearchClassId();
  $agent = $this->driver->getAgentFacts($this->driver->getUniqueID(),true);

  // Set up search box:
  $this->layout()->searchbox = $this->context($this)->renderInContext(
      'search/searchbox.phtml',
      [
        'lookfor' => $agent->name . ' (' . $lookfor . ')',
        'searchIndex' => $searchIndex,
        'searchType' => $searchType,
        'searchId' => $this->results->getSearchId(),
        'searchClassId' => $searchClassId,
        'checkboxFilters' => $this->params->getCheckboxFacets(),
        'filterList' => $this->params->getFilters(),
        'hasDefaultsApplied' => $this->params->hasDefaultsApplied(),
        'selectedShards' => $this->params->getSelectedShards(),
        'ignoreHiddenFiltersInRequest' => isset($this->ignoreHiddenFiltersInRequest) ? $this->ignoreHiddenFiltersInRequest : false,
        'ignoreHiddenFilterMemory' => isset($this->ignoreHiddenFilterMemory) ? $this->ignoreHiddenFilterMemory : false,
      ]
  );

  // Enable cart if appropriate:
  $this->showBulkOptions = $this->params->getOptions()->supportsCart() && $this->showBulkOptions;
  // Checkboxes if appropriate:
  $this->showCartControls = $this->params->getOptions()->supportsCart() && $this->cart()->isActive()
    && ($this->showBulkOptions || !$this->cart()->isActiveInSearch());
  // Enable bulk options if appropriate:
  $this->showCheckboxes = $this->showCartControls || $this->showBulkOptions;

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != "full") {
    $this->headScript()->appendFile("record.js");
    $this->headScript()->appendFile("embedded_record.js");
  }

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");
  $this->headScript()->appendFile("check_save_statuses.js");

  $ignoreHiddenFilterMemory = isset($this->ignoreHiddenFilterMemory) && $this->ignoreHiddenFilterMemory;
  $ignoreHiddenFiltersInRequest = isset($this->ignoreHiddenFiltersInRequest) && $this->ignoreHiddenFiltersInRequest;
  $hiddenFilters = $this->searchtabs()->getHiddenFilters($searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
  $searchTabs = $this->searchtabs()->getTabConfig($searchClassId, $lookfor, $searchIndex, $searchType, $hiddenFilters);
  $recordTotal = $this->results->getResultTotal();?>

  <?=$this->context($this)->renderInContext('RecordDriver/SolrAuth/data-agent.phtml', ['agent' => $agent])?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <? if ($recordTotal > 0): // only display these at very top if we have results ?>
    <? foreach ($this->results->getRecommendations('top') as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>
  <? endif; ?>
  <?=$this->flashmessages()?>
  <nav class="search-header hidden-print">
    <div class="search-stats">
      <? if ($recordTotal > 0): ?>
        <?=$this->context()->renderInContext('search/controls/showing.phtml', ['lookfor' => $agent->name . ' (' . $lookfor . ')', 'recordTotal' => $recordTotal]) ?>
      <? else: ?>
        <h2><?=$this->transEsc('nohit_heading')?></h2>
      <? endif; ?>
    </div>

    <? if ($recordTotal > 0): ?>
      <div class="search-controls">
        <?=$this->render('search/controls/limit.phtml')?>
        <?=$this->render('search/controls/sort.phtml')?>
        <?=$this->render('search/controls/view.phtml')?>
      </div>
    <? endif; ?>
  </nav>
  <? /* End Listing Options */ ?>

  <? if ($recordTotal < 1): ?>
    <p>
      <? if (isset($this->overrideEmptyMessage)): ?>
        <?=$this->overrideEmptyMessage?>
      <? else: ?>
        <? $this->layout()->srmessage = $this->translate('nohit_lookfor_html', ['%%lookfor%%' => $this->escapeHtml($agent->name . ' (' . $lookfor . ')')]); ?>
        <?=$this->layout()->srmessage ?>
      <? endif; ?>
    </p>
    <? if (isset($this->parseError)): ?>
      <p class="alert alert-danger"><?=$this->transEsc('nohit_parse_error')?></p>
    <? endif; ?>
    <? foreach (($top = $this->results->getRecommendations('top')) as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>
    <? foreach ($this->results->getRecommendations('noresults') as $current): ?>
      <? if (!in_array($current, $top)): ?>
        <?=$this->recommend($current)?>
      <? endif; ?>
    <? endforeach; ?>
  <? else: ?>
    <form id="search-cart-form" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
      <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => ''])?>
    </form>
    <?=$this->render('search/list-' . $this->params->getView() . '.phtml')?>
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => 'bottom_', 'formAttr' => 'search-cart-form'])?>
    <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results, 'options' => isset($this->paginationOptions) ? $this->paginationOptions : []])?>

    <div class="searchtools hidden-print">
      <strong><?=$this->transEsc('Search Tools')?>:</strong>
      <a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>"><i class="fa fa-bell" aria-hidden="true"></i> <?=$this->transEsc('Get RSS Feed')?></a>
      &mdash;
      <a href="<?=$this->url('search-email')?>" class="mailSearch" data-lightbox id="mailSearch<?=$this->escapeHtmlAttr($this->results->getSearchId())?>">
        <i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc('Email this Search')?>
      </a>
      <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
        &mdash;
        <? if (is_numeric($this->results->getSearchId())): ?>
          <? if ($this->results->isSavedSearch()): ?>
            <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($this->results->getSearchId())?>"><i class="fa fa-remove" aria-hidden="true"></i> <?=$this->transEsc('save_search_remove')?></a>
          <? else: ?>
            <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($this->results->getSearchId())?>"><i class="fa fa-save" aria-hidden="true"></i> <?=$this->transEsc('save_search')?></a>
          <? endif; ?>
        <? endif; ?>
      <? endif; ?>
    </div>
  <? endif; ?>
</div>
<? /* End Main Listing */ ?>

<? /* Narrow Search Options */ ?>
<div class="<?=$this->layoutClass('sidebar')?>">
  <? foreach ($this->results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <? endforeach; ?>
</div>
<? /* End Narrow Search Options */ ?>
