<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));
  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }
  $this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
  <div id="searchAndNews">
    <div class="well well-lg clearfix">
      <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true, 'checkboxFilters' => $this->checkboxFacets])?>
      <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
    </div>
    <?=$this->render("news/stream.phtml")?>
    <div class="alert alert-info">
      <?=$this->transEsc("Infotextstart")?>
      <a href="http://performing-arts.eu/EventSearch/Results?lookfor=König+Lear&type=AllFields&limit=20"><?=$this->transEsc("Infotextmid")?></a>
      <?=$this->transEsc("Infotextend")?>
      <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc("Feedback")?>&nbsp;<i class="fa fa-envelope fa-fw" aria-hidden="true"></i></a>
    </div>
  </div>
</div>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
