<?php $this->headTitle($this->translate('AllResults')); ?>

<h1><?=$this->transEsc('AllResults') ?></h1>

<p>
  <?=$this->transEsc('MoreExplanation') ?>
  <div class="flexing">
  <div><img class="iconR" src="<?=$this->imageLink('icons/boxes_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('search-results')?>?lookfor=<?=$this->escapeHtml($lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Record")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/person_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('personsearch-results')?>?lookfor=<?=$this->escapeHtml($lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Person")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/buildings_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('corporationsearch-results')?>?lookfor=<?=$this->escapeHtml($lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Corporation")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/calendar4-event_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('eventsearch-results')?>?lookfor=<?=$this->escapeHtml($lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Event")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/lightbulb_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('worksearch-results')?>?lookfor=<?=$this->escapeHtml($lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Work")?></a></div>
</div>
</p>
