<?php $this->headTitle($this->translate('Find more hits')); ?>

<h1><?=$this->transEsc('Find more hits') ?></h1>

<p>
  There are more results in total. If you decide for a search type from below, you can see more results.
  <div class="flexing">
  <div><img class="iconR" src="<?=$this->imageLink('icons/boxes_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('search-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Record")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/person_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('personsearch-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Person")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/buildings_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('corporationsearch-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Corporation")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/calendar4-event_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('eventsearch-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Event")?></a></div>
  <div><img class="iconR" src="<?=$this->imageLink('icons/lightbulb_color.svg')?>" alt="Icon" width="32" height="32"><a href="<?=$this->url('worksearch-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Work")?></a></div>
</div>
</p>
