<?php $this->headTitle($this->translate('Find more hits')); ?>

<h1><?=$this->transEsc('Find more hits') ?></h1>

<p>
  There are more results in total. If you decide for a search type from below, you can see more results.
  <div>
  <i class="fa fa-regular fa-calendar"></i>&nbsp;<a href="<?=$this->url('eventsearch-results')?>?lookfor=<?=$this->escapeHtml($this->lookfor)?>" data-lightbox-ignore><?=$this->transEsc("Event")?></a><br/>
  </div>
</p>
