<?php if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <?php foreach ($searchTabs as $tab): ?>
      <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
        <li id="<?=$tab['id']?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
          <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <?=$this->transEsc($tab['label']); ?></a>
          <?php if(!$tab['selected']):?>
            <?php $script = <<<JS
              $(document).ready(function() {
                addTotalResults("{$tab['id']}","{$tab['url']}");
              })
              JS;
            ?>
            <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <?php endif; ?>
        </li>
      <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
