<?php if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <?php foreach ($searchTabs as $tab): ?>
      <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
        <li id="<?=$tab['id']?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
          <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <!--<div class="loader"></div>--> <?=$this->transEsc($tab['label']); ?></a>
        <?php if (!$tab['selected'] && strpos($tab['id'],"SolrEvent") !== FALSE) :
                $url = str_replace("/EventSearch/Results", "/AJAX/json", $tab['url']);
              elseif  (!$tab['selected'] && $tab['id'] === "SolrAuthor"):
                $url = str_replace("/AgentSearch/Results", "/AJAX/json", $tab['url']);
              elseif  (!$tab['selected'] && $tab['id'] === "Solr"):
                $url = str_replace("/Search/Results", "/AJAX/json", $tab['url']);
              endif;
              if (isset($url) && !$tab['selected']) {
                $var = <<<JS
                  $(document).ready(function() {
                    $.getJSON("{$url}", {method: "GetTotalResults",searchClassId: "{$tab['id']}"},
                  function (data) {
                    $("#{$tab['id']} > a").append(data['data']['localizedTotal']);
                  });
                });
JS;
              $this->headScript()->appendScript($var);
          }?>
        </li>
      <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
