<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
        <li id="<?=$tab["id"]?>"<?=$tab['selected'] ? ' class="active"' : ''?>>
          <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
        <? if ($tab["id"] === "SolrAuth" && !$tab['selected']) :
            $url = str_replace("/Authority/Search", "/AJAX/json", $tab["url"]);
            $var = <<<JS
    var url = "{$url}";
    $(document).ready(function() {
      $.getJSON(url, {method: "getResultTotal",searchClassId: "{$tab['id']}"},
      function (data) {
        $("#SolrAuth > a").append(" <small>("+data["data"]+")</small>");
      });
    });
JS;
        $this->headScript()->appendScript($var); ?>

        <? elseif  ($tab['id'] === "Solr" && !$tab['selected']): ?>
            <? $url = str_replace("/Search/Results", "/AJAX/json", $tab["url"]);
                $var = <<<JS
                    var url = "{$url}";
                    $(document).ready(function() {
                      $.getJSON(url, {method: "getResultTotal",searchClassId: "{$tab['id']}"},
                        function (data) {
                          $("#Solr > a").append(" <small>("+data["data"]+")</small>");
                        });
                      });
JS;
            $this->headScript()->appendScript($var); ?>
        <? endif; ?>

</li>
    <? endforeach; ?>
  </ul>
<? endif; ?>
