<?
    $this->headTitle('Akademie der Künste Berlin, Archiv Darstellende Kunst');
?>

<h2>Akademie der Künste Berlin, Archiv Darstellende Kunst</h2>
<p><a href="https://archiv.adk.de/"
    target="_blank">Direkt zum Katalog</a></p>

<p>Das Archiv sammelt, bewahrt, erschließt Bestände von Regisseuren, Intendanten im Bereich
    Sprech- und Musiktheater, von Schauspielern, Tänzern und Choreographen, Bühnenbildnern,
    Kritikern, Theaterwissenschaftlern, Dramatikern, Dramaturgen, Kabarettisten und Komponisten
    vorrangig für den Bereich Kabarett. Mit Hilfe der Methode der Inszenierungsdokumentation
    werden im Bereich Theaterdokumentation Arbeitsprozesse und -ergebnisse aktueller Inszenierungen
    führender Regisseure des Sprech- und Musiktheaters festgehalten.</p>
