<?
    $this->headTitle('Akademie der Künste Berlin, Bibliothek');
?>

<h2>Akademie der Künste Berlin, Bibliothek</h2>
<p><a href="https://opac.adk.de/"
    target="_blank">Direkt zum Katalog</a></p>

<p>Die Bibliothek verfügt über einen Bestand von mehr als 600.000 Bänden und umfasst
    alle Sparten der Künste. Der Sammelschwerpunkt liegt auf Werken der Mitglieder und
    Preisträger der Akademie, ergänzt werden die Bestände um zahlreiche Sondersammlungen,
    besonders herausragend z.B. zum Expressionismus und zur Exilliteratur zwischen 1933
    und 1945. Darüber hinaus besitzt die Bibliothek umfangreiche Sammlungen von Bühnenmanuskripten,
    nationalen und internationalen Ausstellungskatalogen, seltenen Zeitschriften sowie
    Bibliotheken von Institutionen und Künstlervereinigungen.  Für das Portal des
    Fachinformationsdienstes Darstellende Kunst wurden fachspezifische Nachlass- und
    Sammlungsbibliotheken ausgewählt, darunter z.B. Bertolt Brecht, Bernhard Minetti,
    Herbert Ihering und Christoph Schlingensief. </p>
