<?
    $this->headTitle('Alexander Street Press');
?>

<h2>Alexander Street Press: Drama-Package  und Theatre on Video</h2>
<p><a href="http://alexanderstreet.com/" target="_blank">Direkt zum Verlag</a></p>

<p>Der Datenbankanbieter Alexander Street Press bietet ein breites Portfolio Volltextdatenbanken und
    Videokollektionen für die Theater- und Tanzwissenschaft an.
    <p>Der FID Darstellende Kunst hat folgende sieben Datenbanken lizenziert:
        <ul>
            <li>Asian American Drama vereint mehr als 250 Stücke, zusammen mit biographischen, Produktions- und Theaterinformationen.</li>
            <li>Black Drama: Second Edition enthält die Volltexte von 1.462 Dramen von 233 Autoren aus Nordamerika, dem
                englischsprachigen Afrika und der Karibik von der Mitte des 19. Jahrhunderts bis heute.</li>
            <li>Latino Literature enthält mehr als 100.000 Seiten Poesie, Kurzgeschichten, Romane und mehr als 450 Theaterstücke.</li>
            <li>North American Theatre Online deckt Themen zum Theater von der Kolonialzeit bis zur Gegenwart ab</li>
            <li>North American Women's Drama enthält 1500 Stücke, die von US-Amerikanerinnen oder Kanadierinnen verfasst wurden.</li>
            <li>North American Indian Drama enthält mehr als 240 Werke zur dramatischen Literatur nordamerikanischer
                Autoren indigener Abstammung des 20. Jahrhunderts.</li>
            <li>Theatre in Video ist ein Online-Service mit Live-Aufnahmen und filmischen Adaptionen von über 250 Aufführungen
                vorwiegend englischsprachiger Theaterstücke im Streaming-Video-Verfahren.</li>
        </ul>
    </p>
</p>
