<?
    $this->headTitle('Deutsches Tanzfilminstitut Bremen');
?>

<h2>Deutsches Tanzfilminstitut Bremen</h2>
<p><a href="http://www.deutsches-tanzfilminstitut.de/?cat=222"
    target="_blank">Zur Webseite des Archives</a></p>

<p>Das Deutsche Tanzfilminstitut Bremen ist ein nationales Archiv zur Sammlung,
  Aufbereitung und Produktion von audiovisuellen Tanzdokumenten. 1988 als
  Nonprofit-Organisation gegründet, unterstützt das Institut durch die Bereitstellung
  der gesammelten Materialien die Arbeit von Choreografen, Tanzkompanien, Theatern,
  Fachjournalisten und Fernsehanstalten und hilft bei der Produktion,  Restauration
  und Digitalisierung von Tanzvideos und Filmen.</p>
