<?
    $this->headTitle('Deutsches Tanzarchiv Köln');
?>

<h2>Deutsches Tanzarchiv Köln- Auszug aus der archivinternen Datenbank des Deutschen Tanzarchivs Köln (TIS-Tanzinformationssystem)</h2>
<p><a href="http://www.sk-kultur.de/tanz"
    target="_blank">Zur Webseite des Archives</a></p>

<p>Das Archiv beherbergt über 400 Nachlässe und Sammlungen von Tänzern, Choreographen,
  Tanzpädagogen und Ballettkritikern (Harald Kreutzberg, Kurt Jooss, die Duncans, die
  Sacharoffs, Mary Wigman, Dore Hoyer, usw). Die Fotosammlung umfasst über 300.000
  Aufnahmen / Negative sowie Fotografennachlässe (Siegfried Enkelmann, Dietmar Dünhöft,
  Hans Rama, usw.). Ferner verfügt das Archiv über eine umfangreiche Kunstsammlung
  (Nachlässe von Ernst Oppler, Arthur Grunenberg etc.) sowie eine Kostüm- und Plakatsammlung.
  Die Dokumentation archiviert rund 650.000 Zeitungsausschnitte seit den 1950er Jahren und
  auch zu Sachthemen wie Ausdruckstanz (1920er/1930er Jahre), sowie etwa 30.000 Programmhefte.</p>
<p>Die Bibliothek umfasst ca. 14.000 Titel und rund 20.000 Fachzeitschriftenhefte.
  Die Videothek betreut über 4.500 Filme: Kamera-Choreographien, filmische Inszenierungen,
  experimentelle Tanzfilme, Musicals, Dokumentationen, Bühnenaufzeichnungen.</p>
