<?
    $this->headTitle('Deutsches Theatermuseum München');
?>

<h2>Deutsches Theatermuseum München</h2>
<p><a href="http://www.bayerische-bibliographie.de/avanti/dtm/opac.html"
    target="_blank">Direkt zum Katalog</a></p>

<p>Das Deutsche Theatermuseum in München hat es sich zur Aufgabe gemacht, die Theatergeschichte Münchens,
    Bayerns und Deutschlands möglichst lückenlos zu bewahren und zu dokumentieren. Darüber hinaus sammelt es -
    gemäß seiner Tradition - alle erreichbaren Objekte zur Weltgeschichte des Theaters, insbesondere, wenn sie
    Einflüsse auf oder durch das deutsche Theater belegen. Das Theatermuseum besitzt zudem die weltweit
    umfangreichste Sammlung an Theaterfotografien. Insgesamt bewahrt es unter anderem ca. 250.000 grafische Blätter,
    ca. 500.000 Autographen und ca. 4,3 Millionen Theaterfotografien. Die Bibliothek des Deutschen Theatermuseums
    ist eine Präsenzbibliothek und nimmt nur eingeschränkt am Fernleihverkehr teil.
    Eine umfassende Recherche ist daher nur vor Ort möglich.</p>
