<?
    // Set page title
    $this->headTitle('Digitalisierungsprojekt Düsseldorfer Theaterzettel der Universitäts- und Landesbibliothek Düsseldorf');
?>

<h2>Digitalisierungsprojekt Düsseldorfer Theaterzettel der Universitäts- und Landesbibliothek Düsseldorf</h2>
<p><a href="http://digital.ub.uni-duesseldorf.de/theaterzettel" target="_blank">Direkt zur Einrichtung</a></p>

<p>In dem von der Deutschen Forschungsgemeinschaft (DFG) geförderten Projekt werden ca. 13.000 Theaterzettel
    von Düsseldorfer Theatern aus den Jahren 1802 bis 1918 erschlossen und digitalisiert.
    Besonderes Augenmerk wird auf die Erschließungstiefe gelegt: So werden nicht nur die Regisseure,
    Autoren und Komponisten der jeweiligen Stücke in den Katalog aufgenommen, sondern nach Möglichkeit
    auch alle weiteren beteiligten Personen, vor allem die Schauspielerinnen und Schauspieler.</p>
