<?
    $this->headTitle('Universitätsbibliothek Frankfurt am Main - Fachinformationsdienst Darstellende Kunst');
?>

<h2>Universitätsbibliothek Frankfurt am Main - Fachinformationsdienst Darstellende Kunst</h2>
<p><a href="https://hds.hebis.de/ubffm/Search/Advanced" target="_blank">Direkt zum Katalog</a></p>

<p>In diesem Katalogausschnitt der UB Frankfurt finden Sie die für die Theater- und Filmwissenschaft
    relevanten Bücher und Nichtbuchmaterialien (AV-Medien, Noten, Illustrationen etc.) ab Erscheinungsjahr
    1986 sowie Print- und Online-Zeitschriften (alle Erscheinungsjahre). Der Bestand wird im Rahmen des
    Fachinformationsdienstes Darstellende Kunst fortlaufend ergänzt.</p>
