<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
      // Set page title
      $this->headTitle('Theatersammlung Komplex Mauerbach des Don Juan Archivs Wien');
?>
<h2>Theatersammlung Komplex Mauerbach des Don Juan Archivs Wien</h2>
<p><a href="http://www.donjuanarchiv.at/historischer-bestand/komplex-mauerbach.html"
  target="_blank">Direkt zur Einrichtung</a></p>
<p>Der Komplex Mauerbach (KMB) ist eine Theatersammlung, bestehend aus rund 2.975 Bänden mit etwa 4.500
  Theatertexten und Libretti. Gedruckt wurden diese von der Mitte des 18. Jahrhunderts bis um 1930 im
  deutschsprachigen Raum (etwa in Wien, Berlin, Leipzig), zumeist in deutscher Sprache.</p>
<? } else {
  // Set page title
  $this->headTitle('Komplex Mauerbach Theatre Collection owned by the Don Juan Archive in Vienna');
?>
<h2>Komplex Mauerbach Theatre Collection owned by the Don Juan Archive in Vienna</h2>
<p><a href="http://www.donjuanarchiv.at/historischer-bestand/komplex-mauerbach.html"
    target="_blank">View the items online</a></p>
<p>The Komplex Mauerbach (KMB) is a theatre collection which consists of about 2,975 volumes with approximately
  4,500 theatre scripts and librettos which were printed mostly in German between the mid-18th century and 1930
  in the German-speaking countries (in cities such as Vienna, Berlin, and Leipzig). </p>
<? } ?>
