<?
    // Set page title
    $this->headTitle('Theatersammlung Komplex Mauerbach des Don Juan Archivs Wien');
?>

<h2>Theatersammlung Komplex Mauerbach des Don Juan Archivs Wien</h2>
<p><a href="http://www.donjuanarchiv.at/historischer-bestand/komplex-mauerbach.html"
  target="_blank">Direkt zur Einrichtung</a></p>

<p>Der Komplex Mauerbach (KMB) ist eine Theatersammlung, bestehend aus rund 2.975 Bänden mit etwa 4.500
  Theatertexten und Libretti. Gedruckt wurden diese von der Mitte des 18. Jahrhunderts bis um 1930 im
  deutschsprachigen Raum (etwa in Wien, Berlin, Leipzig), zumeist in deutscher Sprache.</p>
