<?
    $this->headTitle('Mime Centrum Berlin');
?>

<h2>Mime Centrum Berlin</h2>
<p><a href="http://archiv.mimecentrum.de/"
    target="_blank">Direkt zum Katalog</a></p>

<p>Das MIME CENTRUM BERLIN (MCB) ist ein offener Ort der Produktion, Weiterbildung,
  der Kooperation und des internationalen Austausches. Es versteht sich als eine
  moderne Serviceinstitution für Theaterakteure sowie für die Vermittlung von
  Kunstprozeß und Öffentlichkeit.</p>
<p>Die Dokumentationsbasis des MCB besteht aus der Mediathek für Tanz und Theater.
  Die DOKUMENTATIONEN zu Künstlern, Gruppen, Festivals, zu europäischen Theaterschulen
  und Ausbildungszentren bilden einen Fundus an INFORMATIONEN und Kontakten. Darüber
  hinaus spielen VIDEOPRODUKTIONEN als Referenz- und Analysemedium für Bewegungstheater
  eine wichtige Rolle. Das Videostudio realisiert die Aufzeichnung von ausgewählten
  Aufführungen, erstellt Schnittfassungen und Dokumentationen.</p>
