<?
    $this->headTitle('Aufsatzdatenbanken/Online Contents Darstellende Kunst');
?>

<h2>Aufsatzdatenbanken/Online Contents Darstellende Kunst</h2>
<p><a href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/?COOKIE=U203,K203,I251,B1999++++++,SN,NDefault+login,D3.6,Ee61732b8-0,A,H,R141.2.32.198,FY"
    target="_blank">Direkt zum Angebot</a></p>

<p>Die Datenbank Online Contents (kurz OLC) Darstellende Kunst erschließt Inhaltsverzeichnisse von
    fachrelevanten Zeitschriften aus dem Bereich Theater, Tanz und Performancekunst nach Autor und Titel.
    Betreut wird diese kostenlose und frei zugängliche Datenbank von der
    <a href="http://www.ub.uni-franfurt.de" target="_blank">Universitätsbibliothek Frankfurt am Main</a>.</p>
