<?
    $this->headTitle('Schweizerische Theatersammlung Bern');
?>

<h2>Schweizerische Theatersammlung Bern</h2>
<p><a href="http://www.theatersammlung.ch/"
    target="_blank">Zur Webseite der Sammlung</a></p>

<p>Die Schweizerische Theatersammlung ist eine nationale Dokumentationsstelle des
  Schweizer Theaterschaffens. Sie  wurde als Privatinitiative von Theaterakteuren
  1927 gegründet und 1978 überführt in eine privatrechtliche Stiftung mit Sitz in Bern.
  Seit ihrer Gründung erschließt die Theatersammlung die Metadaten zu den Schweizer
  Theaterveranstaltungen und archiviert die vielfältigen Dokumente, die bei der
  Vorbereitung, Ankündigung, Durchführung, Aufzeichnung, Beschreibung und Rezeption
  der Theaterinszenierungen aller Sparten und Formen entstehen. Sie besitzt auch die
  größte Fachbibliothek mit Büchern, Periodika und Stücktexten zum Schweizer Theaterwesen.</p>
<p>Ein Großteil ihres Sammelgutes stammt aus dem 20. Jahrhundert und aus der Gegenwart.
  Die Bibliothek der Schweizerischen Theatersammlung umfasst rund 80.000 Titel zum
  Theaterwesen (Schauspiel, Oper, Operette, Musical, Tanz/Bühnentanz) sowie zu Randgebieten
  wie Figurentheater, Kabarett, Varieté, Zirkus, Schaustellung, theaterbezogenes Brauchtum,
  und Spielformen in den Medien.  Seit 1. September 1993 werden Buchneuzugänge elektronisch
  im <a href="http://aleph.unibas.ch/menu.html" target="_blank">Bibliotheksverbund IDS Basel-Bern</a> katalogisiert.
  Zurzeit können die <a href="http://www.theatersammlung.ch/archiv/erschliessung" target="_blank">Repertorien-Datenbanken</a>
  zum <a href="http://www.theatersammlung.ch/?q=search_berufstheater" target="_blank">Berufstheater</a> und zum
  <a href="http://www.theatersammlung.ch/?q=search_amateure" target="_blank">Amateurtheater</a> online recherchiert werden.
</p>
