<?
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Schweizerische Theatersammlung Bern');
?>
<h2>Schweizerische Theatersammlung Bern</h2>
<p><a href="http://www.theatersammlung.ch/"
    target="_blank" data-lightbox-ignore>Zur Webseite der Sammlung</a></p>
<p>Die Schweizerische Theatersammlung ist eine nationale Dokumentationsstelle des
  Schweizer Theaterschaffens. Sie  wurde als Privatinitiative von Theaterakteuren
  1927 gegründet und 1978 überführt in eine privatrechtliche Stiftung mit Sitz in Bern.
  Seit ihrer Gründung erschließt die Theatersammlung die Metadaten zu den Schweizer
  Theaterveranstaltungen und archiviert die vielfältigen Dokumente, die bei der
  Vorbereitung, Ankündigung, Durchführung, Aufzeichnung, Beschreibung und Rezeption
  der Theaterinszenierungen aller Sparten und Formen entstehen. Sie besitzt auch die
  größte Fachbibliothek mit Büchern, Periodika und Stücktexten zum Schweizer Theaterwesen.</p>
<p>Ein Großteil ihres Sammelgutes stammt aus dem 20. Jahrhundert und aus der Gegenwart.
  Die Bibliothek der Schweizerischen Theatersammlung umfasst rund 80.000 Titel zum
  Theaterwesen (Schauspiel, Oper, Operette, Musical, Tanz/Bühnentanz) sowie zu Randgebieten
  wie Figurentheater, Kabarett, Varieté, Zirkus, Schaustellung, theaterbezogenes Brauchtum,
  und Spielformen in den Medien.  Seit 1. September 1993 werden Buchneuzugänge elektronisch
  im <a href="http://aleph.unibas.ch/menu.html" target="_blank" data-lightbox-ignore>Bibliotheksverbund IDS Basel-Bern</a> katalogisiert.
  Zurzeit können die <a href="http://www.theatersammlung.ch/archiv/erschliessung" target="_blank" data-lightbox-ignore>Repertorien-Datenbanken</a>
  zum <a href="http://www.theatersammlung.ch/?q=search_berufstheater" target="_blank" data-lightbox-ignore>Berufstheater</a> und zum
  <a href="http://www.theatersammlung.ch/?q=search_amateure" target="_blank" data-lightbox-ignore>Amateurtheater</a> online recherchiert werden.
</p>
<? } else {
  // Set page title
  $this->headTitle('Swiss Theatre Collection, Bern');
?>
<h2>Swiss Theatre Collection, Bern</h2>
<p><a href="http://www.theatersammlung.ch/"
    target="_blank" data-lightbox-ignore>To the collection</a></p>
<p>The library of the Swiss Theatre Collection houses approximately 80,000 titles on theatre-related
  topics (acting, opera, operetta, musicals, dance/stage dance) as well as on niche topics such as
  puppet theatre, cabaret, variety theatre, the circus, exhibits, traditions in the world of theatre,
  and variations of performance in the media. Since September 1st 1993, newly acquired books have been
  catalogued electronically in the
  <a href="http://aleph.unibas.ch/menu.html" target="_blank" data-lightbox-ignore>Basel-Bern Library Association IDS</a>.
  Currently the <a href="http://www.theatersammlung.ch/archiv/erschliessung" target="_blank" data-lightbox-ignore>repertoire databases</a>
  on <a href="http://www.theatersammlung.ch/?q=search_berufstheater" target="_blank" data-lightbox-ignore>professional theatre</a> and
  <a href="http://www.theatersammlung.ch/?q=search_amateure" target="_blank" data-lightbox-ignore>amateur theatre</a> can be searched online.
</p>
<? } ?>
