<?
    $this->headTitle('Tanzarchiv Leipzig e.V.');
?>

<h2>Tanzarchiv Leipzig e.V.</h2>
<p><a href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070"
    target="_blank">Zur Webseite des Archives</a></p>

<p>Gegründet 1957 von Kurt Petermann als Sammlung traditionell überlieferter Folklore
  erweiterte sich das Tanzarchiv Leipzig zu einer Dokumentationsstelle zu "allen
  Gebieten des Tanzes". Bis zu seinem Tod im Jahr 1984 etablierte Petermann das Archiv
  als eine anerkannte Einrichtung der Auseinandersetzung mit Tanz als kulturellem Phänomen
  und erreichte 1975 die Angliederung an die Akademie der Künste der DDR. Seit 1993 arbeitet
  das Tanzarchiv Leipzig als gemeinnütziger Verein, begründet von der Universität Leipzig
  und der Hochschule für Musik und Theater "Felix Mendelssohn Bartholdy". 2011 wurde das
  Tanzarchiv Leipzig in die Verantwortung der UBL übergeben. Die Bestände gliedern sich
  in eine Fachbibliothek und die Sammlungen des Tanzarchivs. Dazu gehören Filmaufnahmen aus
  der zweiten Hälfte des 20. Jh., Literatursammlungen, Nachlässe und Teilnachlässe, Plakate,
  Fotografien, Postkarten, Mikrofilme und Archivmaterial. Die Bestände sind teilweise in
  einer Datenbank erschlossen, die in den Sondersammlungen und an den Computern in der
  UBL benutzt werden kann.</p>
