<?
    $this->headTitle('Teatro Español del Siglo de Oro');
?>

<h2>Teatro Español del Siglo de Oro</h2>
<p><a href="http://www.nationallizenzen.de/angebote/nlproduct.2006-03-10.7433818373" 
  target="_blank">Direkt zum Produkt</a></p>

<p>850 Werke der 16 prominentesten Vertreter, u. a. Cervantes, Lope de Vega, Calderón de la Barca,
  des spanischen goldenen Zeitalters sind als Volltext recherchierbar. Die Periode zwischen 1500 und
  1700 bildet den Höhepunkt des intellektuellen und künstlerischen Schaffens in Spanien. Für die Auswahl
  zeichnet ein internationales Herausgeberteam verantwortlich.<br />
  Die Suche kann wahlweise über eine englische oder eine spanische Oberfläche erfolgen.
</p>
