<?
    $this->headTitle('Tanzfonds Erbe');
?>

<h2>Tanzfonds Erbe - Förderung von künstlerischen Projekten zum Tanz im 20. Jahrhundert</h2>
<p><a href="http://tanzfonds.de/home/"
    target="_blank">Direkt zur Einrichtung</a></p>

<p>Tanzfonds.de ist die Webseite der beiden Förderfonds Tanzfonds Erbe und Tanzfonds
  Partner, die die Kulturstiftung des Bundes 2011 initiiert hat. Projektträger ist
  <a href="http://www.diehl-ritter.de/" target="_blank">DIEHL+RITTER</a>. Während
  Tanzfonds Partner – Fonds für Partnerschaften zwischen Tanzinstitutionen und Schulen
  – im Jahr 2014 auslief, wurde Tanzfonds Erbe bis 2018 verlängert. Auf der Webseite
  finden Sie Informationen zur Antragsstellung, die Videodokumentationen der Tanzfonds
  Erbe-Projekte sowie weiterführende Beiträge zum Thema Tanzerbe. Im FID-Portal
  www.performing-arts.eu sind die Projektdokumentationen der Förderfonds recherchierbar.</p>
