<?
    $this->headTitle('Theatermuseum der Landeshauptstadt Düsseldorf');
?>

<h2>Theatermuseum der Landeshauptstadt Düsseldorf</h2>
<p><a href="https://emuseum.duesseldorf.de/search/advanced/Objects"
    target="_blank">Direkt zum Katalog</a></p>

<p>Das Theatermuseum ging aus dem 1938 gegründeten privaten Theaterarchiv des
  "Schauspielhaus Düsseldorf Dumont-Lindemann“ (1904-1933) hervor und befindet
  sich nach der Schenkung von Gustaf Lindemann seit 1947 im Besitz der Stadt.
  Schwerpunkt für Sammlung, Forschung, Dokumentation und Ausstellungen ist heute
  die Theatergeschichte Düsseldorfs und der Region seit dem 16. Jahrhundert. Der
  Bestand umfasst vielfältige theaterbezogenen Sammlungen: Fotos, die grafische
  Sammlung, Quellen zur Theaterpraxis, audiovisuelle Medien, Handschriften, die
  Presseausschnittsammlung, dreidimensionale Objekte und eine wissenschaftliche
  Spezialbibliothek, wobei die Bestände vorwiegend aus dem 20. und 21. Jahrhundert stammen.</p>
