<?
    $this->headTitle('Transcript-Verlag');
?>

<h2>Transcript-Verlag: eBook-Frontlist 2015-2017 Theater- und Tanzwissenschaft</h2>
<p><a href="http://www.transcript-verlag.de/programmbereiche/kulturwissenschaften/theater-und-tanzwissenschaft/?f=79385"
    target="_blank">Direkt zum Verlag</a></p>

<p>Der transcript Verlag ist ein wissenschaftlicher Fachverlag mit Schwerpunkten in den Kultur- und Sozialwissenschaften.
    Für die Theater-, Tanz- und Performancewissenschaft bietet transcript ein umfassendes Spektrum an Veröffentlichungen an.
    Hier ist u.a. die Reihe Tanzscripte (Hg. Brandstetter/Klein) angesiedelt und es werden zahlreiche Dissertationen und
    Tagungsbände publiziert, u.a. die Beiträge zum Kongress der Fachgesellschaft für Theaterwissenschaft.</p>
