<?
    $this->headTitle('Freie Universität Berlin, Institut für Theaterwissenschaft, Theaterhistorische Sammlungen');
?>

<h2>Freie Universität Berlin, Institut für Theaterwissenschaft, Theaterhistorische Sammlungen</h2>
<p><a href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/Sammlung_Walter_Unruh/IfT_Sammlungen_Bestandsliste_20160406.pdf"
    target="_blank">Zur Bestandsübersicht</a></p>

<p>In den Theaterhistorischen Sammlungen des Instituts stehen dazu umfangreiche Archivbestände
  insbesondere zur Berliner Theatergeschichte des 18. Bis 21. Jahrhunderts zur Verfügung
  (Schwerpunkt um 1900 bis 1950er Jahre). Sie sind grundsätzlich öffentlich zugänglich und
  werden unentgeltlich im Bereich der Institutsbibliothek zur Einsichtnahme vorgelegt.
  Mit der Theaterhistorischen Sammlung Walter Unruh  betreut das Institut eine der größten
  ehemaligen Privatsammlungen dieser Art. Darüber hinaus finden sich im Institutsarchiv weitere
  bedeutende Künstlernachlässe sowie umfangreiche Foto-, Theaterzettel- und Presseausschnittsammlungen.
  Insbesondere die Programmheftsammlung wird aktiv weitergeführt.</p>
