<h2><?=$this->transEsc("news::CurrentNews")?></h2>
<div class="card">
  <p><a class="link" href="<?=$this->url('news-archive')?>"><?=$this->transEsc("news::ArchivedNews")?></a></p>

  <?php foreach ($pinnedlist as $pin) : ?>
    <div class="news">
      <img src="<?=$this->imageLink('pin.png')?>">
      <?=$this->render("news/newsitem.phtml", ['data' => $pin])?>
    </div>
  <?php endforeach; ?>
  <?php foreach ($newslist as $news) : ?>
    <div class="news">
      <?=$this->render("news/newsitem.phtml", ['data' => $news])?>
    </div>
  <?php endforeach; ?>

</div>
