<h2><?=$this->transEsc("news::CreateOrEdit")?></h2>

<form action="<?=$this->url('news-list')?>">
  <button class="btn btn-primary" type="submit"><?=$this->transEsc("news::BackToList")?></button>
</form>

<form class="newsEdit" accept-charset="UTF-8" enctype="multipart/form-data" data-toggle="validator" method="POST" action="<?=$this->url('news-list')?>">
  <input type="hidden" name="id" value="<?=$article['id']?>">
  <input type="hidden" name="guid" value="<?=$article['guid']?>">
  <input type="hidden" name="active" value="<?=$article['active']?>">
  <input type="hidden" name="pin" value="<?=$article['pin']?>">

  <div class="form-group row">
    <label><?=$this->transEsc("Title")?> *</label>
    <input class="form-control" type="text" name="title" required="true" maxlength="200" value="<?=htmlentities($article['title']);?>">
  </div>

  <div class="form-group row">
    <label><?=$this->transEsc("Description")?> *</label>
    <textarea class="form-control" type="text" name="description" required="true" rows="4" maxlength="500"><?=htmlentities($article['description']);?></textarea>
  </div>

  <div class="form-group row">
    <label><?=$this->transEsc("Fulltext")?> *</label>
    <textarea class="form-control" name="text" required="true" rows="25"><?=htmlentities($article['text'])?></textarea>
  </div>

  <div class="form-group row">
    <label><?=$this->transEsc("Source RSS")?> *</label>
    <input class="form-control" type="text" name="source" required="true" maxlength="200" value="<?=htmlentities($article['source'])?>">
  </div>

  <fieldset class="form-group">
    <legend><?=$this->transEsc("Author RSS")?></legend>
    <div class="form-check">
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="author" id="fid"
        value="redaktion@performing-arts.eu (Fachinformationsdienst Darstellende Kunst)"
        <?php if ($article['author'] == 'redaktion@performing-arts.eu (Fachinformationsdienst Darstellende Kunst)') {echo 'checked';}?>>
        Fachinformationsdienst Darstellende Kunst
      </label>
    </div>
    <div class="form-check">
    <label class="form-check-label">
        <input type="radio" class="form-check-input" name="author" id="gtw"
        value="info@theater-wissenschaft.de (Gesellschaft fuer Theaterwissenschaft)"
        <?php if ($article['author'] == 'info@theater-wissenschaft.de (Gesellschaft fuer Theaterwissenschaft)') {echo 'checked';}?>>
        Gesellschaft für Theaterwissenschaft
      </label>
    </div>
  </fieldset>

  <fieldset class="form-group">
    <legend><?=$this->transEsc("Picture")?></legend>
    <div class="form-check">
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="enclosure" value="fid-dk_logo.gif"
        <?php if ($article['enclosure'] == 'fid-dk_logo.gif') {echo 'checked';}?>>
        <img src="<?=$this->imageLink('fid-dk_logo.gif')?>" width="250px" height="auto">
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="enclosure" value="gtw_logo.png"
        <?php if ($article['enclosure'] == 'gtw_logo.png') {echo 'checked';}?>>
        <img src="<?=$this->imageLink('gtw_logo.png')?>" width="150px" height="auto">
      </label>
    </div>
</fieldset>

<fieldset class="form-group">
  <legend><?=$this->transEsc("Start / End")?></legend>
  <div class="form-check">
    <label><?=$this->transEsc("Startdate")?> *</label>
    <input class="form-control date" type="text" name="startdate" placeholder="YYYY-MM-DD" required="true" maxlength="10" value="<?=$article['startdate']?>">
  </div><br/>
  <div class="form-check">
    <label><?=$this->transEsc("Enddate")?> *</label>
    <input class="form-control date" type="text" name="enddate" placeholder="YYYY-MM-DD" required="true" maxlength="10" value="<?=$article['enddate']?>">
  </div>
</fieldset>

  <fieldset class="form-group">
    <legend><?=$this->transEsc("Category")?></legend>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Call for Papers / Participation"
        <?php if ($article['category']=='Call for Papers / Participation') {echo 'checked';}?>>
        Call for Papers / Participation
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Events"
        <?php if ($article['category']=='Events') {echo 'checked';}?>>
        <?=$this->transEsc("Events");?>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Announcements"
        <?php if ($article['category']=='Announcements') {echo 'checked';}?>>
        <?=$this->transEsc("Announcements");?>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Jobs"
        <?php if ($article['category']=='Jobs') {echo 'checked';}?>>
        <?=$this->transEsc("Jobs");?>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Book Reviews"
        <?php if ($article['category']=='Book Reviews') {echo 'checked';}?>>
        <?=$this->transEsc("Book Reviews");?>
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
        <input type="checkbox" class="form-check-input" name="category" value="Other"
        <?php if ($article['category']=='Other') {echo 'checked';}?>>
        <?=$this->transEsc("Other");?>
      </label>
    </div>
</fieldset>

<fieldset class="form-group">
  <legend><?=$this->transEsc("URLs")?></legend>
  <?php for ($i=1; $i < 4; $i++) :
    $name = 'urlname' . $i;
    $url = 'url' . $i; ?>
  <div class="form-group">
    <label><?=$this->transEsc("URL Name") . ' ' . $i?></label>
    <input class="form-control" type="text" name="<?=$name?>" maxlength="100" value="<?=htmlentities($article[$name])?>">
  </div>
  <div class="form-group">
    <label><?=$this->transEsc("URL") . ' ' . $i?></label>
    <input class="form-control" type="text" name="<?=$url?>" maxlength="200" value="<?=htmlentities($article[$url])?>">
  </div>
  <?php endfor;?>
</fieldset>

<fieldset class="form-group">
  <legend><?=$this->transEsc("Downloads") ." (" . $this->transEsc("File size") . " <= 3MB)"?></legend>
  <?php for ($i=1; $i < 4; $i++) :
     $name = 'dlname' . $i;
     $url = 'dl' . $i; ?>
  <div class="form-group">
    <label><?=$this->transEsc("Download Name") . ' ' . $i?></label>
    <input class="form-control" type="text" name="<?=$name?>" maxlength="100" value="<?=htmlentities($article[$name])?>">
  </div>
  <div class="form-group">
    <label><?=$this->transEsc("Download") . ' ' . $i?></label>
    <input type="file" data-upload name="<?=$url?>">
  </div>
  <?php endfor;?>
</fieldset>

<div class="form-group row">
  <button class="btn btn-primary" type="SUBMIT"><?=$this->transEsc("Save")?></button>
</div>

</form>

<?php if(isset($article->lastedit)) : ?>
<div><?=$this->transEsc("Last edited") . ': ' . date_format(date_create($article->lastedit), "d.m.Y - H:i:s");?>
  <?php if(isset($article->user)) : ?>
    <?=' ' . $this->transEsc("by") . ' ' . $article->user;?>
  <?php endif; ?></div><br/>
<?php endif; ?>
