<?php if ($admin) : ?>
    <?=$this->headTitle('News')?>
    <h2><?=$this->transEsc('News')?></h2>

    <div class="news_menu">
        <form action="<?=$this->url('news-edit')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-pencil" aria-hidden="true"></i> <?=$this->transEsc('news::Create News')?></button>
        </form>
        <form action="<?=$this->url('news-current')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-newspaper-o" aria-hidden="true"></i> <?=$this->transEsc('news::CurrentNews')?></button>
        </form>
        <form action="<?=$this->url('news-archive')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-newspaper-o" aria-hidden="true"></i> <?=$this->transEsc('news::ArchivedNews')?></button>
        </form>
        <form action="<?=$this->url('search-home')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc('news::Stream')?></button>
        </form>
        <form method="post" action="<?=$this->url('news-list')?>" autocomplete="off">
            <input type="text" name="searchNews" size="20" maxlength="100" value="">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i> <?=$this->transEsc('news::Search News')?></button>
        </form>
    </div>

    <?php if (isset($searchlist)) : ?>
      <h3><?=$this->transEsc('Results') . ' (' . count($searchlist) . ')'?></h3>
      <?=$this->render("news/newstable.phtml", ['datalist' => $searchlist])?>
    <?php endif; ?>

    <?php if (isset($newslist)) : ?>
      <h3><?=$this->transEsc('List')?></h3>
      <?=$this->render("news/newstable.phtml", ['datalist' => $newslist])?>
    <?php endif; ?>

<?php else : ?>
  <h1> You don't have permission to be here!</h1>
<?php endif; ?>
