<?php if ($admin) : ?>
    <?=$this->headTitle('News');?>
    <h2><?=$this->transEsc('News')?></h2>

    <div class="news_menu">
        <form action="<?=$this->url('news-edit')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-pencil" aria-hidden="true"></i> <?=$this->transEsc('news::Create News')?></button>
        </form>
        <form action="<?=$this->url('news-current')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-newspaper-o" aria-hidden="true"></i> <?=$this->transEsc('news::CurrentNews')?></button>
        </form>
        <form action="<?=$this->url('news-archive')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-newspaper-o" aria-hidden="true"></i> <?=$this->transEsc('news::ArchivedNews')?></button>
        </form>
        <form action="<?=$this->url('search-home')?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc('news::Stream')?></button>
        </form>
        <form method="post" action="<?=$this->url('news-list')?>" autocomplete="off">
            <input type="text" name="searchNews" size="20" maxlength="100" value="">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i> <?=$this->transEsc('news::Search News')?></button>
        </form>
    </div>

    <?php if (isset($searchlist)) : ?>
        <h3><?=$this->transEsc('Results') . ' (' . count($searchlist) . ')'?></h3>

        <table class="newstable table-striped">
            <tr>
                <th><?=$this->transEsc('Title')?></th>
                <th><?=$this->transEsc('news::Editor')?></th>
                <th><?=$this->transEsc('news::Startdate')?></th>
                <th><?=$this->transEsc('news::Enddate')?></th>
                <th><?=$this->transEsc('Edit')?></th>
                <th><?=$this->transEsc('Delete')?></th>
                <th><?=$this->transEsc('news::Active')?></th>
                <th><?=$this->transEsc('news::Pin')?></th>
            </tr>
            <?php foreach ($searchlist as $news) : ?>
            <tr>
              <td><a href="<?=$this->url('news-article')?>?guid=<?=$news->guid?>"><?=htmlentities($news->title)?></a></td>
              <td><?=$news->user?></td>
              <td><?php if ($news->startdate!=null) { echo date_format(date_create($news->startdate), "d.m.Y");}?></td>
              <td><?php if ($news->enddate!=null) { echo date_format(date_create($news->enddate), "d.m.Y");}?></td>
              <td><a href="<?=$this->url('news-edit')?>?id=<?=$news->id?>"><i class="fa fa-pencil"></i></a></td>
              <td><a href="<?=$this->url('news-list')?>?do=del&amp;id=<?=$news->id?>"><i class="fa fa-trash-o"></i></a></td>
              <td><a href="<?=$this->url('news-list')?>?do=act&amp;id=<?=$news->id?>"><?php if ($news->active==true):?><i class="fa fa-check"></i><?php else: ?><i class="fa fa-ban"></i><?php endif;?></a></td>
              <td><a href="<?=$this->url('news-list')?>?do=pin&amp;id=<?=$news->id?>"><?php if ($news->pin==true):?><i class="fa fa-ban"></i><?php else: ?><i class="fa fa-check"></i><?php endif; ?></a></td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>

    <?php if (isset($newslist)) : ?>
    <h3><?=$this->transEsc('List')?></h3>
    <table class="newstable table-striped">
        <tr>
            <th><?=$this->transEsc('Title')?></th>
            <th><?=$this->transEsc('Editor')?></th>
            <th><?=$this->transEsc('news::Startdate')?></th>
            <th><?=$this->transEsc('news::Enddate')?></th>
            <th><?=$this->transEsc('Edit')?></th>
            <th><?=$this->transEsc('Delete')?></th>
            <th><?=$this->transEsc('news::Active')?></th>
            <th><?=$this->transEsc('news::Pin')?></th>
        </tr>
        <?php foreach ($newslist as $news) : ?>
        <tr>
          <td><a href="<?=$this->url('news-article')?>?guid=<?=$news->guid?>"><?=htmlentities($news->title)?></a></td>
          <td><?=$news->user?></td>
          <td><?php if ($news->startdate!=null) { echo date_format(date_create($news->startdate), "d.m.Y");}?></td>
          <td><?php if ($news->enddate!=null) { echo date_format(date_create($news->enddate), "d.m.Y");}?></td>
          <td><a href="<?=$this->url('news-edit')?>?id=<?=$news->id?>"><i class="fa fa-pencil"></i></a></td>
          <td><a href="<?=$this->url('news-list')?>?do=del&amp;id=<?=$news->id?>" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></a></td>
          <td><a href="<?=$this->url('news-list')?>?do=act&amp;id=<?=$news->id?>"><?php if ($news->active==true) : ?><i class="fa fa-check"></i><?php else:?><i class="fa fa-ban"></i><?php endif; ?></a></td>
          <td><a href="<?=$this->url('news-list')?>?do=pin&amp;id=<?=$news->id?>"><?php if ($news->pin==true) : ?><i class="fa fa-ban"></i><?php else: ?><i class="fa fa-check"></i><?php endif; ?></a></td>
        </tr>
      <?php endforeach; ?>
    </table>
  <?php endif; ?>

<?php else : ?>
  <h1> You don't have permission to be here!</h1>
<?php endif; ?>
