<?php if (isset($newslist)):?>
<div class="stream">
  <div class="stream well well-lg clearfix">
    <p class="title"><?=$this->transEsc("Newsstream")?></p>
    <?php foreach ($pinnedlist as $pin) : ?>
      <div class="pinned_news">
        <?php if ($pin->enclosure!=null || $pin->enclosure!='') : ?>
          <div class="news_pic">
            <img src="<?=$this->imageLink($pin->enclosure)?>" width="80" height="60" alt="<?=$pin->author?>">
          </div>
        <?php endif; ?>
        <span class="newsdate">
          <?php if ($pin->startdate!=null) : ?>
            <?=date_format(date_create($pin->startdate), "d.m.Y") . ' - ' . $this->transEsc('news::'.$pin->category)?>
          <?php endif; ?>
        </span><br/>
        <b><?=htmlentities($pin->title)?></b><br/>
        <?=htmlentities(substr($pin->description,0, 200)).'...'?><br/>
        <a href="<?=$this->url('news-article')?>?guid=<?=$pin->guid?>" data-lightbox-ignore><?=$this->transEsc("news::FurtherInfo")?></a>
      </div>
    <?php endforeach; ?>
    <?php foreach ($newslist as $news) : ?>
      <div class="news">
        <?php if ($news->enclosure!=null || $news->enclosure!='') : ?>
          <div class="news_pic">
            <img src="<?=$this->imageLink($news->enclosure)?>" style="max-width:100%" height="auto" alt="<?=$news->author?>">
          </div>
        <?php endif; ?>
        <span class="newsdate">
          <?php if ($news->startdate!=null) : ?>
           <?=date_format(date_create($news->startdate), "d.m.Y") . ' - ' . $this->transEsc('news::'.$news->category)?>
          <?php endif; ?>
        </span><br/>
        <b><?=htmlentities($news->title)?></b><br/>
        <?=htmlentities(substr($news->description,0, 200)).'...'?><br/>
        <a href="<?=$this->url('news-article')?>?guid=<?=$news->guid?>" data-lightbox-ignore><?=$this->transEsc("news::FurtherInfo")?></a>
      </div>
    <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>
