<?php if (isset($newslist)):?>
<div class="stream">
  <div class="stream well well-lg clearfix">
    <p class="title"><?=$this->transEsc("Newsstream")?></p>
    <?php foreach ($pinnedlist as $pin) : ?>
      <div class="news">
        <img src="<?=$this->imageLink('pin.png')?>">
        <?=$this->render("news/newsitem_stream.phtml", ['data' => $pin])?>
      </div>
    <?php endforeach; ?>
    <?php foreach ($newslist as $news) : ?>
      <div class="news">
        <?=$this->render("news/newsitem_stream.phtml", ['data' => $news])?>      
      </div>
    <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>
