<?php
  $this->metadata()->generateMetatags($this->driver);
  $recordType = $this->driver->getRecordType();
  $recordIcon = $this->driver->getRecordIcon();
?>
<h2><img src="<?=$this->imageLink($recordIcon)?>" alt="Icon" width="48" height="48"></img>
    <?=$this->escapeHtml($this->driver->getTitle())?></h2>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $alignment = $this->record($this->driver)->getThumbnailAlignment('result');
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
  ?>
  <?php if (($QRCode || $cover || $preview) && $alignment == 'left') : ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
      $relatedFields = $formatter->getData($driver, $formatter->getDefaults('ResourceRelated'));
      $provider = $formatter->getData($driver, $formatter->getDefaults('Provider'));
      $seeAlso = $formatter->getData($driver, $formatter->getDefaults('SeeAlso'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <div class="data-table">
        <table class="table">
          <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
          <?php foreach ($coreFields as $current): ?>
            <tr><th><?=$this->transEsc($current['label'])?></th><td><?=$current['value']?></td></tr>
          <?php endforeach; ?>
          <?php foreach ($relatedFields as $current): ?>
            <?php switch ($current['label']) {
        case 'dc:contributor':
          $entity = 'Person';
          $icon = 'icons/person_color.svg';
          break;
        case 'RelatedEvents':
            $entity = 'Event';
            $icon = 'icons/calendar4-event_color.svg';
            break;
        case 'RelatedWorks':
            $entity = 'Work';
            $icon = 'icons/lightbulb_color.svg';
            break;
        case '':
          break; 
        } ?>
            <tr><th><?=$this->transEsc("edm::".$current['label'])?><div><img src="<?=$this->imageLink($icon)?>" alt="Icon" width="32" height="32"></div></th><td><?=$current['value']?></td></tr>
          <?php endforeach; ?>
        </table>
      </div>
    <?php endif; ?>    
    <?php if (!empty($seeAlso)): ?>
      <hr class="wmar">
      <div class="seeAlso data-table">
      <h3><i class="fa fa-regular fa-link"></i>&nbsp;<?=$this->transEsc("Zugänge")?></h3>
        <table class="table">
          <?php foreach ($seeAlso as $current): ?>
            <tr><th><?=$this->transEsc($current['label'])?></th><td><?=$current['value']?></td></tr>
          <?php endforeach; ?>
        </table>
      </div>
    <?php endif; ?> 
    <?php /* End Main Details */ ?>
  </div>
  <div class="media-body-right">
    <?php if ($coverDetails['cover'] && $alignment == 'right'): ?>
      <div class="media-right <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
        <?=$cover?>
      </div>
    <?php endif ?>
    <?php if (!empty($provider)): ?>
      <div class="provider">
      <h3><img src="<?=$this->imageLink("icons/arrow-repeat.svg")?>" alt="Icon" width="32" height="32">&nbsp;<?=$this->transEsc("Institution")?></h3>
        <table class="table">
          <?php foreach ($provider as $current): ?>
            <tr><th><?=$this->transEsc($current['label'])?></th><td><?=$current['value']?></td></tr>
          <?php endforeach; ?>
        </table>
      </div>
    <?php endif; ?>
    <?=$this->record($this->driver)->getToolbar()?>
  </div>

</div>
