<? foreach ($data as $key => $field): ?>
  <? switch ($key) {
       case 'isbn':
          foreach ($field as $isbn): ?>
              <span property="isbn"><?=$this->escapeHtml($isbn)?></span>
          <? endforeach;
       break;
       case 'extent':
       foreach ($field as $extent): ?>
           <span property="extent"><?=$this->escapeHtml($extent)?></span>
       <? endforeach;
     break;
    default:
    break;
  }?>
  <br/>
<? endforeach; ?>
