<table class="table table-inside">
<?php $institution = isset($data["edm:dataProvider"][0]) ? current($data["edm:dataProvider"][0]) : '';?>
<?php foreach ($data as $key => $fields): ?>
  <?php $count = sizeof($fields);?>
  <tr>
    <th><?php if (strpos($key,':')) : ?>
      <?=$this->transEsc('edm::' . $key);?>
    <?php else : ?>
      <?=$this->transEsc($key);?>
    <?php endif; ?></th>
    <?php if ($count > 4) : ?>
      <?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
      <?php $rest = array_slice($fields, 4); ?>
      <?php $fields = array_slice($fields, 0, 4);?>
      <td>
        <?php foreach ($fields as $field) : ?>
         <?php foreach ($field as $resource => $seeAlso) : ?>
          <?php if ($key == 'edm:isShownAt' && ($institution == 'Alexander Street Press' || $institution == 'transcript Verlag' || $institution == 'Adam Matthew Digital')) : ?>
             <a href="<?=$this->url('content-page', ['page' => 'licensed']) . '?link=' . key($field)?>"><?=$this->transEsc("FullTextByFID");?></a>
             <img src="<?=$this->imageLink("fid-dk_logo_nur-Taenzer.png")?>" style="width:7%"/><br />
          <?php else: ?>
            <a href="<?=$resource?>" target="_blank"><?=$this->escapeHtml($seeAlso)?></a><br/>
          <?php endif; ?>
        <?php endforeach; ?>
      <?php endforeach; ?>
        <?php if (!(empty($rest))) : ?>
        <span class="toggleContainer">
          <input type="checkbox" class="toggle" id="toggle_<?=$key?>">
          <span> <?php foreach ($rest as $field) : ?>
            <?php foreach ($field as $resource => $seeAlso): ?>
           <?php if ($key == 'edm:isShownAt' && ($institution == 'Alexander Street Press' || $institution == 'transcript Verlag' || $institution == 'Adam Matthew Digital')) : ?>
              <a href="<?=$this->url('content-page', ['page' => 'licensed']) . '?link=' . key($field)?>"><?=$this->transEsc("FullTextByFID");?></a>
              <img src="<?=$this->imageLink("fid-dk_logo_nur-Taenzer.png")?>" style="width:7%"/><br />
           <?php else: ?>
             <a href="<?=$resource?>" target="_blank"><?=$this->escapeHtml($seeAlso)?></a><br/>
           <?php endif; ?>
         <?php endforeach; ?>
         <?php endforeach; ?>
        </span>
        <?php if ($lang =='de') : ?>
         <label for="toggle_<?=$key?>" class="label_de"></label>
        <?php else : ?>
         <label for="toggle_<?=$key?>" class="label_en"></label>
        <?php endif; ?>
        </span>
        <?php endif; ?>
     </td>
    <?php else: ?>
    <td>
      <?php foreach ($fields as $type => $field) : ?>
       <?php foreach ($field as $resource => $seeAlso) : ?>
        <?php if ($key == 'edm:isShownAt' && ($institution == 'Alexander Street Press' || $institution == 'transcript Verlag'  || $institution == 'Adam Matthew Digital')) : ?>
           <a href="<?=$this->url('content-page', ['page' => 'licensed']) . '?link=' . key($field)?>"><?=$this->transEsc("FullTextByFID");?></a>
           <img src="<?=$this->imageLink("fid-dk_logo_nur-Taenzer.png")?>" style="width:7%"/><br />
         <?php elseif ($key == 'Ask Archive' && $type == 'CallNumber') : ?>
       <?php elseif ($key == 'Ask Archive' && $type == 'Mail' && isset($fields['CallNumber'][0])) : ?>
             <?php $trans = $this->transEsc(substr($seeAlso,0,7)) . substr($seeAlso,7);?>
             <a class="mail-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'EMail') . '?callNumber=' . $fields['CallNumber'][0]?>" rel="nofollow"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$trans?></a>
         <?php elseif ($key == 'child_records') : ?>
             <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', ['%%count%%' => $seeAlso])?></a>
        <?php else: ?>
          <a href="<?=$resource?>" target="_blank"><?=$this->escapeHtml($seeAlso)?></a><br/>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endforeach; ?>
   </td>
    <?php endif; ?>
  </tr>
<?php endforeach; ?>
</table>
