<?php
  $containerSource = $this->driver->getSourceIdentifier();
  $containerIDs = $this->driver->getContainerRecordID();
  $volumes = $this->driver->getVolume();
  $i = 0;
  $ref = $this->driver->getContainerReference();
  if ($containerIDs) :
    //TODO: Fix me!
    $containers = sizeof($containerIDs) == sizeof($data) ? array_combine($containerIDs,$data) : [];
    $volumes = sizeof($containerIDs) == sizeof($volumes) ? $volumes : [implode($volumes, ', ')];
    $containerLinks = [];
    foreach ($containers as $containerID => $containerTitle) :
      ob_start();
      $link = $containerID
        ? $this->recordLink()->getUrl("$containerSource|$containerID")
        : (isset($highlight) ? $this->record($this->driver)->getLink('journaltitle', $containerTitle)
        : $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $containerTitle)));
      $containerTitle = isset($highlight) ? $this->highlight($containerTitle) : $this->escapeHtml($containerTitle); ?>
      <a href="<?=$link?>"><?=$containerTitle?></a>
      <?=isset($volumes[$i]) && !empty($volumes[$i]) ? '[' . $this->escapeHtml($volumes[$i]) . ']' : '' ?>
      <?php $i++; ?>
      <?=empty($ref) ? '' : $this->escapeHtml($ref)?>
      <?php $containerLinks[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
        ob_end_clean();
    endforeach;?>
    <?=implode(', ', $containerLinks)?>
  <?php elseif($data): ?>
    <?php foreach ($data as $containerTitle):
      ob_start();
      $link = $this->record($this->driver)->getLink('journaltitle', $containerTitle); ?>
      <a href="<?=$link?>"><?=$this->escapeHtml($containerTitle)?></a>
      <?=isset($volumes[$i]) && !empty($volumes[$i]) ? '[' . $this->escapeHtml($volumes[$i]) . ']' : ''?>
      <?php $i++; ?>
      <?php $containerLinks[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
        ob_end_clean();
    endforeach; ?>
    <?=implode(', ', $containerLinks)?>
  <?php endif;?>
