<? foreach ($data as $field): ?>
  <? $dates = $field["dates"];?>
  <? $places = $field["places"];?>
  <? $names = $field["names"];?>
  <? $i = 0; ?>
  <? while (isset($names[$i]) || isset($dates[$i]) || isset($places[$i])) : ?>
  <? if (isset($places[$i])) : ?>
    <?=$this->escapeHtml($places[$i]);?>
    <? if (isset($names[$i]) || isset($dates[$i])): ?>
      <?=" : "?>
    <? endif; ?>
  <? endif; ?>
  <? if (isset($names[$i]) && isset($dates[$i])): ?>
    <?=$this->escapeHtml($names[$i])?><?=","?>
    <?=$this->escapeHtml($dates[$i])?>
  <? elseif (isset($names[$i])) : ?>
    <?=$this->escapeHtml($names[$i])?>
  <? elseif (isset($dates[$i])) : ?>
     <?=$this->escapeHtml($dates[$i])?>
  <? endif; ?>
  <? if (isset($names[$i+1]) || isset($dates[$i+1]) || isset($places[$i+1])) : ?>
  <?="; "?>
<? endif; ?>
  <? $i++; ?>
<? endwhile; ?>
   <br/>
<? endforeach; ?>
