<? foreach ($data as $field): ?>
    <? $agent = $field[0]; ?>
    <? $agentID = $agent[0]; ?>
    <? if ($agent[1]) : ?>
    <? if ($agentID != '' and $this->driver->checkExistence($agentID,'SolrAuth')) : ?>
      <a href="<?=$this->url('search-authorityresults')?>?lookfor=<?=$agentID?>&amp;type=agentID">
        <?=$this->escapeHtml($agent[1])?></a><br/>
    <? else : ?>
      <?=$this->escapeHtml($agent[1])?><br/>
    <? endif; ?>
  <? endif; ?>
<? endforeach; ?>
