<table class="table table-inside">
<? foreach ($data as $key => $fields): ?>
  <tr>
    <th><?=$this->transEsc($key);?></th>
    <td>
      <? foreach ($fields as $field) : ?>
       <? foreach ($field as $resource => $seeAlso) : ?>
         <? if ($key == 'Related' || $key == 'Digital Copies') : ?>
           <a href="<?=$resource?>"><?=$this->escapeHtml($seeAlso)?></a><br/>
        <? elseif ($key == 'Fulltext') : ?>
           <a href="<?=$this->url('spages-licensed') . '?link=' . key($field)?>"><?=$this->transEsc("FullTextByFID");?></a>
           <img src="/vufind/themes/fiddk/images/fid-dk_logo_nur-Taenzer.png" style="width:7%"/><br />
        <? else: ?>
          <a href="<?=$resource?>" target="_blank"><?=$this->escapeHtml($seeAlso)?></a><br/>
        <? endif; ?>
      <? endforeach; ?>
    <? endforeach; ?>
   </td>
  </tr>
<? endforeach; ?>
</table>
