<table class="table table-inside">
    <span property="agents">
<? foreach ($data as $key => $field): ?>
    <tr>
      <th><?=$this->transEsc('edm::' . $key);?></th>
      <td><? foreach ($field as $agent): ?>
    <? $agentID = $agent[0]; ?>
    <? if ($agentID != '' and $this->driver->checkExistence($agentID,'SolrAuth')) : ?>
      <a href="<?=$this->url('search-authorityresults')?>?lookfor=<?=$agentID?>&amp;type=agentID">
        <span property="<?=$key?>"><?=$this->escapeHtml($agent[1])?></span></a><br/>
    <? else : ?>
      <span property="<?=$key?>"><?=$this->escapeHtml($agent[1])?></span><br/>
    <? endif; ?>
  <? endforeach; ?>
   </td>
  </tr>
<? endforeach; ?>
</span>
</table>
