<? $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<table class="table table-inside">
<? foreach ($data as $key => $field): ?>
  <? if ($key == 'dc:language') : ?>
  <? $prefix = 'iso639-1::';?>
  <? else: ?>
  <? $prefix = '';?>
  <? endif;?>
  <tr>
    <th><?=$this->transEsc('edm::' . $key);?></th>
    <td>
  <? foreach ($field as $k => $value) : ?>
  <? if ($key == 'dcterms:tableOfContents') : ?>
    <span property="<?=$key?>">
      <?$toc = array_filter(explode('--', $value), 'trim');?>
      <ul class="toc">
        <? foreach ($toc as $line): ?>
          <li><?=$this->escapeHtml($line)?></li>
        <? endforeach; ?>
      </ul>
    </span>
  <? elseif ($key == 'dc:description') : ?>
    <? $words = explode(' ', $value);?>
    <? if (sizeof($words) <= 30) : ?>
        <? if ($prefix) : ?>
            <span property="<?=$key?>"><?=$this->transEsc($prefix . $value);?></span><br/>
        <? else : ?>
            <span property="<?=$key?>"><?=nl2br(str_replace("&lt;br /&gt;","\n",$this->escapeHtml($value)));?></span><br/>
        <? endif; ?>
    <? else : ?>
        <? $start = array_slice($words, 0, 30);?>
        <? $rest = array_slice($words, 30);?>
        <?=nl2br(str_replace("&lt;br /&gt;","\n",$this->escapeHtml(implode($start,' ') . ' ')));?>
        <span class="toggleContainer">
          <input type="checkbox" class="toggle" id="toggle_<?=$k?>">
          <span><?=nl2br(str_replace("&lt;br /&gt;","\n",$this->escapeHtml(implode($rest,' '))));?></span>
          <? if ($lang =='de') : ?>
             <label for="toggle_<?=$k?>" class="label_de"></label>
          <? else : ?>
             <label for="toggle_<?=$k?>" class="label_en"></label>
          <? endif; ?>
        </span><br/>
    <? endif; ?>
  <? else : ?>
    <? if ($prefix) : ?>
    <span property="<?=$key?>"><?=$this->transEsc($prefix . $value);?></span><br/>
    <? else : ?>
    <span property="<?=$key?>"><?=$this->escapeHtml($value);?></span><br/>
    <? endif; ?>
  <? endif;?>
  <? endforeach; ?>
   </td>
  </tr>
<? endforeach; ?>
</table>
