<?php
  $containerSource = $this->driver->getSourceIdentifier();
  $containerIDs = $this->driver->getContainerRecordID();
  $ref = $this->driver->getContainerReference();
  if ($containerIDs) :
    $containers = array_combine($containerIDs,$data);
    $containerLinks = [];
    foreach ($containers as $containerID => $containerTitle) :
      ob_start();
      $link = $containerID
        ? $this->recordLink()->getUrl("$containerSource|$containerID")
        : $this->record($this->driver)->getLink('journaltitle', $containerTitle); ?>
      <a href="<?=$link?>"><?=$this->escapeHtml($containerTitle)?></a>
      <?=empty($ref) ? '' : $this->escapeHtml($ref)?>
      <?php $containerLinks[] = trim(preg_replace('/\s+<\//', '</', ob_get_contents()));
        ob_end_clean();
    endforeach;?>
    <?=implode(', ', $containerLinks)?>
  <?php endif;?>
