<?php foreach ($data as $inst => $links): ?>
  <?php if (isset($links[0]) && isset($links[1])): ?>
  <a href="<?=$links[0]?>" target="_blank"><?=$this->escapeHtml($inst)?></a>
  <!--a class="providerInfo" data-lightbox href="/vufind/DataProvider/dtk"><i class="fa fa-info-circle" aria-hidden="true"></i></a><br/-->
  <hr>
  <a href="<?=$this->url('agentrecord')?><?=$links[1]?>"><?=$this->transEsc("More_of_this_provider")?></a-->
  <?php endif; ?>
<?php endforeach; ?>
