<?php foreach ($data as $key => $field):
  $place = $field->getPlace();
  $date = $field->getDate(); ?>
  <span property="publisher" typeof="Organization">
  <?php if (!empty($place)): ?>
    <img src="<?=$this->imageLink("icons/geo-alt.svg")?>" alt="Icon" width="16" height="16"></img>&nbsp;<span property="location"><?=$this->escapeHtml($place)?></span>
  <?php endif; ?>
  <?php if (!empty($date)):
    if (!empty($place)): ?>
      : <span property="date"><?=$this->driver->translateDate($date, 'de')?></span>
    <?php else: ?>
      <img src="<?=$this->imageLink("icons/calendar4-event.svg")?>" alt="Icon" width="16" height="16"></img>&nbsp;<span property="date"><?=$this->driver->translateDate($date, 'de')?></span>
    <?php endif; ?>
  <?php endif; ?>
</span><?php if ($key + 1 != count($data)):?>; <?php endif; ?>
<?php endforeach; ?>
<br/>
