<?php if (sizeof($data) > 5) :
    $lang = $this->plugin('translate')->getTranslator()->getLocale();
    $rest = array_slice($data, 5);
    $data = array_slice($data, 0, 5);
  endif;
  foreach ($data as $link => $field): ?>
    <a href="<?=$link?>" target="_blank"><?=$this->escapeHtml($field)?></a><br/>
  <?php endforeach; ?>
<?php if (!(empty($rest))) : ?>
<span class="toggleContainer">
  <input type="checkbox" class="toggle" id="toggle_subject">
  <span><?php foreach ($rest as $link => $field): ?>
    <a href="<?=$link?>" target="_blank"><?=$this->escapeHtml($field)?></a><br/>
  <?php endforeach; ?></span>
  </div>
  <?php if ($lang =='de') : ?>
     <label for="toggle_subject" class="label_de"></label>
  <?php else : ?>
     <label for="toggle_subject" class="label_en"></label>
  <?php endif; ?>
</span><br/>
<?php endif; ?>
