<? foreach ($data as $field): ?>
  <? $pubDate = $field->getDate();?>
  <? $pubPlace = $field->getPlace();?>
  <? $pubName = $field->getName();?>
  <? if (!empty($pubPlace) && (!empty($pubName) || !empty($pubDate))): ?>
    <?=$this->escapeHtml($pubPlace) . " : "?>
  <? else : ?>
    <?=$this->escapeHtml($pubPlace)?>
  <? endif; ?>
  <? if (!empty($pubName) && !empty($pubDate)): ?>
    <span property="publisher"><?=$this->escapeHtml($pubName)?></span><?=","?>
    <?=$this->escapeHtml($pubDate)?>
  <? elseif (!empty($pubName)) : ?>
    <span property="publisher"><?=$this->escapeHtml($pubName)?></span>
  <? elseif (!empty($pubDate)) : ?>
     <?=$this->escapeHtml($pubDate)?>
  <? endif; ?>
  <br/>
<? endforeach; ?>
