<?php foreach ($data as $id => $field): ?>
  <?php $eventDate = $this->driver->getEventDate($id);
        $lang = $this->plugin('translate')->getTranslator()->getLocale();?>
  <a href="<?=$this->url('eventrecord')?><?=$id?>"><?=$this->escapeHtml($field)?></a>
  <?php if (isset($eventDate)):?>
    <?="("?><img src="<?=$this->imageLink("icons/calendar4-event.svg")?>" alt="Icon" width="16" height="16"></img>&nbsp;<?=$this->driver->translateDate($eventDate[0], $lang) . ")"?>
  <?php endif;?><br/>
<?php endforeach; ?>
