<? if ($agent->name) : ?>
<div class="agent-container">

   <? $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
   <? $sameAs = $agent->sameAs; ?>

   <? if ($agent->depiction) : ?>
      <? parse_str(parse_url($agent->depiction,PHP_URL_QUERY),$url);?>
      <div class="agent-column" style="max-width:<?=$url['width']?>px;"><img src="<?=$agent->depiction?>" alt="<?=$this->transEsc('Depiction')?>"/></div>
   <? endif; ?>

   <div class="agent-column">
      <h2 id="agentName"><?=$agent->name;?></h2>

      <? $birthDate = $agent->birthDate;
         $birthPlace = $agent->birthPlace;
         $deathDate = $agent->deathDate;
         $deathPlace = $agent->deathPlace; ?>

            <? if ($birthDate or $birthPlace) : ?>
              <span property="born">
                 <?=$this->transEsc("born")?>
                 <? if ($birthDate) : ?>
                 <span property="birthDate">
                    <?=$birthDate?>
                 </span>
                 <? endif; ?>
                 <? if ($birthPlace) : ?>
                 <?=$this->transEsc("in")?>
                 <span property="birthPlace">
                    <?=$birthPlace?>
                 </span>
                 <? endif; ?>
              </span><br/>
            <? endif; ?>

            <? if ($deathDate or $deathPlace) : ?>
              <span property="died">
                 <?=$this->transEsc("died")?>
                 <? if ($deathDate) : ?>
                 <span property="deathDate">
                    <?=$deathDate?>
                 </span>
                 <? endif; ?>
                 <? if ($deathPlace) : ?>
                 <?=$this->transEsc("in")?>
                 <span property="deathPlace">
                    <?=$deathPlace?>
                 </span>
                 <? endif; ?>
              </span><br/>
            <? endif; ?>

            <? if ($agent->establishment) : ?>
                 <?=$this->transEsc("established")?>
                 <span property="established">
                    <?=$agent->establishment?>
                 </span><br/>
            <? endif; ?>
            <? if ($agent->termination) : ?>
                 <?=$this->transEsc("terminated")?>
                 <span property="terminated">
                    <?=$agent->termination?>
                 </span><br/>
            <? endif; ?>

            <? if ($agent->prof) : ?>
              <?=implode($agent->prof,', ');?><br/>
            <? endif; ?>

            <? if ($agent->topic) : ?>
              <?=implode($agent->topic,', ');?><br/>
            <? endif; ?>

            <? if ($agent->bio) : ?>
               <br/><b><?=$this->transEsc("BiographicalDetails")?></b><br/>
               <?=$agent->bio;?><br/>
            <? endif; ?>

            <? if ($agent->placeOfActivity) : ?>
             <?=$this->transEsc("placeOfActivity") . ': ' .  implode($agent->placeOfActivity,', ');?><br/>
            <? endif; ?>

            <? if ($agent->placeOfBusiness) : ?>
             <?=$this->transEsc("placeOfBusiness") . ' ' . $this->transEsc("in") . ' ' . implode($agent->placeOfBusiness,', ');?><br/>
            <? endif; ?>

            <? if ($agent->variants) : ?>
               <br/><b><?=$this->transEsc("Variants")?></b><br/>
               <? if (sizeof($agent->variants) <= 20) : ?>
                 <?=implode($agent->variants,', ');?>
               <? else : ?>
                 <? $start = array_slice($agent->variants, 0,20);?>
                 <? $rest = array_slice($agent->variants, 20);?>
                 <?=implode($start,', ') . ', ';?>
                 <span class="toggleContainer">
                    <input type="checkbox" class="toggle" id="toggle_id">
                    <span><?=implode($rest,', ');?></span>
                    <? if ($lang =='de') : ?>
                       <label for="toggle_id" class="label_de"></label>
                    <? else : ?>
                       <label for="toggle_id" class="label_en"></label>
                    <? endif; ?>
                 </span>
               <? endif; ?>
            <? endif; ?>

         </div>

         <? if ($sameAs) : ?>
           <div class="agent-column">
             <h4><?=$this->transEsc('More Links')?></h4>
             <? foreach ($sameAs as $k => $sa) : ?>
               <a href="<?=$sa[0]?>" target="_blank"><i class="external-icon"><img src="<?=$sa[1]?>"></i><?=$this->escapeHtml($sa[2]);?></a><br/>
               <? if(array_key_exists($k+1,$sameAs)):?>
                  <hr/>
               <? endif;?>
            <? endforeach; ?>
             <br/><p><b>Quelle:</b> <a href="http://www.dnb.de/entityfacts.html">Entity Facts</a></p>
           </div>
          <? endif; ?>
</div>
<? endif; ?>
