<h2><?=$this->transEsc('Nationallicense');?></h2>
<div class="info">
<p>Wissenschaftler*innen und Interessierte,
  <ul>
    <li>die außerhalb Deutschlands</li>
    <li>bzw. nicht Angehörige einer deutschen Universität sind,</li>
  </ul>
  können ebenfalls auf die Nationallizenzen zugreifen. Diese Personen müssen sich
  zunächst als Nutzer*innen des FID Darstellende Kunst
  <a href="https://darstellende-kunst.fid-lizenzen.de/kfllogin-individual" data-lightbox-ignore target="_blank">registrieren</a>.
  Nach erfolgreichem Login können Sie standortunabhängig auf die lizenzierten Produkte zugreifen.
</p>
</div>
