<?php // Set page title.
$this->headTitle($this->translate('Advisory Board') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Advisory Board')?></h2>

<p>All of the work done in connection with the <i>SIS Performing Arts</i> is being overseen
  by an Advisory Board of experts during the funding phase. In addition to evaluating
  the services developed by the <i>SIS</i>, the Advisory Board’s meetings serve to provide
  an important source of motivation and ideas for the project. To this end, the Board’s
  members are all involved in researching and teaching subjects that reflect the entire
  range of theatre and dance studies. The members of the Advisory Board are:</p><br>

<div class="card">
  <b>Prof. Dr. Wolf Dieter Ernst</b><br>
  Professor of Theatre Studies at the University of Bayreuth<br>
  Internet: <a target="_blank" href="http://www.theaterwissenschaft-ernst.uni-bayreuth.de/de/index.html">http://www.theaterwissenschaft-ernst.uni-bayreuth.de/de/index.html</a><br>
  <br>
  <b>Marko Knepper</b><br>
  Head of Digital Library Services at the Mainz University Library<br>
  Internet: <a target="_blank" href="http://www.ub-eng.uni-mainz.de">http://www.ub-eng.uni-mainz.de</a><br>
  <br>
  <b>Dr. phil. Nic Leonhardt</b><br>
  Institute of Theatre Studies Munich<br>
  Internet: <a target="_blank" href="https://nicleonhardt.wordpress.com/">https://nicleonhardt.wordpress.com/</a><br>
  <br>
  <b>Prof. Dr. Nikolaus Müller-Schöll</b><br>
  Professor of Theatre Studies at the Institute of Theatre, Film and Media Arts, Goethe University, Frankfurt am Main<br>
  Internet: <a target="_blank" href="http://www.uni-frankfurt.de/59032336/MitarbeiterInnen">http://www.uni-frankfurt.de/59032336/MitarbeiterInnen</a><br>
  <br>
  <b>Dr. Matthias J. Pernerstorfer</b><br>
  Head of the Don Juan Archive Vienna<br>
  Internet: <a target="_blank" href="http://www.donjuanarchiv.at/home/don-juan-archiv-wien.html">http://www.donjuanarchiv.at/home/don-juan-archiv-wien.html</a><br>
  <br>
  <b>Prof. Dr. Frank-Manuel Peter</b><br>
  Head of the German Dance Archives Cologne<br>
  Internet: <a target="_blank" href="http://www.sk-kultur.de/tanz/dtk-english.html">http://www.sk-kultur.de/tanz/dtk-english.html</a><br>
  <br>
  <b>Prof. Dr. Patrick Primavesi</b><br>
  Professor of Theatre Studies at the University of Leipzig<br>
  Head of Tanzarchiv Leipzig e.V.<br>
  Internet: <a target="_blank" href="http://theaterwissenschaft.gko.uni-leipzig.de/index.php?id=65">http://theaterwissenschaft.gko.uni-leipzig.de/index.php?id=65</a><br>
  <br>
  <b>Prof. Dr. Gerald Siegmund</b><br>
  Professor of Applied Theatre Studies and Managing Director of the Institute of Applied Theatre Studies at the University of Gießen<br>
  Internet: <a target="_blank" href="http://www.inst.uni-giessen.de/theater/en">http://www.inst.uni-giessen.de/theater/en</a><br>
  <br>
  <b>Prof. Dr. Sandra Umathum</b><br>
  Professor of (Applied) Theory Dance, Context, Choreography at the Inter-University Centre for Dance Berlin (HZT)<br>
  Internet: <a target="_blank" href="http://www.hzt-berlin.de/?lan=en">http://www.hzt-berlin.de/?lan=en</a><br>
  <br>
</div>
