<?php // Set page title.
$this->headTitle($this->translate('Advisory Board') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Advisory Board')?></h2>

<p>Die gesamten Arbeiten des <i>FID Darstellende Kunst</i> werden während
der Förderung von einem wissenschaftlichen Beirat betreut. Neben
der Evaluierung der im <i>FID</i> entwickelten Serviceleistungen dienen
die Treffen des wissenschaftlichen Beirats zudem als wichtiger
Impulsgeber für den weiteren Projektverlauf. Dabei spiegeln die
Forschungs- und Lehrfelder der Beiratsmitglieder das gesamte
Spektrum der Theater- und Tanzwissenschaft wider. Folgende Personen
bilden den wissenschaftlichen Beirat:
</p><br>

<div class="card">
<b>Prof. Dr. Wolf Dieter Ernst</b><br>
Professur für Theaterwissenschaft an der Universität Bayreuth<br>
Internet: <a target="_blank" href="http://www.theaterwissenschaft-ernst.uni-bayreuth.de/de/index.html">http://www.theaterwissenschaft-ernst.uni-bayreuth.de/de/index.html</a><br>
<br>
<b>Marko Knepper</b><br>
Leiter der Digitalen Bibliotheksdienste an der Universitätsbibliothek Mainz<br>
Internet: <a target="_blank" href="http://www.ub.uni-mainz.de">http://www.ub.uni-mainz.de</a><br>
<br>
<b>Dr. phil. Nic Leonhardt</b><br>
Institut für Theaterwissenschaft München<br>
Internet: <a target="_blank" href="https://nicleonhardt.wordpress.com/">https://nicleonhardt.wordpress.com/</a><br>
<br>
<b>Prof. Dr. Nikolaus Müller-Schöll</b><br>
Professor für Theaterwissenschaft am Institut für Theater-, Film- und Medienwissenschaft der Goethe-Universität Frankfurt/Main<br>
Internet: <a target="_blank" href="http://www.uni-frankfurt.de/59032336/MitarbeiterInnen">http://www.uni-frankfurt.de/59032336/MitarbeiterInnen</a><br>
<br>
<b>Dr. Matthias J. Pernerstorfer</b><br>
Direktor des Don Juan Archiv Wien<br>
Internet: <a target="_blank" href="http://www.donjuanarchiv.at/home/don-juan-archiv-wien.html">http://www.donjuanarchiv.at/home/don-juan-archiv-wien.html</a><br>
<br>
<b>Prof. Dr. Frank-Manuel Peter</b><br>
Leiter des Deutschen Tanzarchivs Köln<br>
Internet: <a target="_blank" href="http://www.sk-kultur.de/tanz">http://www.sk-kultur.de/tanz</a><br>
<br>
<b>Prof. Dr. Patrick Primavesi</b><br>
Professor für Theaterwissenschaft an der Universität Leipzig<br>
Direktor des Tanzarchiv Leipzig e.V.<br>
Internet: <a target="_blank" href="http://theaterwissenschaft.gko.uni-leipzig.de/index.php?id=65">http://theaterwissenschaft.gko.uni-leipzig.de/index.php?id=65</a><br>
<br>
<b>Prof. Dr. Gerald Siegmund</b><br>
Professur für Angewandte Theaterwissenschaft und geschäftsführender Direktor des Institutes für angewandte Theaterwissenschaft der Universität Gießen<br>
Internet: <a target="_blank" href="http://www.inst.uni-giessen.de/theater/de">http://www.inst.uni-giessen.de/theater/de</a><br>
<br>
<b>Prof. Dr. Sandra Umathum</b><br>
Professur für (Angewandte) Theorie Tanz Choreografie Performance am Hochschulübergreifenden Zentrum Tanz Berlin (HZT)<br>
Internet: <a target="_blank" href="http://www.hzt-berlin.de">http://www.hzt-berlin.de</a><br>
</div>
