<?php // Set page title.
$this->headTitle($this->translate('Online Contents') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Online Contents (OLC) Darstellende Kunst</h2>

<div class="card">
<p>
Die Datenbank <a target="_blank" href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/">Online Contents (kurz OLC) Darstellende Kunst</a> erschließt und weist Inhaltsverzeichnisse von fachrelevanten Zeitschriften aus dem Bereich Theater, Tanz und Performancekunst sortiert nach Autor und Artikeltitel nach.
<br>
Betreut wird diese kostenlose und frei zugängliche Datenbank von der <a target="_blank" href="http://www.ub.uni-frankfurt.de/">Universitätsbibliothek Frankfurt am Main</a>.
</p>
<!--p>Gewünschte Aufsätze, die Sie nicht in Ihrer Bibliothek vor Ort finden, können Sie per Fernleihe oder
über den kostenpflichtigen Dokumentlieferdienst <a target="_blank" href="http://www.subito-doc.de/">Subito</a> bestellen.</p-->
</div>
