<?php // Set page title.
$this->headTitle($this->translate('Copyright') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Copyright')?></h2>

<div class="card">
It is the policy of the University Library Frankfurt to observe copyright law with regard to
  any copyrighted graphics, sound documents, videos and texts, or to use graphics, texts, audio
  and video files created by the Frankfurt University Library itself, or to use licence-free graphics,
  texts, audio and video files. All brands and trademarks named as part of our online services to
  which third parties own the copyright are fully subject to the provisions of the valid copyright
  law in question, and the rights of the formally registered copyright owner(s). The sole fact that
  a brand or trademark is named does not signify that the aforementioned is not subject to third-party
  rights. The copyright on materials created by the Frankfurt University Library itself and published
  or used in the public sphere is reserved to the Frankfurt University Library. Duplication or use of
  these graphics, texts, audio and video files in other electronic or printed publications is not permitted
  without the explicit agreement of the University Library Frankfurt.<br />
  We actively seek and promote external links to the online sites run under <i>performing-arts.eu</i>.
  However, no unauthorised duplication and/or republication of entire pages or articles is permitted.
</div>
