<? // Set page title.
$this->headTitle($this->translate('Copyright') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Copyright')?></h2>

<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>

<p>Die UB Frankfurt ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken,
Tondokumente, Videosequenzen und Texte zu beachten, von der UB Frankfurt selbst erstellte Grafiken,
Texte, Audio- und Videodateien zu nutzen oder auf lizenzfreie Grafiken, Texte, Audio- und
Videodateien zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte
geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils
gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein
aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte
Dritter geschützt sind! Das Copyright für veröffentlichte, von der UB Frankfurt selbst erstellte
Objekte bleibt allein bei der UB Frankfurt. Eine Vervielfältigung oder Verwendung solcher Grafiken,
Texte, Audio- und Videodateien in anderen elektronischen oder gedruckten Publikationen ist ohne
ausdrückliche Zustimmung durch die UB Frankfurt nicht gestattet.<br />
Externe Links auf die Angebote von <i>performing-arts.eu</i> sind ausdrücklich erwünscht. Eine unautorisierte
Übernahme ganzer Seiten oder ganzer Beiträge ist dagegen nicht zulässig.
</p>

<?
    } else {
?>

<p>It is the policy of the University Library Frankfurt to observe copyright law with regard to
  any copyrighted graphics, sound documents, videos and texts, or to use graphics, texts, audio
  and video files created by the Frankfurt University Library itself, or to use licence-free graphics,
  texts, audio and video files. All brands and trademarks named as part of our online services to
  which third parties own the copyright are fully subject to the provisions of the valid copyright
  law in question, and the rights of the formally registered copyright owner(s). The sole fact that
  a brand or trademark is named does not signify that the aforementioned is not subject to third-party
  rights. The copyright on materials created by the Frankfurt University Library itself and published
  or used in the public sphere is reserved to the Frankfurt University Library. Duplication or use of
  these graphics, texts, audio and video files in other electronic or printed publications is not permitted
  without the explicit agreement of the University Library Frankfurt.<br />
  We actively seek and promote external links to the online sites run under <i>performing-arts.eu</i>.
  However, no unauthorised duplication and/or republication of entire pages or articles is permitted.
</p>

<?
    }
?>
