<?php // Set page title.
$this->headTitle($this->translate('Copyright') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Copyright')?></h2>
<div class="card">
Die UB Frankfurt ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken,
Tondokumente, Videosequenzen und Texte zu beachten, von der UB Frankfurt selbst erstellte Grafiken,
Texte, Audio- und Videodateien zu nutzen oder auf lizenzfreie Grafiken, Texte, Audio- und
Videodateien zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte
geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils
gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein
aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte
Dritter geschützt sind! Das Copyright für veröffentlichte, von der UB Frankfurt selbst erstellte
Objekte bleibt allein bei der UB Frankfurt. Eine Vervielfältigung oder Verwendung solcher Grafiken,
Texte, Audio- und Videodateien in anderen elektronischen oder gedruckten Publikationen ist ohne
ausdrückliche Zustimmung durch die UB Frankfurt nicht gestattet.<br />
Externe Links auf die Angebote von <i>performing-arts.eu</i> sind ausdrücklich erwünscht. Eine unautorisierte
Übernahme ganzer Seiten oder ganzer Beiträge ist dagegen nicht zulässig.
</div>
