<?php // Set page title.
$this->headTitle($this->translate('Data Privacy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Data Privacy')?></h2>
<div class="card">
<p>Where our site offers users the opportunity to enter their data, whether personal or professional
  (e-mail addresses, names, postal addresses) this information is given by the user on a voluntary basis.
</p>

<p>The University Library Frankfurt forwards no user data to third parties without the user having given
  explicit permission and agreement. The use of data from the Website Information section or similar publically
  presented data such as postal addresses, telephone and fax numbers and e-mail addresses by third parties
  for purposes of transmitting information that has not been explicitly requested, is not permitted. The
  University Library Frankfurt reserves the right to take legal action against the unrequested transmission
  of advertising materials including spam e-mails.
</p>
</div>
