<? // Set page title.
$this->headTitle($this->translate('Data Privacy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Data Privacy')?></h2>

<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>

<p>Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder
geschäftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe
dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis.
</p>

<p>Die UB Frankfurt gibt keine nutzerbezogenen Daten an Dritte weiter, ohne dass der Nutzer
hierfür ausdrücklich seine Zustimmung erteilt hat. Die Nutzung der im Rahmen des Impressums
oder vergleichbarer Angaben veröffentlichten Kontaktdaten wie Postanschriften, Telefon- und
Faxnummern sowie Emailadressen durch Dritte zur Übersendung von nicht ausdrücklich angeforderten
Informationen ist nicht gestattet. Die UB Frankfurt behält sich rechtliche Schritte im Falle der
unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.
</p>

<?
    } else {
?>

<p>Where our site offers users the opportunity to enter their data, whether personal or professional
  (e-mail addresses, names, postal addresses) this information is given by the user on a voluntary basis.
</p>

<p>The University Library Frankfurt forwards no user data to third parties without the user having given
  explicit permission and agreement. The use of data from the Website Information section or similar publically
  presented data such as postal addresses, telephone and fax numbers and e-mail addresses by third parties
  for purposes of transmitting information that has not been explicitly requested, is not permitted. The
  University Library Frankfurt reserves the right to take legal action against the unrequested transmission
  of advertising materials including spam e-mails.
</p>

<?
    }
?>
