<?php // Set page title.
$this->headTitle($this->translate('Data Privacy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Data Privacy')?></h2>
<div class="card">
<p>Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder
geschäftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe
dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis.
</p>

<p>Die UB Frankfurt gibt keine nutzerbezogenen Daten an Dritte weiter, ohne dass der Nutzer
hierfür ausdrücklich seine Zustimmung erteilt hat. Die Nutzung der im Rahmen des Impressums
oder vergleichbarer Angaben veröffentlichten Kontaktdaten wie Postanschriften, Telefon- und
Faxnummern sowie Emailadressen durch Dritte zur Übersendung von nicht ausdrücklich angeforderten
Informationen ist nicht gestattet. Die UB Frankfurt behält sich rechtliche Schritte im Falle der
unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.
</p>
</div>
