<?php
// Set page title.
$this->headTitle($this->translate('Documentation') . ' - ' . $this->translate('FID Darstellende Kunst'));?>

<h2>Projektdokumentation</h2>

<div class="card">
<p>
Die Materialien zu Projektdokumentationen stellen wir Ihnen zur Nachnutzung frei zur Verfügung.
</p>

<ul>

<li><a target="_blank" href="<?=$this->imageLink('Dokumentenmappe_Workshop.pdf')?>">Dokumentenmappe zum <i>FID</i> Workshop „Verwahren/Aufbewahren. Über den Umgang mit
Inszenierungsartefakten“ vom 8./9. Oktober 2015</a></li>
<li><a target="_blank" href="<?=$this->imageLink('Ergebnismappe_Bundesverband_05-09-2016.pdf')?>">Dokumentenmappe zum Arbeitstreffen des Bundesverbandes der
  Bibliotheken und Museen für Darstellende Künste e.V. vom 5./6. September 2016</a></li>
<li><a target="_blank" href="https://github.com/FID-Darstellende-Kunst"><i>FID</i> Quellcodes auf der kollaborativen Entwicklerplattform GitHub</a></li>
</ul>
</div>

<div class="card">
<p>
Der Suchschlitz des <i>FID</i> kann in den eigenen Webauftritt eingebunden werden. Sie können den benötigten HTML-Codesausschnitt hier downloaden:
<form method="get" action="<?=$this->imageLink('fiddk_searchbox.zip')?>">
  <input type="submit" value="Download"/>
</form>
<br>
</p>
<p>Der Suchschlitz ist responsiv und sieht wie folgt aus:</p>
<div class="container-fluid" style="padding:5px;border:1px solid #EDEDED;">
 <div style="float:left;padding-bottom:5px;">
   <a href="http://www.performing-arts.eu/"><img src="<?=$this->imageLink('fid-dk_logo.gif')?>" style="max-width:300px;"></a>
 </div>
 <div class="well well-lg clearfix" style="float:left;margin-top:0;margin-bottom:0;margin-left:20px;min-width:300px;max-width:400px;overflow:hidden;">
    <form class="searchForm navbar-form flip" method="get" action="http://performing-arts.eu/Search/Results" name="searchForm" style="margin:0 auto;padding:0px;">
      <div class="form-group">
          <input type="text" name="lookfor" value="" class="searchForm_lookfor form-control autocomplete searcher:Solr typeSelector:searchForm_type" style="min-width:240px;"/>
        </div>
          <button type="submit" class="btn btn-primary" style="color:#FFF;background-color:#4f81bd;">
          <i class="fa fa-search" style="padding-right:4px;"></i>Suchen</button>
    </form>
  </div>
</div>
</div>

<!--
<h2>Materialien</h2>
<p>
Im Bereich <b>Materialien</b> haben wir Dokumente anderer Institutionen zusammengefasst, die für Forschung und Lehre der Theater- und Tanzwissenschaft relevant sein können.
</p>
-->
