<h2><?=$this->transEsc('Events');?></h2>
<div class="info">
<img src="<?=$this->imageLink('Events.jpg')?>" alt="Events"/>
<p>In <b>Ereignisse</b> recherchieren Sie zu Ereignissen der Darstellenden Kunst
  (<a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Aufführung%22'?>" data-lightbox-ignore>Aufführungen</a>,
  <a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Festival%22'?>" data-lightbox-ignore>Festivals</a>,
  <a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Ausstellung%22'?>" data-lightbox-ignore>Ausstellungen</a>, uvm.).</p>
</div>
