<h2><?=$this->transEsc('Events');?></h2>
<div class="info">
<img src="<?=$this->imageLink('Events.jpg')?>" alt="Events"/>
<p>In <b>Events</b>, you can search for performing arts events
  (<a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Aufführung%22'?>" data-lightbox-ignore>performances</a>,
  <a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Festival%22'?>" data-lightbox-ignore>festivals</a>,
  <a href="<?=$this->url('eventsearch-results') . '?filter[]=event_type%3A%22Ausstellung%22'?>" data-lightbox-ignore>exhibitions</a>, etc.).</p>
</div>
