<?php // Set page title.
$this->headTitle($this->translate('FAQ') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('FAQ')?></h2>

<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Wofür steht der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <p>Der an der UB Frankfurt beheimatete <i>Fachinformationsdienst (FID) Darstellende Kunst</i> bietet der Fachwelt der Theater- und
  Tanzwissenschaft einen effektiven und freien Zugang zu Informationsressourcen.<br/>
  Die Kernaufgaben des <i>FID</i>s sind der Ausbaus der Informationsinfrastruktur sowie die Entwicklung und Betreuung des
  <i>FID</i>-Portals <a href="http://www.performing-arts.eu/">http://www.performing-arts.eu/</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Wie finanziert sich der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <p>Das Projekt zum Aufbau eines <i>Fachinformationsdienstes Darstellende Kunst</i> wird seit 2015 von der Deutschen Forschungsgemeinschaft im Rahmen
  des Förderprogramms <a target="_blank" href="http://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinformationsdienste_wissenschaft/">Fachinformationsdienste für die Wissenschaft</a> finanziert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          An wen richtet sich der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <p><img src="<?=$this->imageLink('PA_Audience.png')?>" alt="Fokus" width="25%"/>
      Die inhaltliche Ausrichtung des <i>FIDs Darstellende Kunst</i> orientiert sich an Forschung und Lehre in all ihren Ausprägungen:
      <ul>
        <li>Theaterwissenschaft: Theater, Musiktheater</li>
        <li>Tanzwissenschaft: Tanz, Bühnentanz, performance studies, Bewegungswissenschaften</li>
        <li>Kleinkunst / popular theatre and entertainment: Zirkus, Varieté, Kabarett, Comedy</li>
        <li>Paratheatrale Grenzbereiche: Performance-Kunst, Aktions-und Medienkunst.</li>
      </ul>
       Die bereitgestellten Fachinformationen orientieren sich an den Ansprüchen und Wünschen eines wissenschaftlichen Publikums.
       Damit bietet der <i>FID Darstellende Kunst</i> für Studium, Forschung und Lehre ein breites Spektrum an Fachinformationen, bündelt diese
       und stellt sie in übersichtlicher Form bereit. Das <i>FID</i>-Portal steht allerdings allen interessierten Nutzern und Wissenschaftler*Innen
       anderer Fachrichtungen offen. Allerdings erhalten diese Nutzergruppen keinen Zugriff auf die lizenzierten Produkte im Portal.</p>
</div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Welche Ressourcen sind im <i>FID</i>-Portal lizenziert und wer hat darauf Zugriff?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <p>Der Fachinformationsdienst Darstellende Kunst hat in Kooperation mit dem <a target="_blank" href="http://www.fid-lizenzen.de">Kompetenzzentrum für Lizenzierung</a> folgende Lizenzpakete erworben:
      <ul>
        <li>die e-Book Frontlist Titel 2015-2017 des <a href="http://www.transcript-verlag.de/reihen/kulturwissenschaften/theater-und-tanzwissenschaft/">transcript-Verlags</a></li>
        <li/><a target="_blank" href="http://alexanderstreet.com/products/alexander-street-drama-package">Drama-Package</a> und
        <a target="_blank" href="https://alexanderstreet.com/products/theatre-video-series">Theatre in Video</a> vom Alexander-Street-Press Verlag.</li>
      </ul>
      Die Metadaten stehen frei im <i>FID</i>-Portal http://www.performing-arts.eu/ zur Verfügung. Autorisierte bzw. registrierte Nutzer können die
      Volltexte bzw. Videos direkt im Portal ansehen. Folgender Nutzerkreis ist zur Nutzung berechtigt:
      <ul>
        <li>Wissenschaftliches Personal</li>
        <li>Fachspezifische Institutionen (Archive, Sammlungen, Museen)</li>
        <li>Mitglieder der Fachgesellschaften für Theaterwissenschaft, Theatergeschichte und Tanzforschung.</li>
      </ul>
    </p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Wie kann ich mich für die Nutzung der <i>FID</i>-Lizenzen registrieren?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <p>Die Registrierung zur Nutzung der FID-Lizenzen erfolgt über unseren Kooperationspartner
      dem <a target="_blank" href="http://www.fid-lizenzen.de">Kompetenzzentrum für Lizenzierung</a>. Auf der eigenen
      <a target="_blank" href="http://darstellende-kunst.fid-lizenzen.de">FID Darstellende Kunst Webseite</a> können Sie anmelden. Hier
      erfahren Sie auch, welche Produkte lizenziert wurden und welcher Nutzerkreis darauf Zugriff hat.<br/>
      Eine <a target="_blank" href="<?=$this->imageLink('Anleitung_zur_Anmeldung_beim_FID.pdf')?>">Anleitung</a> für die Registrierung haben wir
      für Sie erstellt. Nach der Anmeldung können Sie sich im FID-Portal <a href="http://performing-arts.eu/">http://www.performing-arts.eu/</a> als
      authetifizierter Nutzer anmelden und erhalten Zugriff auf die lizenzierten Produkte.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Kann ich Kaufvorschläge einbringen?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <p>Ja. Um das gesamte Spektrum an Fachliteratur für die darstellende Kunst abdecken zu können, benötigen wir Ihre Mithilfe!
        Sie haben einen Titel nicht im <i>FID</i>-Portal gefunden oder Sie können Ihren Wunschtitel nicht über die Fernleihe beziehen?
        Melden Sie Ihren <a href="<?=$this->url('content-page', ['page' => 'kaufvorschlag'])?>">Kaufvorschlag</a> an die <i>FID</i>-Redaktion. Wir werden Ihren Vorschlag prüfen und Ihnen eine Rückmeldung geben.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEight">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          Wie kann ich in www.performing-arts.eu recherchieren?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <p>Über den Suchschlitz auf der der Startseite des <i>FID</i>-Portals recherchieren Sie in allen verfügbaren Quellen. Die Ergebnisse sind in einem Relevanzranking sortiert.
      Sie können Ihre Suche nach bestimmten Suchkriterien eingrenzen, hierfür stehen Ihnen Facetten (Datengeber, Materialart, Sammlungen/Reihe, Datum)  zur Verfügung.
      Mit der <a href="<?=$this->url('search-advanced')?>">Erweiterten Suche</a> können Sie von Beginn an gezielt nach einem Autor, Titel und beispielsweise in einer bestimmten Sprache suchen.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingNine">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingNine" aria-expanded="false" aria-controls="collapseheadingNine">
          Was bedeuten die Suchfacetten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingNine">
      <p>Mithilfe von Facetten können Sie die Ergebnisliste Ihrer Suche nach bestimmten Kriterien eingrenzen, z. B. Datengeber, Materialart,
        Datum. Sie können mehrere Facetten kombinieren und auch wieder abwählen, um Ihre Suche zu verfeinern.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTen" aria-expanded="false" aria-controls="collapseheadingTen">
          Welche Angebote finde ich im <i>FID</i>-Portal www.performing-arts.eu?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTen">
      <p>Im <i>FID</i>-Portal wurden Datenquellen indexiert, die das gesamte Spektrum fachrelevanter Informationsversorgung abdecken:
      <ul>
        <li>fachspezifische Bibliothekskataloge wie der Fachausschnitt Theater und Tanz der Universitätsbibliothek Frankfurt/Main oder Bibliotheksbestände
          der Akademie der Künste Berlin</li>
        <li>Archivbestände der wichtigsten deutschsprachigen Sammlungen für die darstellende Kunst</li>
        <li><i>FID</i>-Lizenzen elektronischer Volltexte und e-Books für autorisierte Nutzer</li>
        <li><a target="_blank" href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/">erschlossene Inhaltsverzeichnisse</a> relevanter Zeitschriften aus dem Bereich
          Theater, Tanz und Performancekunst; hier ist eine Recherche auf Artikelebene (Überschrift und Autor) möglich</li>
        <li>Digitalisate und Volltexte aus Digitalisierungsprojekten wie dem DFG-Projekt
          <a target="_blank" href="http://digital.ub.uni-duesseldorf.de/theaterzettel">Düsseldorfer Theaterzettel</a> der Universitäts-
        und Landesbibliothek Düsseldorf</li>
     </ul>
     Das Angebot des <i>FID</i>-Portals wird sukzessive erweitert und die bereits indexierten Quellen regelmäßig aktualisiert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEleven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingEleven" aria-expanded="false" aria-controls="collapseheadingEleven">
         Was sind Metadaten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingEleven">
      <p>Metadaten sind (strukturierte) Daten, die eine Ressource, eine Entität, ein Objekt oder andere Daten beschreiben.<br/>
      Metadaten liefern also Informationen über Eigenschaften eines Dokuments, wie z.B. seinen Verfasser, den Zeitpunkt
      der Entstehung des Dokuments, das technische Format, Inhalt, Rechteinhaber usw. Diese Metadaten sind eine Sammlung von
      definierten Elementen, die dem Auffinden, der Verwendung sowie der Verwaltung einer Ressource, einer Entität etc. dienen.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwelve">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTwelve" aria-expanded="false" aria-controls="collapseheadingTwelve">
         Kann ich einen RSS-Feed zur Ergebnisliste meiner Suche einrichten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTwelve">
      <p>Ja. Am unteren Ende der Ergbnisliste gehen Sie den Link '<i class="fa fa-bell"></i> RSS-Feed abonnieren'.<br/>
      Die Suche wird Ihnen nun als Feed bereitgestellt und regelmäßig in Ihrem Feedleser aktualisiert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThirteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingThirteen" aria-expanded="false" aria-controls="collapseheadingThirteen">
          Werden mir ähnliche Treffer zu meiner Suche angezeigt?
        </a>
      </h4>
    </div>
    <div id="collapseheadingThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingThirteen">
      <p>Ja. Ihnen werden auf der Einzeltrefferebene ähnliche Einträge angezeigt. Hierfür gehen Sie zum unteren Ende des Datensatzes. Unter dem
        Reiter „Ähnliche Einträge“ werden diese aufgeführt.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFourteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFourteen" aria-expanded="false" aria-controls="collapseheadingFourteen">
          Wie kann ich mich über die aktuellen Entwicklungen des <i>FIDs Darstellende Kunst</i> informieren?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFourteen">
      <p>Abonnieren Sie den kostenlosen <a href="<?=$this->url('content-page', ['page' => 'news'])?>">Newsletter des <i>FIDs Darstellende Kunst</i></a>.
      Sie werden in regelmäßigen Abständen über Neuerungen und Wissenswertes informiert.</p>
      <p>Gemeinsam mit der Gesellschaft für Theaterwissenschaft betreut der <i>FID Darstellende Kunst</i> den Profildienst Darstellende Kunst. Fachrelevante
      Nachrichten aus der Theater- und Tanzwissenschaft werden redaktionell ausgewertet und können als <a href="<?=$this->url('news-rss')?>">RSS-Feed</a> abonniert werden.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFifteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFifteen" aria-expanded="false" aria-controls="collapseheadingFifteen">
          An wen kann ich mich bei Fragen und Anregungen wenden?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFifteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFifteen">
      <p>Sie können uns Ihre Anregungen und Wünsche unter der E-Mail-Adresse <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a> schreiben
        oder über den <a href="http://performing-arts.eu/Feedback">Feedback-Button</a>
        im Portal <a href="http://performing-arts.eu/">www.performing-arts.eu</a> nutzen.</p>

      <p>Für spezifische Fragen hilft Ihnen das <i>FID</i>-Team auch gerne persönlich weiter:</p>

      <b>Projektleitung und Koordination</b><br/>
      Franziska Voß<br/>
      Tel: 069/ 798-39574<br/>
      <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Technische Realisierung</b><br/>
      Julia Beck<br/>
      Tel: 069/ 798-39387<br/>
      <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Grafische Gestaltung</b><br/>
      Axel Dörrer<br/>
      Tel: 069/ 798-39213<br/>
      <a href="mailto:a.doerrer@ub.uni-frankfurt.de">a.doerrer@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Bibliothekarische Dienstleistung</b><br/>
      Erzsébet Trautz<br/>
      Tel: 069/ 798-39244<br/>
      <a href="mailto:e.trautz@ub.uni-frankfurt.de">e.trautz@ub.uni-frankfurt.de</a>
    </div>
  </div>
</div>
