<?php // Set page title.
$this->headTitle($this->translate('FAQ') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('FAQ')?></h2>

<div id="accordion" role="tablist" aria-multiselectable="false">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          What does <i>SIS Performing Arts</i> stand for?
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <p>The <i>Specialised Information Service (SIS) Performing Arts</i> is based at the University Library Frankfurt
        and offers people in the field of theatre and dance studies an effective and free way to access sources
        of information. The <i>SIS</i>’s main tasks are to expand the informational infrastructure and to develop and
        maintain the <i>SIS</i> web portal <a href="http://www.performing-arts.eu/">http://www.performing-arts.eu/</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Where does funding for the <i>SIS Performing Arts</i> come from?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <p>Since 2015, the project tasked with setting up the <i>Specialised Information Service (SIS) Performing Arts</i> has been funded by the
        German Research Foundation (DFG) as part of its
        <a target="_blank" href="http://www.dfg.de/en/research_funding/programmes/infrastructure/lis/funding_opportunities/informationservice_science/index.htmlSpecialised">Information Services Programme</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          For whom is the <i>SIS Performing Arts</i> intended?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <p><img src="<?=$this->imageLink('PA_Audience_en.png')?>" alt="Focus" width="25%"/></p>
      <p>The aim of the <i>SIS Performing Arts</i>  is to fulfil the needs of researchers and those involved in university teaching in a variety of related fields:
      <ul>
        <li>Theatre studies: theatre, music theatre</li>
        <li>Dance theory: dance, concert dance, performance studies, kinesiology</li>
        <li>Popular theatre and entertainment: circus, variety shows, cabaret, comedy</li>
        <li>Niche topics related to theatre: performance art, happenings and media art.</li>
      </ul>
       The specialised information provided aims to fulfil the needs and wishes of the academic usership. To this end, the <i>SIS Performing Arts</i> offers a
       wide variety of information on the field for the purposes of students, researchers and university teaching, has brought the various sources together
       and provided a user-friendly platform for their use. The <i>SIS</i> web portal is also available to interested users and academics from other disciplines;
       however, these user groups do not have access to the licenced products within the web portal.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Which resources presented by the <i>SIS</i> web portal are licenced and who has access to them?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <p>The <i>Specialised Information Service (SIS) Performing Arts</i> has purchased the following licence packages
        with the help of the <a target="_blank" href="http://www.fid-lizenzen.de">Center of Competence for Licensing</a>:
      <ul>
        <li>the e-book frontlist title series (2015-2017) from <a target="_blank" href="http://www.transcript-verlag.de/en">transcript-Verlag</a></li>
        <li/>the <a target="_blank" href="http://alexanderstreet.com/products/alexander-street-drama-package">Drama Package</a> and
        <a target="_blank" href="https://alexanderstreet.com/products/theatre-video-series">Theatre in Video</a> packages from Alexander-Street-Press Verlag.</li>
      </ul>
      The metadata are freely accessible on the <i>SIS</i> web portal: <a href="http://www.performing-arts.eu/">www.performing-arts.eu/</a>.  Authorised and/or registered users can view the texts and videos in their entirety using the web portal.
      The following users are authorised:
      <ul>
        <li>Academic personnel and staff</li>
        <li>Institutions in the field (archives, collections, museums)</li>
        <li>Members of the professional associations for theatre studies, theatre history and dance research.</li>
      </ul>
    </p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          How can I register to use the <i>SIS</i> licences?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <p>To use the <i>SIS</i> licences, please register with our project partner, the <a target="_blank" href="http://www.fid-lizenzen.de">Center of Competence for Licensing</a>.
        You can register on the <a target="_blank" href="http://darstellende-kunst.fid-lizenzen.de"><i>SIS Performing Arts</i> website</a>. Here you will find information on which products are
        licenced and which users have access to them.<br/>
        We have put together a set of <a target="_blank" href="<?=$this->imageLink('Anleitung_zur_Anmeldung_beim_FID.pdf')?>">instructions</a> for registration.
        After registering, you can sign onto the <i>SIS</i> web portal <a href="http://performing-arts.eu/">http://www.performing-arts.eu/</a> as an authorised
        user and will have access to the licenced products.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Can I make suggestions for new acquisitions?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <p>Yes.  To do justice to the entire range of literature in the field of performing arts, we need your help! If you have been unable to find a
        title you need using the <i>SIS</i> web portal, or if you are unable to receive it using the interlibrary loan programme, please send your
        <a href="<?=$this->url('content-page', ['page' => 'kaufvorschlag'])?>">suggestion for a new acquisition</a> to the <i>SIS</i> editorial team. We will
        evaluate your suggestion and send you a response.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEight">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          How can I use the www.performing-arts.eu site for research?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <p>Using the search function on the main page of the <i>SIS</i> web portal, you can search the contents of all available sources. The results are sorted
        according to relevance. You can limit your search according to specific criteria using the various search options provided (data provider, type of
        material, collection/series, date). An <a href="<?=$this->url('search-advanced')?>">Advanced Search</a> allows you to tailor your search from
        the beginning, e.g. to look for a certain author or title in a specific language.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingNine">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingNine" aria-expanded="false" aria-controls="collapseheadingNine">
          What does faceted search mean?
        </a>
      </h4>
    </div>
    <div id="collapseheadingNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingNine">
      <p>Using the faceted search, you can limit the list of search results according to specific criteria, e.g. data provider, type of material,
        and date. You can combine several options and de-select them to further tailor your search.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTen" aria-expanded="false" aria-controls="collapseheadingTen">
          What is available on the <i>SIS</i> web portal www.performing-arts.eu?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTen">
      <p>The <i>SIS</i> portal has been used to index data sources which address the entire range of information relevant to the field:
        <ul>
          <li>Specialised library catalogues such as the University Frankfurt Library`s theatre and dance section or the Academy of the Arts Berlin Library’s collection</li>
          <li>The most significant archived books and other items housed by collections in the German-speaking world in the field of performing arts</li>
          <li>Licences obtained by the <i>SIS</i> to full texts and e-books, with access for authorised users</li>
          <li><a target="_blank" href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/">Catalogued tables of contents</a> of relevant periodicals in the field of
            theatre, dance and performance art, with the opportunity to search for specific articles (title and author)</li>
          <li>Digitalised materials and full texts from digitalisation projects such as the German Research Foundation-funded
            <a target="_blank" href="http://digital.ub.uni-duesseldorf.de/theaterzettel?lang=en">Theatre Playbills Project</a> by the Düsseldorf University
            and State Library</li>
        </ul>
        The sources available on the <i>SIS</i> web portal are being continually added to, and the sources already indexed are regularly updated.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEleven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingEleven" aria-expanded="false" aria-controls="collapseheadingEleven">
         What are metadata?
        </a>
      </h4>
    </div>
    <div id="collapseheadingEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingEleven">
      <p>Metadata are (structural) data which describe a resource, an entity, an object or other types of data.<br/>
        This means that metadata provide information about the features of a document, e.g. its author, the time of its creation,
        its technical format, its content, and who owns the rights to it. These metadata are a collection of defined elements
        which can be used to locate, use, and administer a resource, an entity, etc.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwelve">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTwelve" aria-expanded="false" aria-controls="collapseheadingTwelve">
         Can I set up an RSS feed for the results of my search?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTwelve">
      <p>Yes. At the bottom of the list of results, you will find the following link: '<i class="fa fa-bell"></i> Get RSS Feed'.<br/>
         The search will now be displayed in the form of a feed and regularly updated in your RSS reader.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThirteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingThirteen" aria-expanded="false" aria-controls="collapseheadingThirteen">
          Will my list of results show almost-matches?
        </a>
      </h4>
    </div>
    <div id="collapseheadingThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingThirteen">
      <p>Yes, the list of individual results will include items similar to your search query.
        To find them, go to the bottom of the data set; the almost-matches will be listed there under “Similar Items”.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFourteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFourteen" aria-expanded="false" aria-controls="collapseheadingFourteen">
          How can I obtain information about current developments at the <i>SIS Performing Arts</i>?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFourteen">
      <p>You can subscribe to the free <a href="<?=$this->url('content-page', ['page' => 'news'])?>"><i>SIS Performing Arts</i> newsletter</a>.
        You will receive information on new developments and on topics of interest at regular intervals. </p>
      <p>The <i>SIS Performing Arts</i> has teamed up with the Society for Theatre Studies to operate the Performing Arts News Service, which evaluates and edits news from the
        world of theatre and dance studies. The sources thus provided can be subscribed to via an <a href="<?=$this->url('news-rss')?>">RSS feed</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFifteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFifteen" aria-expanded="false" aria-controls="collapseheadingFifteen">
          To whom should I send questions and suggestions?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFifteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFifteen">
      <p>You can send your suggestions and requests to <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>, or click
        on the <a href="http://performing-arts.eu/Feedback">Feedback button</a> in the <a href="http://performing-arts.eu/">www.performing-arts.eu</a> portal.</p>

      <p>The <i>SIS</i> team would be glad to help you in person if you have specific questions:</p>

      <b>Project Leader and Coordinator</b><br/>
      Franziska Voß<br/>
      Tel: +49 69/ 798-39574<br/>
      <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Technical Implementation</b><br/>
      Julia Beck<br/>
      Tel: +49 69/ 798-39387<br/>
      <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Graphic Design</b><br/>
      Axel Dörrer<br/>
      Tel: +49 69/ 798-39213<br/>
      <a href="mailto:a.doerrer@ub.uni-frankfurt.de">a.doerrer@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Library Services</b><br/>
      Erzsébet Trautz<br/>
      Tel: +49 69/798-39244<br/>
      <a href="mailto:e.trautz@ub.uni-frankfurt.de">e.trautz@ub.uni-frankfurt.de</a>
    </div>
  </div>
</div>
