<?php // Set page title.
$this->headTitle($this->translate('Interlibrary Loan') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Interlibrary Loan')?></h2>

<div class="card">
<p>Die UB Frankfurt nimmt am <a target="_blank" href="https://www.ub.uni-frankfurt.de/benutzung/fernleihe.html">Fernleihverkehr</a> teil. Die Fernleihe (Auswärtiger Leihverkehr)
ist ein Service, mit dem Medien (Bücher, Zeitschriftenartikel u.a.), die am Ort nicht vorhanden
sind, von auswärtigen Bibliotheken beschafft werden können. Die UB Frankfurt ist dabei an die
<a target="_blank" href="http://www.bibliotheksverband.de/fileadmin/user_upload/DBV/vereinbarungen/Leihverkehrsordnung.pdf">Leihverkehrsordnung des Leihverkehrs in Deutschland</a> (LVO) und an Vereinbarungen über den
Internationalen Leihverkehr gebunden.</p>
<p>Benötigen Sie Ihre Bestellung zeitnah? Dann nutzen Sie den kostenpflichtigen Dokumentlieferdienst
<a target="_blank" href="http://www.subito-doc.de/">Subito</a> für Ihre Bestellungen</p>
</div>
