<?php // Set page title.
$this->headTitle($this->translate('Liability Information') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Liability Information')?></h2>

<div class="card">
<p>
Die UB Frankfurt ist als Inhaltsanbieter für die "eigenen Inhalte", die sie zur Nutzung
bereithält, nach den allgemeinen Gesetzen verantwortlich. Die UB Frankfurt ist um Richtigkeit
und Aktualität der auf den Seiten von <a href="http://www.performing-arts.eu">www.performing-arts.eu</a> bereitgestellten Informationen bemüht.
Fehler und Unklarheiten können aber nicht vollständig ausgeschlossen werden, so dass keine Gewähr
für die Aktualität, Richtigkeit, Vollständigkeit, Qualität und jederzeitige Verfügbarkeit der
Inhalte übernommen werden kann. Für Schäden materieller oder immaterieller Art, die durch die
Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und
unvollständiger Informationen unmittelbar oder mittelbar verursacht werden, haften die UB Frankfurt
nicht, sofern ihr nicht nachweislich vorsätzliches oder grob fahrlässiges Verschulden zur Last fällt.
Dies gilt auch für etwaige Schäden, die beim Aufrufen oder Herunterladen von Daten durch
Computerviren oder bei der Installation von Software verursacht werden. Die Nutzung der auf dem
Portal <a href="http://www.performing-arts.eu">www.performing-arts.eu</a> zur Verfügung gestellten Inhalte
erfolgt auf alleinige Gefahr des Benutzers/der Benutzerin.</p>

<p>Die UB Frankfurt behält es sich ausdrücklich vor, Teile des Internetangebotes oder das gesamte
Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung
zeitweise oder endgültig einzustellen.
</p>
</div>

<h4>Rechtswirksamkeit dieses Haftungsausschlusses</h4>
<div class="card">
<p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite
  verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht,
  nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.
</p>
<a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>
</div>
