<?php // Set page title.
$this->headTitle($this->translate('Website Information') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Website Information')?></h2>
The <i>Specialised Information Service Performing Arts</i> and the web portal are run by:<br><br>

<div class="card">
<a target="_blank" href="http://www.ub.uni-frankfurt.de/home_en.html"><b>University Library Johann Christian Senckenberg</b></a><br/>
represented by the Director of the University Library Johann Christian Senckenberg <b>Dr. Heiner Schnelling</b>
<br/><br/>
University Library Frankfurt am Main<br/>
Bockenheimer Landstr. 134-138<br/>
60325 Frankfurt am Main<br/>
Tel.: +49 69/ 798-39205<br/>
<a href="mailto:Direktion@ub.uni-frankfurt.de">Direktion@ub.uni-frankfurt.de</a>
</div>
