<?php // Set page title.
$this->headTitle($this->translate('Website Information') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Website Information')?></h2>
Der <i>Fachinformationsdienst Darstellende Kunst</i> und das Portal ist ein Angebot der:<br><br>

<div class="card">
<a target="_blank" href="http://www.ub.uni-frankfurt.de"><b>Universitätsbibliothek Johann Christian Senckenberg in Frankfurt am Main</b></a><br/>
vertreten durch die Direktorin der Universitätsbibliothek Johann Christian Senckenberg <b>Daniela Poth</b>
<br/><br/>
Universitätsbibliothek Frankfurt a.M.<br/>
Bockenheimer Landstr. 134-138<br/>
60325 Frankfurt am Main<br/>
Tel.: 069/ 798-39205<br/>
<a href="mailto:Direktion@ub.uni-frankfurt.de">Direktion@ub.uni-frankfurt.de</a>
</div>
