<?php // Set page title.
$this->headTitle($this->translate('Imprint') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Imprint')?></h2>
The <i>Specialised Information Service Performing Arts</i> and the web portal are run by:<br><br>

<div class="card">
<a target="_blank" href="http://www.ub.uni-frankfurt.de/home_en.html"><b>University Library Johann Christian Senckenberg</b></a><br/>
<a target="_blank" href="https://www.uni-frankfurt.de/impressum">Imprint: Universität Frankfurt am Main</a>
</div>
