<?php // Set page title.
$this->headTitle($this->translate('Imprint') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Imprint')?></h2>
Der <i>Fachinformationsdienst Darstellende Kunst</i> und das Portal ist ein Angebot der:<br><br>

<div class="card">
<a target="_blank" href="http://www.ub.uni-frankfurt.de"><b>Universitätsbibliothek Johann Christian Senckenberg in Frankfurt am Main</b></a><br/>
<a target="_blank" href="https://www.uni-frankfurt.de/impressum">Impressum: Universität Frankfurt am Main</a>
</div>
