<?php // Set page title.
$this->headTitle($this->translate('Suggestion Buy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Suggestion Buy')?></h2>

<p>Um das gesamte Spektrum an Fachliteratur für die Darstellende
Kunst abdecken zu können, benötigen wir Ihre Mithilfe! Sie haben
einen Titel nicht im FID-Portal gefunden oder Sie können Ihren
Wunschtitel nicht über die Fernleihe beziehen? Melden Sie Ihren
Kaufvorschlag an die FID-Redaktion. Wir werden Ihren Vorschlag
prüfen und Ihnen eine Rückmeldung geben.
</p><br>

<div class="card">
<?=$this->flashmessages() ?>
<?=$this->render('content/kaufvorschlag_form.phtml') ?>
<br><br>
<p>Bitte beachten Sie, dass die Kaufvorschläge dem <a href="<?=$this->url('content-page', ['page' => 'neuerwerb'])?>">Erwerbungsprofil</a>
des Fachinformationsdienstes entsprechen müssen.<br>
Mit einem * gekennzeichnete Felder sind Pflichtfelder, die Sie ausfüllen müssen, damit Ihr Vorschlag
bearbeitet werden kann.
</p>
</div>
