<form accept-charset="UTF-8"  method="POST" action="kaufvorschlag">
<p><b><?=$this->transEsc("Suggestion Buy") . ":";?></b></p>
<table style="border-collapse: separate; border-spacing: 10px;">
<tr>
<td width="250px">
ISBN/ISSN:
</td>
<td>
<input type="text" name="isxn" size="13" maxlength="20" value="<?if(isset($this->isxn)) echo $this->isxn;?>">
</td>
</tr>

<tr>
<td>
<b>*</b><?=$this->transEsc("Author");?>:
</td>
<td>
<input type="text" name="author" size="50" maxlength="100" value="<?if(isset($this->author)) echo $this->author;?>">
</td>
</tr>

<tr>
<td>
<b>*</b><?=$this->transEsc("Title");?>:
</td>
<td>
<textarea name="title" rows="1" cols="47" wrap="" maxlength="300">
<?if(isset($this->title))echo $this->title;?></textarea>
</td>
</tr>

<tr>
<td>
<b>*</b><?=$this->transEsc("Publisher");?>:
</td>
<td>
<input type="text" name="publisher" size="30" maxlength="100" value="<?if(isset($this->publisher))echo $this->publisher;?>">
</td>
</tr>

<tr>
<td>
<?=$this->transEsc("Publication_Place");?>:
</td>
<td>
<input type="text" name="placeOfPublication" size="30" maxlength="100" value="<?if(isset($this->placeOfPublication))echo $this->placeOfPublication;?>">
</td>
</tr>

<tr>
<td>
<?=$this->transEsc("adv_search_year");?>:
</td>
<td>
<input type="text" name="dateOfPublication" size="4" maxlength="4" value="<?if(isset($this->dateOfPublication))echo $this->dateOfPublication;?>">
</td>
</tr>

<tr>
<td>
<?=$this->transEsc("Add a Note");?>:
</td>
<td>
<textarea name="remarks" rows="2" cols="50" wrap="" maxlength="1000">
<?if(isset($this->remarks))echo $this->remarks;?></textarea>
</td>
</tr>

</table>

<hr size="1">

<p><b><?=$this->transEsc("Contact");?>:</b></p>

<table style="border-collapse: separate;border-spacing: 10px;">
<tr>
<td width="250px">
<b>*</b><?=$this->transEsc("Name");?>:
</td>
<td>
<input type="text" name="name" size="50" value="<?if(isset($this->name))echo $this->name;?>" maxlength="100">
</td>
</tr>

<tr>
<td>
<b>*</b>E-Mail:
</td>
<td>
<input id="email" name="email" size="30" value="<?if(isset($this->email))echo $this->email;?>" maxlength="100"/>
</td>
</tr>

<tr>
<td>
Institution:
</td>
<td>
<input id="institution" name="institution" size="50" value="<?if(isset($this->institution))echo $this->institution;?>" maxlength="100"/>
</td>
</tr>

<tr>
<td>
</td>
<td>
<input align="left" type="submit" name="submit" value="<?=$this->transEsc('Send')?>">
<input align="right" type="reset" name="reset" value="<?=$this->transEsc('Clear')?>">
</td>
</tr>

</table>

</form>
