<?php // Set page title.
$this->headTitle($this->translate('Contact') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('Contact')?></h2>

<div id="contacts">
<div class="left card">
<h4>Project Leader and Coordinator</h4>
Franziska Voß<br>
Tel: +49 69/ 798-39574<br>
<a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
<br><br>

<h4>Technical Implementation</h4>
Julia Beck<br>
Tel: +49 69/ 798-39387<br>
<a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
<br><br>

<h4>Graphic Design</h4>
Axel Dörrer<br><br>

<h4>Library Services</h4>
TBA
</div>

<div class="right card">
<h4>Additional Contact Person</h4>
Dr. Ann-Barbara Kersting-Meuleman<br>
Head of the Music and Theatre Department<br>
Tel: +49 69/ 798-39245<br>
<a href="mailto:a.b.kersting-meuleman@ub.uni-frankfurt.de">a.b.kersting-meuleman@ub.uni-frankfurt.de</a>
<br><br>

Department of Music, Theatre<br>
Tel.: +49 69/798-39 244<br>
<a href="mailto:slg-musik-theater@ub.uni-frankfurt.de">slg-musik-theater@ub.uni-frankfurt.de</a>
<br><br>

General enquiries may be sent to the editorial team:<br>
<a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>
</div>
