<?php // Set page title.
$this->headTitle($this->translate('Contact') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('Contact')?></h2>

<div id="contacts">
<div class="left card">
<h4>Projektleitung und Koordination</h4>
Franziska Voß<br>
Tel: 069/ 798-39574<br>
<a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
<br><br>

<h4>Technische Realisierung</h4>
Julia Beck<br>
Tel: 069/ 798-39387<br>
<a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
<br><br>

<h4>Grafische Gestaltung</h4>
Axel Dörrer<br><br>

<h4>Bibliothekarische Dienstleistung</h4>
Doris Becker<br>
Tel: 069/ 798-39258<br>
<a href="mailto:d.becker@ub.uni-frankfurt.de">d.becker@ub.uni-frankfurt.de</a>
</div>

<div class="right card">
<h4>Weitere Ansprechpartner</h4>
Dr. Ann-Barbara Kersting-Meuleman<br>
Abteilungsleitung Musik, Theater<br>
Tel: 069/ 798-39245<br>
<a href="mailto:a.b.kersting-meuleman@ub.uni-frankfurt.de">a.b.kersting-meuleman@ub.uni-frankfurt.de</a>
<br><br>

Abteilung Musik, Theater<br>
Tel.: 069/798-39 244<br>
<a href="mailto:slg-musik-theater@ub.uni-frankfurt.de">slg-musik-theater@ub.uni-frankfurt.de</a>
<br><br>

Allgemeine Anfragen können Sie auch an die Redaktion senden:<br>
<a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>
</div>
</div>
