<?php // Set page title.
$this->headTitle($this->translate('Contact') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('Contact')?></h2>

<div class="flexing left">
<div class="card itemleft">
<h4>Projektleitung und Koordination</h4>
<p>Franziska Voß<br>
Tel: 069/ 798-39574<br>
<a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a></p>

<h4>Technische Realisierung</h4>
<p>Julia Beck<br>
Tel: 069/ 798-39387<br>
<a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a></p>

<h4>Grafische Gestaltung</h4>
<p>Axel Dörrer</p>

<h4>Bibliothekarische Dienstleistung</h4>
N.N.
</div>

<div class="card itemleft">
<h4>Weitere Ansprechpartner</h4>
<p>Dr. Ann-Barbara Kersting-Meuleman<br>
Abteilungsleitung Musik, Theater<br>
Tel: 069/ 798-39245<br>
<a href="mailto:a.b.kersting-meuleman@ub.uni-frankfurt.de">a.b.kersting-meuleman@ub.uni-frankfurt.de</a></p>

<p>Abteilung Musik, Theater<br>
Tel.: 069/798-39 244<br>
<a href="mailto:slg-musik-theater@ub.uni-frankfurt.de">slg-musik-theater@ub.uni-frankfurt.de</a></p>

<br>
<hr>
<p>Allgemeine Anfragen können Sie auch an die Redaktion senden:<br>
<a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a></p>
</div>
</div>
