<?php $link=htmlentities($_GET['link']);?>
<div class="card">
  <div class="flex-content flex-between">
    <div><a href="https://darstellende-kunst.fid-lizenzen.de/kfllogin" target="_blank"><?=$this->transEsc('NotRegistered');?></a></div>
    <div><a href="<?=$link?>" target="_blank"><?=$this->transEsc('NoContent');?></a></div>
    <div><a href="https://darstellende-kunst.fid-lizenzen.de/mail_password_form" target="_blank"><?=$this->transEsc('ForgotPassword');?></a></div>
    <div><a href="https://darstellende-kunst.fid-lizenzen.de/kfl-mail-account" target="_blank"><?=$this->transEsc('ForgotUsername');?></a></div>
    <div><a href="<?=$link?>" target="_blank"><?=$this->transEsc('FullScreen');?></a></div>
  </div>
</div>
<iframe id="fid-license-frame" src="<?=$link?>"></iframe>
