<?php // Set page title.
$this->headTitle($this->transEsc('MediaLibraries') . ' - ' . $this->translate('FID Darstellende Kunst'));?>

<h2>Digitally connecting Media Libraries of the Performing Art</h2>

<p>A project of the University Library Johann Christian Senckenberg / Specialised
  Information Service Performing Arts and the German Centre of the International
  Theatre Institute / Media Library for Dance and Theatre in cooperation with the
  Video and Audio Collection of the Department of Theatre, Film and Media Studies
  at the University of Vienna.</p>

<div class="flexing center">
  <figure>
    <a href="https://www.performing-arts.eu">
        <img src="<?=$this->imageLink('fid-dk_claim_s.png')?>" alt="Fachinformationsdienst Darstellende Kunst"/>
    </a>
  </figure>
  <figure>
    <a href="https://archiv.mimecentrum.de/">
        <img src="<?=$this->imageLink('logos_m/mtt.png')?>" alt="Internationales Theaterinstitut Deutschland (ITI), Berlin // Mediathek für Tanz und Theater (MTT)"/>
    </a>
  </figure>
  <figure>
    <a href="https://tfm.univie.ac.at/">
        <img src="<?=$this->imageLink('logos_m/tfm.png')?>" alt="Department of Theatre, Film and Media Studies at the University of Vienna"/>
    </a>
  </figure>
</div>
<br>

<div class="card">
<p>The aim of the project <b>„Digitally Connecting Media Libraries of the Performing Arts"</b>
   is to aggregate metadata on audiovisual collections of the performing arts that are distributed
   among theatre and dance studies institutes at universities, art academies or media archives
   in Germany and German speaking countries. The implementation of a central access point to
   these data via the SIS portal <a href="https://www.performing-arts.eu">www.performing-arts.eu</a>
   will enable the research of information on audiovisual media as well as the performances
   and events of the performing arts that are represented in them.</p>

<p>The following are focal points of the project:</p>

<ul>
  <li>Developing workflows for aggregation, modelling, enrichment, implementation
    and publication of media library metadata of the performing arts</li>
  <li>Establishing a central access for media library metadata via the SIS portal
    <a href="https://www.performing-arts.eu">www.performing-arts.eu</a></li>
  <li>Sustainable publication and distribution of media library metadata for use
    in and beyond the project</li>
  <li>Establishing a communication structure with the professional community</li>
  <li>Developing consulting services for media libraries and media collections of
    the performing arts as well as the evaluation of project results.</li>
  </ul>

<p>The digital accessibility and curation of metadata is a central concern of the
  project. In addition to the metadata of the project partners - ITI Germany and
  TFM Vienna - further metadata from data partners are to be integrated in order
  to publish the largest possible amount of freely accessible media library metadata.</p>

<p>The technical developments and best practices developed as well as the evaluation
  results will be permanently and freely available for subsequent use or research
  to theatre and dance studies institutes, non-university research institutions,
  collections and archives. Application scenarios of the project results will be
  developed as part of the openly accessible project documentation. All technical
  implementations will be published as open-source source code.</p>
</div>

<h3>Contact Person</h3>
<div class="flexing">
<div class="card item">
  <h3><b>Specialised Information Service (SIS) Performing Arts</b></h3>
  <h4>Project Leader and Coordinator</h4>
  <p>Sara Tiefenbacher<br>
  <a href="mailto:s.tiefenbacher@ub.uni-frankfurt.de">s.tiefenbacher@ub.uni-frankfurt.de</a></p>
  <p>Franziska Voß<br>
  <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a></p>

  <h4>Technical Implementation</h4>
  <p>Julia Beck<br>
  <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a></p>
</div>

<div class="card item">
  <h3><b>German Centre of the International Theatre Institute (ITI) // Media library for dance and theatre</b></h3>
  <h4>Project Leader and Coordinator</h4>
  <p>Christine Henniger<br>
  <a href="mailto:c.henniger@iti-germany.de">c.henniger@iti-germany.de</a></p>

  <h4>Technical Implementation</h4>
  <p>Maxim Wittenbecher<br>
  <a href="mailto:m.wittenbecher@iti-germany.de">m.wittenbecher@iti-germany.de</a></p>
  <br>
  <hr>
  <p>General enquiries may be sent to the editorial team:<br>
  <a href="mailto:mediathek@performing-arts.eu">mediathek@performing-arts.eu</a></p>
</div>
</div>
