<?php // Set page title.
$this->headTitle($this->transEsc('MediaLibraries') . ' - ' . $this->translate('FID Darstellende Kunst'));?>

<h2>Mediatheken der Darstellenden Kunst digital vernetzen</h2>

<p>Ein Projekt der Universitätsbibliothek Johann Christian Senckenberg Frankfurt am Main /
  Fachinformationsdienst Darstellende Kunst und des Internationalen Theaterinstituts
  Deutschland Berlin / Mediathek für Tanz und Theater in Zusammenarbeit mit der
  Wissenschaftlichen Videothek und Audiothek des Instituts für Theater-, Film- und
  Medienwissenschaft der Universität Wien.</p>

<div class="flexing center">
  <figure>
    <a href="https://www.performing-arts.eu">
        <img src="<?=$this->imageLink('fid-dk_claim_s.png')?>" alt="Fachinformationsdienst Darstellende Kunst"/>
    </a>
  </figure>
  <figure>
    <a href="https://archiv.mimecentrum.de/">
        <img src="<?=$this->imageLink('logos_m/mtt.png')?>" alt="Internationales Theaterinstitut Deutschland (ITI), Berlin // Mediathek für Tanz und Theater (MTT)"/>
    </a>
  </figure>
  <figure>
    <a href="https://tfm.univie.ac.at/">
        <img src="<?=$this->imageLink('logos_m/tfm.png')?>" alt="Institut für Theater-, Film- und Medienwissenschaft der Universität Wien"/>
    </a>
  </figure>
</div>
<br>

<div class="card">
<p>Ziel des DFG-Projektes <b>„Mediatheken der Darstellenden Kunst digital vernetzen“</b> ist
  die digitale Zusammenführung von Metadaten zu audiovisuellen Beständen der Darstellenden
  Kunst, die verteilt bei theater- und tanzwissenschaflichen Instituten an Universitäten,
  Kunsthochschulen oder Medienarchiven in Deutschland vorliegen. Durch den Aufbau eines
  zentralen Recherchezugangs über das FID-Portal
  <a href="https://www.performing-arts.eu">www.performing-arts.eu</a> wird es möglich,
  Informationen zu audiovisuellen Medien und den in ihnen repräsentierten Aufführungen,
  Performances und Ereignissen der Darstellenden Kunst zu recherchieren.</p>

<p>Folgende Schwerpunkte werden die Projektarbeit bestimmen:</p>

<ul>
  <li>Erarbeitung von Arbeitsprozessen für die Aggregation, Modellierung, Anreicherung,
    Implementierung und Veröffentlichung von Mediatheksmetadaten der Darstellenden Kunst</li>
  <li>Aufbau eines zentralen Zugangs für Mediatheksmetadaten über das FID-Portal
    <a href="https://www.performing-arts.eu">www.performing-arts.eu</a></li>
  <li>Nachhaltige Bereitstellung und Nachnutzbarkeit der Mediatheksmetadaten</li>
  <li>Etablierung einer Kommunikationsstruktur mit der Fachcommunity</li>
  <li>Entwicklung von Beratungsangeboten für Mediatheken und Mediensammlungen der
    Darstellenden Kunst sowie die Evaluation der Projektergebnisse.</li>
  </ul>

<p>Die digitale Zugänglichmachung und Kuratierung von Mediatheksmetadaten ist ein
  zentrales Anliegen des Mediatheken-Projekts. Neben den Mediatheksmetadaten der
  Projektpartner*innen - ITI Deutschland und TFM Wien - sollen weitere Metadaten von
  Datenpartner*innen eingebunden bzw. zusammengeführt werden, um einen größtmöglichen
  Umfang an frei zugänglichen Mediatheksmetadaten zu veröffentlichen.</p>

<p>Sowohl die technischen Entwicklungen, die erarbeiteten Serviceangebote als auch die
  Evaluationsergebnisse stehen den theater- und tanzwissenschaftlichen Instituten,
  außeruniversitären Forschungseinrichtungen, Sammlungen und Facharchiven zur Nachnutzung
  bzw. Recherche dauerhaft und frei zur Verfügung. Anwendungsszenarien der Projektergebnisse
  werden im Rahmen der frei zugänglichen Projektdokumentation publiziert. Alle technischen
  Entwicklungen werden als open-source Quellcodes veröffentlicht.</p>
</div>

<h3>Ansprechpartner*innen</h3>
<div class="flexing">
<div class="card item">
  <h3><b>Fachinformationsdienst Darstellende Kunst</b></h3>
  <h4>Projektleitung und Koordination</h4>
  <p>Sara Tiefenbacher<br>
  <a href="mailto:s.tiefenbacher@ub.uni-frankfurt.de">s.tiefenbacher@ub.uni-frankfurt.de</a></p>
  <p>Franziska Voß<br>
  <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a></p>

  <h4>Technische Realisierung</h4>
  <p>Julia Beck<br>
  <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a></p>
</div>

<div class="card item">
  <h3><b>Internationales Theaterinstitut Deutschland (ITI), Berlin // Mediathek für Tanz und Theater (MTT)</b></h3>
  <h4>Projektleitung und Koordination</h4>
  <p>Christine Henniger<br>
  <a href="mailto:c.henniger@iti-germany.de">c.henniger@iti-germany.de</a></p>

  <h4>Technische Realisierung</h4>
  <p>Maxim Wittenbecher<br>
  <a href="mailto:m.wittenbecher@iti-germany.de">m.wittenbecher@iti-germany.de</a></p>
  <br>
  <hr>
  <p>Allgemeine Anfragen können Sie auch an die Redaktion senden:<br>
  <a href="mailto:mediathek@performing-arts.eu">mediathek@performing-arts.eu</a></p>
</div>
</div>
