<? // Set page title.
$this->headTitle($this->translate('Networks') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Networks')?></h2>

<?
if ($this->plugin('translate')
    ->getTranslator()
    ->getLocale() == 'de')
    {
    ?>

<a href="<?=$this->url('content-page', ['page' => 'netzwerke'])?>">Fachgesellschaften und Arbeitskreise</a><br>
<b>Gedächtnisinstitutionen der Darstellenden Künste</b><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke3'])?>">Verbünde, Arbeitskreise etc.</a>
<br><br>

<p>In kurzen Portraits werden Ihnen Bibliotheken, Archive und Sammlungen
	der darstellenden Kunst mit ihren Sammelschwerpunkten vorgestellt.</p>

<h4>
	<a target="_blank" href="http://www.adk.de/de/archiv/archivbestand/darstellende-kunst/">Akademie
		der Künste Berlin, Archiv Darstellende Kunst</a>
</h4>
<p>
	Das Archiv sammelt, bewahrt, erschließt Bestände von Regisseuren,
	Intendanten im Bereich Sprech- und Musiktheater, von Schauspielern,
	Tänzern und Choreographen, Bühnenbildnern, Kritikern,
	Theaterwissenschaftlern, Dramatikern, Dramaturgen, Kabarettisten und
	Komponisten vorrangig für den Bereich Kabarett. Mit Hilfe der Methode
	der Inszenierungsdokumentation werden im Bereich Theaterdokumentation
	Arbeitsprozesse und -ergebnisse aktueller Inszenierungen führender
	Regisseure des Sprech- und Musiktheaters festgehalten. <br>
	Die Anfänge
	des Archivs Darstellende Kunst gehen in die Jahre 1951/52 zurück. 1960
	wurden die ersten Nach- und Vorlässe übernommen. Der zeitliche Umfang
	der Bestände erstreckt sich vom 19. Jahrhundert bis in die unmittelbare
	Gegenwart. Das Archiv betreut 270 Personenbestände und 19 thematische
	Sammlungen, darunter etwa 1.300 Inszenierungsdokumentationen, das sind
	mehr als 1.800 laufende Meter (lfm.) Archivgut, über 25.000 Blatt
	großformatige Blätter und mehr als 35.000 Fotos.</p>
<p>Sammlungsschwerpunkte:
<ul>
	<li>Mitglieder der Akademie der Künste</li>
	<li>Theater in Berlin</li>
	<li>Theater im Exil</li>
	<li>Theater der DDR</li>
	<li>Theater der BRD</li>
	<li>Aktuelles Theater</li>
	<li>Ausdruckstanz</li>
	<li>Kabarett</li>
	<li>Kritik und Theaterwissenschaft</li>
	<li>Archive von Theatern und Verbänden</li>
	<li>Inszenierungsdokumentationen des Sprech- und Musiktheaters</li>
	<li>Dokumentation Theater in der Wende</li>
</ul>
</p>

Webseite: <a target="_blank" href="http://www.adk.de/de/archiv/archivbestand/darstellende-kunst/">www.adk.de/de/archiv/archivbestand/darstellende-kunst</a><br>
E-Mail: <a href="mailto:archivdarstellendekunst@adk.de">archivdarstellendekunst@adk.de</a><br>
<br>
<br>

<h4>
	<a target="_blank" href="http://www.adk.de/de/archiv/bibliothek">Akademie der Künste
		Berlin, Bibliothek</a>
</h4>
<p>
	Die Bibliothek verfügt über einen Bestand von mehr als 600.000 Bänden
	und umfasst alle Sparten der Künste. Der Sammelschwerpunkt liegt auf
	Werken der Mitglieder und Preisträger der Akademie, ergänzt werden die
	Bestände um zahlreiche Sondersammlungen, besonders herausragend z.B.
	zum Expressionismus und zur Exilliteratur zwischen 1933 und 1945.<br>
	Darüber hinaus besitzt die Bibliothek umfangreiche Sammlungen von
	Bühnenmanuskripten, nationalen und internationalen
	Ausstellungskatalogen, seltenen Zeitschriften sowie Bibliotheken von
	Institutionen und Künstlervereinigungen.<br>
	 Ihren einzigartigen Charakter
	begründen über 300 Nachlassbibliotheken bedeutender Schriftsteller,
	Architekten und Künstler sowie bibliophiler Sammler und Repräsentanten
	der Kulturpolitik in der DDR und in der BRD.<br>
	Für das Portal des <i>Fachinformationsdienstes Darstellende Kunst</i> wurden
  fachspezifische	Nachlass- und Sammlungsbibliotheken ausgewählt, darunter z.B.
  Bertolt	Brecht, Bernhard Minetti, Herbert Ihering und Christoph Schlingensief.
</p>

Webseite: <a target="_blank" href="http://www.adk.de/de/archiv/bibliothek">www.adk.de/de/archiv/bibliothek</a><br>
E-Mail: <a href="mailto:Bibliothek@adk.de">Bibliothek@adk.de</a><br>
<br>
<br>

<h4>
	<a target="_blank" href="http://www.mimecentrum.de">Internationales Theaterinstitut Deutschland, Mime Centrum Berlin, Mediathek für Tanz und Theater</a>
</h4>
<p>Das Mime Centrum Berlin ist ein öffentlicher Ort der Dokumentation,
	Information, der Forschung und praktischen Arbeit im Bereich Tanz und
	Theater.<br>
	Mit seinem Videostudio, einem großen Proben- und
	Workshop-Studio sowie einer umfangreichen Mediathek verbindet das Mime
	Centrum in seiner Arbeitsstruktur Möglichkeiten der praktischen und
	theoretischen Auseinandersetzung zu Fragen der Körperarbeit und zu
	Bewegungsmethoden in den Darstellenden Künsten.<br>
	Die Mediathek für Tanz
	und Theater mit mehr als 8000 Videodatenträgern, Buch- und
	Zeitschriftenbeständen gibt Einblick in nationale und internationale
	Entwicklungen der Darstellenden Kunst. Der Bestand der Mediathek wird
	kontinuierlich erweitert durch eigene Dokumentationen, die Übernahme
	von Sammlungen und Leihgaben von Künstlern, Festivals und Theatern.<br>
	Das
	Mime Centrum Berlin dient dem Austausch von Künstlern, Forschern,
	Journalisten und allen weiteren Interessenten. In öffentlichen Formaten
	wie Filmveranstaltungen, Lectures und Diskussionen bietet es die
	Möglichkeit zur Befragung und Kommunikation von aktuellen und
	historischen Ereignissen in Tanz und Theater.
</p>

Webseite: <a target="_blank" href="http://www.mimecentrum.de">www.mimecentrum.de</a><br>
E-Mail: <a href="mailto:mediathek@mimecentrum.de">mediathek@mimecentrum.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/index.html">Freie Universität Berlin, Institut für Theaterwissenschaft,
	Theaterhistorische Sammlungen</a></h4>
<p>
 Das Institut für Theaterwissenschaft der Freien
	Universität bietet die Studiengänge Theaterwissenschaft (BA und MA),
	Tanzwissenschaft (MA), Filmwissenschaft (BA und MA), Musikwissenschaft
	an. Das Studium ist vorwiegend theoretisch und historisch-kritisch
	ausgerichtet, das Institut ist dabei in ein internationales und
	interdisziplinäres Forschungsumfeld eingebunden und pflegt umfangreiche
	Kontakte zu anderen fachverbundenen wissenschaftlichen und praktischen
	Einrichtungen.<br>
	 In den Theaterhistorischen Sammlungen des Instituts
	stehen dazu umfangreiche Archivbestände insbesondere zur Berliner
	Theatergeschichte des 18. bis 21. Jahrhunderts zur Verfügung
	(Schwerpunkt um 1900 bis 1950er Jahre). Sie sind grundsätzlich
	öffentlich zugänglich und werden unentgeltlich im Bereich der
	Institutsbibliothek zur Einsichtnahme vorgelegt. Mit der
	Theaterhistorischen Sammlung Walter Unruh, Dauerleihgabe des Landes
	Berlin, betreut das Institut eine der größten ehemaligen
	Privatsammlungen dieser Art. Darüber hinaus finden sich im
	Institutsarchiv weitere bedeutende Künstlernachlässe sowie umfangreiche
	Foto-, Theaterzettel- und Presseausschnittsammlungen. Insbesondere die
	Programmheftsammlung wird aktiv weitergeführt.<br>
	 Die Bestände sind nur
	teilweise in einer Datenbank erfasst. Eine detaillierte
	Bestandsübersicht steht auf der Homepage des Instituts zur Verfügung.
</p>

Webseite: <a target="_blank" href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/index.html">www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen</a><br>
E-Mail: <a href="mailto:peter.jammerthal@fu-berlin.de">peter.jammerthal@fu-berlin.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">Deutsches Tanzfilminstitut Bremen</a></h4>
<p>Das Deutsche Tanzfilminstitut Bremen ist ein nationales
	Archiv zur Sammlung, Aufbereitung und Produktion von audiovisuellen
	Tanzdokumenten. 1988 als Nonprofit-Organisation gegründet, unterstützt
	das Institut durch die Bereitstellung der gesammelten Materialien die
	Arbeit von Choreografen, Tanzkompanien, Theatern, Fachjournalisten und
	Fernsehanstalten und hilft bei der Produktion, Restauration und
	Digitalisierung von Tanzvideos und Filmen.
</p>

Webseite: <a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">www.deutsches-tanzfilminstitut.de</a><br>
E-Mail: <a href="http://deutsches-tanzfilminstitut.de/web/?page_id=9118">Mailformular</a><br>
<br>
<br>

<h4><a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">Theatermuseum der Landeshauptstadt Düsseldorf</a></h4>
<p>  Das
	Theatermuseum ging aus dem 1938 gegründeten privaten Theaterarchiv des
	"Schauspielhaus Düsseldorf Dumont-Lindemann“ (1904-1933) hervor und
	befindet sich nach der Schenkung von Gustaf Lindemann seit 1947 im
	Besitz der Stadt. Schwerpunkt für Sammlung, Forschung, Dokumentation
	und Ausstellungen ist heute die Theatergeschichte Düsseldorfs und der
	Region seit dem 16. Jahrhundert. Der Bestand umfasst vielfältige
	theaterbezogenen Sammlungen: Fotos, die grafische Sammlung, Quellen zur
	Theaterpraxis, audiovisuelle Medien, Handschriften, die
	Presseausschnittsammlung, dreidimensionale Objekte und eine
	wissenschaftliche Spezialbibliothek, wobei die Bestände vorwiegend aus
	dem 20. und 21. Jahrhundert stammen.
</p>

Webseite: <a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">www.duesseldorf.de/theatermuseum</a><br>
E-Mail: <a href="mailto:archiv.theatermuseum@duesseldorf.de">archiv.theatermuseum@duesseldorf.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html ">Universitätsbibliothek Frankfurt am Main -Fachinformationsdienst
	Darstellende Kunst</a></h4>
<p>In
	diesem Katalogausschnitt der UB Frankfurt finden Sie die für die
	Theater- und Filmwissenschaft relevanten Bücher und
	Nichtbuchmaterialien (AV-Medien, Noten, Illustrationen etc.) ab
	Erscheinungsjahr 1986 sowie Print- und Online-Zeitschriften (alle
	Erscheinungsjahre). <br>
	Der Bestand wird im Rahmen des
	<a target="_blank" href="http://www.ub.uni-frankfurt.de/theater/fid.html">Fachinformationsdienstes Darstellende Kunst</a> fortlaufend ergänzt.
</p>

Webseite: <a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html">www.ub.uni-frankfurt.de/musik/musik.html</a><br>
E-Mail: <a href="mailto:ls-spezialsammlungen@ub.uni-frankfurt.de">ls-spezialsammlungen@ub.uni-frankfurt.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44">Theatermuseum Hannover</a></h4>
<p> Der Sammlungsschwerpunkt des Archivs des Theatermuseums
	Hannover liegt auf den Materialien und Dokumenten zu den Aufführungen
	der Landeshauptstadt Niedersachsen, genauer: auf die Spielstätten der
	derzeitigen Staatstheater Hannover (Opernhaus, Schauspielhaus und
	Ballhof), sowie deren Vorläuferinstitute. Material zu Aufführungen
	anderer Bühnen in Hannover oder von auswärtigen Spielstätten sind zwar
	zum Teil einzeln vorhanden, werden aber nicht systematisch gesammelt.
	Das Material setzt sich für die Sparten Oper, Schauspiel, Ballett und
	Konzert im Wesentlichen zusammen aus Programmhefte bzw. –zettel;
	Rollen- und Szenenfotos bzw. Dias; Rezensionen; Bühnenbildmodelle und
	Figurinen.
</p>

Webseite: <a target="_blank" href="http://www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44">www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44</a><br>
E-Mail: <a href="mailto:theatermuseum@staatstheater-hannover.de">theatermuseum@staatstheater-hannover.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.sk-kultur.de/tanz">Deutsches Tanzarchiv Köln- Auszug aus der archivinternen Datenbank
	des Deutschen Tanzarchivs Köln (TIS-Tanzinformationssystem)</a></h4>
<p>  Das Archiv beherbergt über 400
	Nachlässe und Sammlungen von Tänzern, Choreographen, Tanzpädagogen und
	Ballettkritikern (Harald Kreutzberg, Kurt Jooss, die Duncans, die
	Sacharoffs, Mary Wigman, Dore Hoyer, usw). <br>
	Die Fotosammlung umfasst
	über 300.000 Aufnahmen / Negative sowie Fotografennachlässe (Siegfried
	Enkelmann, Dietmar Dünhöft, Hans Rama, usw.).<br>
	 Ferner verfügt das Archiv
	über eine umfangreiche Kunstsammlung (Nachlässe von Ernst Oppler,
	Arthur Grunenberg etc.) sowie eine Kostüm- und Plakatsammlung.<br>
	 Die
	Dokumentation archiviert rund 650.000 Zeitungsausschnitte seit den
	1950er Jahren und auch zu Sachthemen wie Ausdruckstanz (1920er/1930er
	Jahre), sowie etwa 30.000 Programmhefte. Die Bibliothek umfasst ca.
	14.000 Titel und rund 20.000 Fachzeitschriftenhefte. Die Videothek
	betreut über 4.500 Filme: Kamera-Choreographien, filmische
	Inszenierungen, experimentelle Tanzfilme, Musicals, Dokumentationen,
	Bühnenaufzeichnungen. Angeschlossen ist das Tanzmuseum zur Präsentation
	der Bestände.</p>
<p>1948 von dem Tänzer und Pädagogen Kurt Peters gegründet, wird das
	Tanzarchiv seit 1986 von der SK Stiftung Kultur in gemeinsamer
	Trägerschaft mit der Stadt Köln als Informations-, Dokumentations- und
	Forschungszentrum für Tanz zugänglich gemacht.
</p>

Webseite: <a target="_blank" href="http://www.sk-kultur.de/tanz">www.sk-kultur.de/tanz</a><br>
E-Mail: <a href="mailto:tanzarchiv@sk-kultur.de">tanzarchiv@sk-kultur.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">Theaterwissenschaftliche Sammlung der Universität zu Köln</a></h4>

<p> Die Theaterwissenschaftliche Sammlung der Universität zu
	Köln ist ein internationales Dokumentations- und Forschungszentrum für
	Theatergeschichte und Medienkultur. Schwerpunkte der Sammlung liegen
	zum einen auf der deutschsprachigen Theaterkultur – mit einem
	umfassenden Kritiken- und Fotoarchiv, das durch eine vielseitige
	graphische Sammlung ergänzt wird –, zum anderen auf den Theater- und
	Medienformen unterschiedlicher Kulturen und Epochen.
</p>

Webseite: <a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">tws.phil-fak.uni-koeln.de/21345.html</a><br>
E-Mail: <a href="mailto:info-tws@uni-koeln.de">info-tws@uni-koeln.de</a><br>
<br>
<br>


<h4><a href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">Tanzarchiv Leipzig</a></h4>
<p>
	Gegründet 1957 von Kurt Petermann als Sammlung traditionell
	überlieferter Folklore erweiterte sich das Tanzarchiv Leipzig zu einer
	Dokumentationsstelle zu "allen Gebieten des Tanzes". Bis zu seinem Tod
	im Jahr 1984 etablierte Petermann das Archiv als eine anerkannte
	Einrichtung der Auseinandersetzung mit Tanz als kulturellem Phänomen
	und erreichte 1975 die Angliederung an die Akademie der Künste der DDR.
	Seit 1993 arbeitet das Tanzarchiv Leipzig als gemeinnütziger Verein,
	begründet von der Universität Leipzig und der Hochschule für Musik und
	Theater "Felix Mendelssohn Bartholdy". 2011 wurde das Tanzarchiv
	Leipzig in die Verantwortung der UBL übergeben. Die Bestände gliedern
	sich in eine Fachbibliothek und die Sammlungen des Tanzarchivs. Dazu
	gehören Filmaufnahmen aus der zweiten Hälfte des 20. Jh.,
	Literatursammlungen, Nachlässe und Teilnachlässe, Plakate, Fotografien,
	Postkarten, Mikrofilme und Archivmaterial. Die Bestände sind teilweise
	in einer Datenbank erschlossen, die in den Sondersammlungen und an den
	Computern in der UBL benutzt werden kann.</p>


<p>Bestand: <br>
Tanz in seiner Vielfalt; Tanz in Bezug zu anderen
	Wissenschaften, Künsten und Medien; Tanzgeschichte; Volks-, Kinder-,
	Gesellschafts-, Turnier- und Bühnentanz; Tanztherapie; Tanzwissenschaft
	Nachlässe / Sammlungen: Rudolf von Laban, Mary Wigman, Gret Palucca,
	Jenny Gertz, Fritz Böhme, Jean Weidt, Rudolf Liechtenhan, Ilse Loesch,
	Kurt Petermann, Uwe Scholz, Staatliches Tanzensemble und Staatliches
	Folkloreensemble der DDR u.v.a. ca. 10.000 Medieneinheiten: Bücher,
	Nachschlagewerke, Musikalien, in- und ausländische Periodika, Zeitungs-
	und Zeitschriftenartikel, MCs, Videos, DVDs, Fotografien, Dias,
	Plakate, Programmhefte, Postkarten, Grafiken</p>

Webseite: <a target="_blank" href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070</a><br>
E-Mail: <a href="mailto:ruiz@ub.uni-leipzig.de">ruiz@ub.uni-leipzig.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.deutschestheatermuseum.de/">Deutsches Theatermuseum München, Bibliothek</a></h4>

<p> Das Deutsche
	Theatermuseum bewahrt nicht nur die Münchener Theatergeschichte,
	sondern ist deutschlandweit angelegt und dokumentiert darüber hinaus
	die europaweiten Verflechtungen des theatralen Kunstgeschehens.
	Insgesamt befinden sich ca. 250.000 grafische Blätter in der Sammlung
	sowie etwa 500.000 Autografen. Zum Barock besitzt das Deutsche
	Theatermuseum ein umfangreiches Konvolut an Originalgrafiken, und die
	wertvollsten Bestände der 130.000 Bände umfassenden Bibliothek reichen
	zurück bis in die Renaissance. Es verfügt außerdem über die weltweit
	umfangreichste Sammlung an Theaterfotografien einschließlich ihrer
	ersten Anfänge.
</p>

Webseite: <a target="_blank" href="http://www.deutschestheatermuseum.de/">www.deutschestheatermuseum.de</a><br>
E-Mail: <a href="mailto:bibliothek@deutschestheatermuseum.de">bibliothek@deutschestheatermuseum.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.theatersammlung.ch">Schweizerische Theatersammlung Bern</a></h4>

<p> Die Schweizerische Theatersammlung ist eine nationale
	Dokumentationsstelle des Schweizer Theaterschaffens. Sie wurde als
	Privatinitiative von Theaterakteuren 1927 gegründet und 1978 Überführt
	in eine privatrechtliche Stiftung mit Sitz in Bern. Seit ihrer Gründung
	erschließt die Theatersammlung die Metadaten zu den Schweizer
	Theaterveranstaltungen und archiviert die vielfältigen Dokumente, die
	bei der Vorbereitung, Ankündigung, Durchführung, Aufzeichnung,
	Beschreibung und Rezeption der Theaterinszenierungen aller Sparten und
	Formen entstehen. Sie besitzt auch die größte Fachbibliothek mit
	Büchern, Periodika und Stücktexten zum Schweizer Theaterwesen. Ein
	Großteil ihres Sammelgutes stammt aus dem 20. Jahrhundert und aus der
	Gegenwart.
</p>

Webseite: <a target="_blank" href="http://www.theatersammlung.ch">www.theatersammlung.ch</a><br>
E-Mail: <a href="mailto:info@theatersammlung.ch">info@theatersammlung.ch</a><br>
<br>
<br>


<h4><a target="_blank" href="http://www.theatermuseum.at">Theatermuseum Wien</a></h4>

<p>Im Gründungsjahr der Theatersammlung der
	Österreichischen Nationalbibliothek, 1922, bildete die aus dem Besitz
	des Burgschauspielers Hugo Thimig erworbene umfangreiche Büchersammlung
	jenen zentralen Bibliotheksbestand, um den sich die anderen Theatralia
	als non-book-materials gruppierten. Die aus diesen Anfängen
	hervorgegangene fachwissenschaftliche Studienbibliothek des
	Theatermuseums umfasst heute etwa 100.000 Bücher, Zeitschriftenbände,
	Bühnenmanuskripte und Theaterzettel mit den Sammlungsschwerpunkten
	Sprechtheater, Musiktheater, Tanz und Ballett, Figurentheater, Film,
	Fernsehen und Hörspiel.
</p>

Webseite: <a target="_blank" href="http://www.theatermuseum.at">www.theatermuseum.at</a><br>
E-Mail: <a href="mailto:bibliothek@theatermuseum.at">bibliothek@theatermuseum.at</a><br>
<br>
<br>

<?
} else {
    ?>

<a href="<?=$this->url('content-page', ['page' => 'netzwerke'])?>">Professional Associations and Research Groups in the Field</a><br>
<b>Institutions Documenting the History of the Performing Arts</b><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke3'])?>">Associations, Research Groups, etc.</a>
<br><br>

<p>Libraries, archives and collections of documents related to the performing arts are presented below with
  their individual focal points in a series of short portraits.
</p>

<h4>
	<a target="_blank" href="http://www.adk.de/en/archive/archive-inventory/performing_arts_archive/">Academy of the Arts Berlin, Performing Arts Archive</a>
</h4>
<p>
	The Archive collects, preserves, and catalogues documents and other items belonging
  to directors and conductors of theatre and musical performances; actors, dancers and
  choreographers; stage designers; critics; theatre scholars; dramatists; dramatologists;
  as well as cabarettists and composers working primarily in cabaret. Staging documentation
  has been used here as a submethod of theatre documentation to record how current stage
  productions by leading directors in theatre and musical performances came into being. <br>
  The seed for the Performing Arts Archive was sown in 1951-52, and in 1960 it received
  its first inherited private collections. The documents and other items it houses represent
  the period from the 19th century to today. The Archive preserves documents and items belonging
  to 270 people as well as housing 19 theme-based collections, including about 1,300 staging
  documentations. This adds up to more than 1,800 metres of archive material, over 25,000
  oversize pages and more than 35,000 photos.</p>
<p>Focal points of the collection:
<ul>
	<li>Members of the Academy of the Arts</li>
	<li>Theatre in Berlin</li>
	<li>Theatre in exile</li>
	<li>Theatre in the German Democratic Republic</li>
	<li>Theatre in the Federal Republic of Germany</li>
	<li>Contemporary theatre</li>
	<li>Expressionist dance</li>
	<li>Cabaret</li>
	<li>Criticism and Theatre Studies</li>
	<li>Archives owned by theatres and associations</li>
	<li>Staging documentation of theatre and musical performances</li>
	<li>Documentation of theatre during the period of German reunification</li>
</ul>
</p>

Website: <a target="_blank" href="http://www.adk.de/en/archive/archive-inventory/performing_arts_archive/">www.adk.de/en/archive/archive-inventory/performing_arts_archive/</a><br>
E-mail: <a href="mailto:archivdarstellendekunst@adk.de">archivdarstellendekunst@adk.de</a><br>
<br>
<br>

<h4>
	<a target="_blank" href="http://www.adk.de/en/archive/the-academy-of-arts-library/">Academy of the Arts Berlin, Library</a>
</h4>
<p>
	The Library houses documents and other items amounting to over 600,000 volumes on all
  disciplines in the arts. The focal point is the works of the Academy’s members and award
  winners. The documents and other items are supplemented by numerous special collections,
  with those on expressionism and literature produced in exile from 1933-1945 being
  especially noteworthy. <br>
	In addition, the Library boasts extensive collections of stage manuscripts, national
  and international exhibition catalogues, rare periodicals and the collections of
  institutions and artists’ associations.<br>
	Its unique character is underlined by over 300 private collections left to the Library
  by leading writers, architects and artists, as well as bibliophiles and members of the
  cultural establishment in both the German Democratic Republic and the Federal Republic
  of Germany.<br>
	For the <i>SIS</i> web portal, private collections in the field of performing arts have been selected,
  including those of Bertolt Brecht, Bernhard Minetti, Herbert Ihering and Christoph Schlingensief.
</p>

Website: <a target="_blank" href="http://www.adk.de/en/archive/the-academy-of-arts-library/">www.adk.de/en/archive/the-academy-of-arts-library/</a><br>
E-mail: <a href="mailto:Bibliothek@adk.de">Bibliothek@adk.de</a><br>
<br>
<br>

<h4>
	<a target="_blank" href="http://www.mimecentrum.de">Federal Republic of Germany Centre of the International Theatre Institute e.V., Mime Centrum Berlin,  Dance and Theatre Media Library</a>
</h4>
<p>The Mime Centrum Berlin is a public institute dedicated to documentation, information,
  research and hands-on work in dance and theatre.<br>
	With its video studio, a large rehearsal and workshop studio and an extensive media
  library, the Mime Centre explores the juxtaposition of hands-on and theoretical approaches
  to questions of bodily expression and types of movement in the performing arts.<br>
	The Media Library, with its more than 8,000 videos, books and periodicals, provides visitors
  a view into developments in the performing arts at a national and international level.
  The media library’s collection of documents and other items is being continually expanded
  by its own documentations, acquisition of collections, and items on loan from artists,
  festivals and theatres.<br>
	The Berlin Dance and Theatre Centre promotes the exchange of ideas between artists, researchers,
  journalists and others interested in the performing arts. At public events such as film viewings,
  lectures and discussions, it offers the public the opportunity to learn about significant
  developments in dance and theatre, both past and present.
</p>

Website: <a target="_blank" href="http://www.mimecentrum.de">www.mimecentrum.de</a><br>
E-mail: <a href="mailto:mediathek@mimecentrum.de">mediathek@mimecentrum.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/index.html">Freie
  Universität Berlin, Institute of Theatre Studies, Historical Theatre Collections</a></h4>
<p>
 The Free University’s Institute of Theatre Studies offers courses in Theatre Studies (BA and MA),
 Dance Studies (MA), Film Studies (BA and MA), and Music Studies. The courses are primarily based on
 theoretical, historical, and critical approaches, with the Institute being part of an international
 and interdisciplinary research community, maintaining contact with other institutes in the field
 with both a theoretical and hands-on orientation.<br>
 The Institute’s Historical Theatre Collections include extensive archives, especially on the history
 of theatre in Berlin from the 18th to the 21st centuries, with a focus on the period from 1900-1950.
 They are all open to the public and as part of the Institute’s library, can be viewed free of charge.
 The Institute houses the Walter Unruh Historical Theatre Collection, on permanent loan from the Federal
 State of Berlin, one of the largest formerly private collections of this kind. In addition, the
 Institute’s archive contains additional significant inherited private collections left to it by artists,
 and extensive collections of photos, theatre bulletins and press excerpts. Special attention is being
 paid to continuing the collection of theatre programmes. <br>
 Not all of the documents and other items have been entered into the database. You will find a detailed
 overview of the books and items on the Institute’s homepage:
</p>

Website: <a target="_blank" href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/index.html">www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen</a><br>
E-mail: <a href="mailto:peter.jammerthal@fu-berlin.de">peter.jammerthal@fu-berlin.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">German Institute of Dance Film Bremen</a></h4>
<p>The German Institute of Dance Video in Bremen is a national archive that collects, processes and produces
  audiovisual recordings of dance performances. It was founded in 1988 as a non-profit organisation with the
  aim of supporting the work of choreographers, dance companies, theatres, television production companies
  and journalists in the field by providing access to its video archive. It also assists in the production,
  restoration and digitalisation of dance videos and films.
</p>

Website: <a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">www.deutsches-tanzfilminstitut.de</a><br>
E-mail: <a href="http://deutsches-tanzfilminstitut.de/web/?page_id=9118">Mailformular</a><br>
<br>
<br>

<h4><a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">Theatre Museum of the State Capital of Düsseldorf</a></h4>

<p>The Theatre Museum grew out of the private theatre archive of the Düsseldorf Dumont-Lindemann Actors’ Association
  (1904 - 1933); the archive was founded in 1938. It was donated to the City of Düsseldorf by Gustaf Lindemann in 1947.
  Today, the focal point of its collections, research, documentation and exhibitions is the history of theatre in
  Düsseldorf and the surrounding region beginning in the 16th century. The documents and other items include a wide
  variety of theatre-related collections: photos, the collection of graphic arts, sources on theatre practice,
  audiovisual media, hand-written manuscripts, the collection of press excerpts, three-dimensional objects and a
  specialised library on theatre studies. Most of the documents and other items are from the 20th and 21st centuries.
</p>

Website: <a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">www.duesseldorf.de/theatermuseum</a><br>
E-mail: <a href="mailto:archiv.theatermuseum@duesseldorf.de">archiv.theatermuseum@duesseldorf.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html ">University Library Frankfurt am Main - Specialised
  Information Service Performing Arts</a></h4>

<p>This catalogue excerpt issued by the University Library Frankfurt lists books and other materials (audiovisual media,
  notes, illustrations, etc.) related to theatre and film studies and published beginning in 1986, as well as periodicals
  and online publications (all years of publication). <br>
  The documents and other items are being continually added to as part of the <i>Specialised Information Service Performing Arts</i>.
</p>

Website: <a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html">www.ub.uni-frankfurt.de/musik/musik.html</a><br>
E-mail: <a href="mailto:ls-spezialsammlungen@ub.uni-frankfurt.de">ls-spezialsammlungen@ub.uni-frankfurt.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44">Theatre Museum Hanover</a></h4>

<p>The focal point of the Theatre Museum Hanover’s collections is on documents and other materials related to
  performances staged by the Federal State Capital of Lower Saxony, or, to be more precise, on the stages of
  the current State Theatre of Hanover (Opernhaus, Schauspielhaus und Ballhof) as well as the institutions that
  preceded them. The Museum also houses individual materials related to performances in other Hanover theatres
  or to performances outside Hanover, but these are not collected systematically. The materials related to opera,
  acting, ballet, and concerts mostly consist of programmes and / or bulletins, role and scene photos or slides,
  reviews, stage design models and figurines.
</p>

Website: <a target="_blank" href="http://www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44">www.staatstheater-hannover.de/schauspiel/index.php?m=95&f=07_seiten&ID_Seite=44</a><br>
E-mail: <a href="mailto:theatermuseum@staatstheater-hannover.de">theatermuseum@staatstheater-hannover.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.sk-kultur.de/tanz/dtk-english.html">German Dance Archives Cologne – Excerpt from the In-house Database of
  the German Dance Archive Cologne (Dance Information System)</a></h4>

<p>The Archive houses over 400 inherited private libraries and collections once owned by dancers,
  choreographers, dance teachers and ballet critics (Harald Kreutzberg, Kurt Jooss, the Duncans,
  the Sacharoffs, Mary Wigman, Dore Hoyer, etc.).<br>
	The photo collection includes over 300,000 photos and/or negatives as well as inherited photo
  collections once owned by people in the field (Siegfried Enkelmann, Dietmar Dünhöft, Hans Rama, etc.).<br>
	In addition, the Archive has an extensive art collection (inherited private collections once owned
  by Ernst Oppler, Arthur Grunenberg etc.) as well as a collection of costumes and posters.<br>
	The documentation section archives approximately 650,000 newspaper excerpts beginning in the 1950s and includes
  articles on specialised topics such as expressionist dance (1920s - 1930s) as well as approximately 30,000 programmes.<br>
  The library boasts approximately 14,000 titles and about 20,000 periodicals related to the field.<br>
  The video library houses over 4,500 films, including camera choreographies, filmed stagings, experimental
  dance films, musicals, documentaries, and stage recordings.<br>
  The Dance Museum is next door and exhibits the items and collections.</p>
<p>The Dance Archive was founded in 1948 by the dancer and teacher Kurt Peters. Since 1986 it has been funded
  and run by the Stiftung Kultur (Cultural Foundation) in cooperation with the City of Cologne as
  an informational, documentation and research centre for the field of dance.
</p>

Website: <a target="_blank" href="http://www.sk-kultur.de/tanz/dtk-english.html">www.sk-kultur.de/tanz/dtk-english.html</a><br>
E-mail: <a href="mailto:tanzarchiv@sk-kultur.de">tanzarchiv@sk-kultur.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">Theatre Collection of the University of Cologne</a></h4>

<p>The Theatre Collection of the University of Cologne is an international documentation and research centre
  for theatre history and media culture. The focal points of the Collection are German-speaking theatre culture
  – with an extensive archive of reviews and photos, supplemented by a wide-ranging collection of graphic art –
  and the approaches to theatre and media in various cultures and epochs.
</p>

Website: <a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">tws.phil-fak.uni-koeln.de/21345.html</a><br>
E-mail: <a href="mailto:info-tws@uni-koeln.de">info-tws@uni-koeln.de</a><br>
<br>
<br>


<h4><a target="_blank" href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">Dance Archive Leipzig</a></h4>

<p>
Founded in 1957 as a collection of traditional folkloric items, the Leipzig Dance Archive has since expanded
to become a documentation centre representing all types of dance. By the time of his death in 1984, Petermann
had established the Archive as a well-recognized institution contributing to an understanding of dance as a
cultural phenomenon. In 1975, the Archive became an associate member of the German Democratic Republic’s Academy
of Arts. Since 1993, the Dance Archive has been run as a non-profit association founded by the University of
Leipzig and the Felix Mendelssohn Bartholdy Academy of Music and Theatre. In 2011, the Leipzig Dance Archive
was taken on the University of Leipzig Library. The documents and other items are divided into a specialised
library and the dance archive collection, which includes film recordings from the second half of the 20th century,
literary collections, full and partial inherited private collections, posters, photographs, postcards, microfilm
and other archive material. Some of the documents and other items have been entered into a database which can be
viewed in the special collections and using University of Leipzig Library computers. </p>

Website: <a target="_blank" href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070</a><br>
E-mail: <a href="mailto:ruiz@ub.uni-leipzig.de">ruiz@ub.uni-leipzig.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.deutschestheatermuseum.de/">German Theatre Museum Munich, Library</a></h4>

<p>The German Theatre Museum not only preserves the history of theatre in Munich, but in Germany as a whole.
  In addition, it documents the ties linking the theatre and cultural scenes in the various European countries.
  All in all, the collection consists of approximately 250,000 pages of graphics and approximately 500,000
  original manuscripts. The German Theatre Museum houses an extensive collection of original graphics from
  the Baroque period, and the most valuable of the 130,000 volumes date back to the Renaissance. In addition,
  the Museum owns the largest collection of theatre photographs worldwide, including some dating from the dawn
  of the photographic era.
</p>

Website: <a target="_blank" href="http://www.deutschestheatermuseum.de/">www.deutschestheatermuseum.de</a><br>
E-mail: <a href="mailto:bibliothek@deutschestheatermuseum.de">bibliothek@deutschestheatermuseum.de</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.theatersammlung.ch">Swiss Theatre Collection, Bern</a></h4>

<p>The Swiss Theatre Collection is a national documentation institute dedicated to the Swiss theatre
  and its works. It was founded as a private initiative by theatre actors in 1927 and in 1978 was given
  into the care of a privately run foundation with headquarters in Bern. Since it was founded, the
  Theatre Collection has been collecting and cataloguing metadata related to Swiss theatre events
  and has archived a wide range of documents describing all types of theatre productions during
  their preparation, announcement, implementation, recording, description and reception phases.
  The Collection also owns the largest specialised library, with books, periodicals and scripts related
  to Swiss theatre. A large proportion of the Collection dates from the 20th century and the present.
</p>

Website: <a target="_blank" href="http://www.theatersammlung.ch">www.theatersammlung.ch</a><br>
E-mail: <a href="mailto:info@theatersammlung.ch">info@theatersammlung.ch</a><br>
<br>
<br>

<h4><a target="_blank" href="http://www.theatermuseum.at/en">Theatre Museum Vienna</a></h4>

<p>In 1922 the Theatre Collection of the Austrian National Library was founded, with the large
  number of books acquired from the court theatre actor Hugo Thimig’s private collection providing a
  basis to which other theatre items and non-book materials were then added. The specialised library
  which has resulted from these beginnings now boasts approximately 100,000 books, volumes of periodicals,
  stage manuscripts and theatre bulletins, with the focal points being spoken and musical theatre, dance and
  ballet, puppet theatre, film, television, and audio plays.
</p>

Website: <a target="_blank" href="http://www.theatermuseum.at/en/">www.theatermuseum.at/en/</a><br>
E-mail: <a href="mailto:bibliothek@theatermuseum.at">bibliothek@theatermuseum.at</a><br>
<br>
<br>

<?
  }
?>
