<?php // Set page title.
$this->headTitle($this->transEsc('Networks') . ' - ' . $this->translate('FID Darstellende Kunst'));?>

<h2><?=$this->transEsc('Networks')?></h2>

<b>Professional Associations and Research Groups in the Field</b><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke2'])?>">Institutions Documenting the History of the Performing Arts</a><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke3'])?>">Associations, Research Groups, etc.</a>
<br><br>
<p>The <i>Specialised Information Service (SIS) Performing Arts</i> web portal displays
  the range of professional associations and research groups in theatre and dance-related academic research.</p><br>
<div class="card">
<a target="_blank" href="http://www.theater-wissenschaft.de" class="no-symbol"><img src="<?=$this->imageLink('gtw_logo.png')?>"></a>
<h4><a target="_blank" href="http://www.theater-wissenschaft.de">Society for Theatre Studies (gtw)</a></h4>
<p>The Society for Theatre Studies promotes research and teaching in the field of theatre studies. To this
  end it organises conferences, issues publications and serves as a public interface for the discipline. It
  includes all branches of theatre both past and present, as well as film, radio, television and video arts.</p>
</div>
<div class="card">
<a target="_blank" href="http://www.theatergeschichte.org" class="no-symbol"><img src="<?=$this->imageLink('theatergeschichte_logo.png')?>"></a>
<h4><a target="_blank" href="http://www.theatergeschichte.org">Society for Theatre History</a></h4>
<p>The Society for Theatre History was founded in Berlin in 1902 by writers, journalists, scholars, aficionados
  and others with an interest in theatre, with the aim of creating an interdisciplinary forum for involvement
  in theatre both past and present.<br>
  The Society is an independent academic network with ties to numerous other research and teaching institutions
  in the theatre studies, as well as to theatre archives, museums and libraries both in Germany and abroad.
  Currently the Association has about 50 members and 70 institutional members (institutes and/or libraries).</p>
</div>
<div class="card">
<a target="_blank" href="http://gtf.danceinfo.de/en/home/" class="no-symbol"><img src="<?=$this->imageLink('gft_logo.png')?>"></a>
<h4><a target="_blank" href="http://gtf.danceinfo.de/en/home/">Society of Dance Research (GFT)</a></h4>
<p>In the mid-1980s with the encouragement of UNESCO, efforts were made to unite all dance organisations in the Federal
  Republic of Germany into an umbrella organisation. These initiatives finally resulted in the Society for Dance
  Research, or GTF, which was founded on May 31 1986 in Cologne. <br>
  The GTF aims to inspire and support dance-related research and to promote communication on the topic. Based in the
  German-speaking countries (Germany, Austria, and Switzerland) it also creates international networking and an exchange of ideas.
</p>
</div>
