<?php // Set page title.
$this->headTitle($this->transEsc('Networks') . ' - ' . $this->translate('FID Darstellende Kunst'));?>

<h2><?=$this->transEsc('Networks')?></h2>

<b>Fachgesellschaften und Arbeitskreise</b><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke2'])?>">Gedächtnisinstitutionen der Darstellenden Künste</a><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke3'])?>">Verbünde, Arbeitskreise etc.</a>
<br><br>
<p>Der <i>Fachinformationsdienst Darstellende Kunst</i> stellt Ihnen in dieser Rubrik
Fachgesellschaften sowie Arbeitskreise der theater- und tanzwissenschaftlichen
Forschung vor.</p><br>
<div class="card">
<a target="_blank" href="http://www.theater-wissenschaft.de" class="no-symbol"><img src="<?=$this->imageLink('gtw_logo.png')?>"></a>
<h4><a target="_blank" href="http://www.theater-wissenschaft.de">Gesellschaft für Theaterwissenschaft (gtw)</a></h4>
<p>Die Gesellschaft für Theaterwissenschaft hat die Aufgabe, die Theaterwissenschaft
in Forschung und Lehre zu fördern. Sie veranstaltet zu diesem Zweck Kongresse, gibt
Publikationen heraus und vertritt die Interessen des Faches nach außen. Ihr Interesse
gilt dem Theater in allen seinen Ausprägungen in Geschichte und Gegenwart, sowie Film,
Hörfunk, Fernsehen und Video.</p>
</div>
<div class="card">
<a target="_blank" href="http://www.theatergeschichte.org" class="no-symbol"><img src="<?=$this->imageLink('theatergeschichte_logo.png')?>"></a>
<h4><a target="_blank" href="http://www.theatergeschichte.org">Gesellschaft für Theatergeschichte</a></h4>
<p>Die Gesellschaft für Theatergeschichte e. V. wurde am 6. April 1902 in Berlin von
 Schriftstellern, Journalisten, Gelehrten, Bühnenangehörigen und anderen am Theater
 Interessierten mit dem Ziel gegründet, ein spartenübergreifendes Forum zur Beschäftigung
 mit dem Theater in Geschichte und Gegenwart zu schaffen.<br>
Sie ist eine selbständige wissenschaftliche Vereinigung mit Verbindung zu zahlreichen
anderen theaterwissenschaftlichen Lehr- und Forschungseinrichtungen, Theatersammlungen,
 Museen und Bibliotheken des In- und Auslandes. Gegenwärtig gehören der Gesellschaft etwa
 50 persönliche und 70 korporative Mitglieder (Institute/Bibliotheken) an.</p>
 </div>
<div class="card">
<a target="_blank" href="http://www.gtf-tanzforschung.de" class="no-symbol"><img src="<?=$this->imageLink('gft_logo.png')?>"></a>
<h4><a target="_blank" href="http://www.gtf-tanzforschung.de">Gesellschaft für Tanzforschung (GFT)</a></h4>
<p>Angeregt durch die UNESCO gab es Mitte der 80er Jahre in der BRD Bestrebungen zum
Zusammenschluss aller Tanzvereinigungen zu einem Tanzrat. Aus diesen Initiativen entstand
schließlich die Gesellschaft für Tanzforschung, gegründet am 31. Mai 1986 in Köln.<br>
Die GTF versteht sich als Ort der Anregung und Unterstützung von Forschungsaktivitäten
im Bereich des Tanzes und der Kommunikation darüber. Ausgehend vom deutschsprachigen Raum
(Deutschland, Österreich, Schweiz) strebt sie internationalen Austausch und Vernetzung an.</p>
</div>
