<?php // Set page title.
$this->headTitle($this->translate('Networks') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Networks')?></h2>

<a href="<?=$this->url('content-page', ['page' => 'netzwerke'])?>">Fachgesellschaften und Arbeitskreise</a><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke2'])?>">Gedächtnisinstitutionen der Darstellenden Künste</a><br>
<b>Verbünde, Arbeitskreise etc.</b>
<br><br>

<!-- <h4>Bundesverband der Museen, Bibliotheken und Archive für Darstellende Künste e.V.</h4>
<br>
<br> -->

<div class="card">

<h4><a target="_blank" href="http://www.thesid.de/">Bundesverband der Theatersammelnden Institutionen in Deutschland (TheSiD) e.V.</a></h4>
<p>Der Bundesverband der Theatersammelnden Institutionen in Deutschland (TheSiD) versteht sich als Interessenvertretung
  der deutschen Theaterarchive, -bibliotheken und -museen. Er ist der deutsche Zweig der Internationalen Gesellschaft der
  Bibliotheken und Museen für Darstellende Künste (Société Internationale des bibliothèques et des musées des arts du spectacle = SIBMAS).
  All dies, was zum Kernbereich des materiellen kulturellen Erbes gehört und das nachdrücklich auf das immaterielle Kulturerbe des Theaters
  verweist, ist aber auch immer wieder durch jene bedroht, die dieses ihnen anvertraute Erbe nicht verstehen und nicht schätzen. Die TheSiD
  will in der Öffentlichkeit ein Bewusstsein und auch die Wertschätzung schaffen für diese oft einmaligen kulturellen Schätze, die man
  bewahren, aber auch erklären muss, denn das Materielle verweist auf den eigentlichen Gehalt des Immateriellen.</p>
  Website: <a target="_blank" href="http://www.thesid.de/">www.thesid.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.tanzarchive.de/en/home">Verbund Deutscher Tanzarchive</a></h4>
<p>Zum Verbund Deutscher Tanzarchive (VDT) haben sich 2007 die fünf führenden Institutionen zur Bestander¬haltung und Erschließung von Quellen und Dokumenten zur Entwicklungs- und Aufführungsgeschichte der Kunstform Tanz in Deutschland nominell zusammengeschlossen. Diese fünf Institutionen sind:
<ul>
<li>Deutsches Tanzarchiv Köln </li>
<li>Tanzarchiv Leipzig</li>
<li>Deutsches Tanzfilminstitut Bremen</li>
<li>Mime Centrum Berlin</li>
<li>Archiv Darstellende Künste der Akademie der Künste</li>
</ul>
</p>
Website: <a target="_blank" href="http://www.tanzarchive.de/en/home">www.tanzarchive.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.theaterarchive.de">Runder Tisch der Berliner Theatersammlungen</a></h4>
<p>Der Runde Tisch der Berliner Theatersammlungen gründete sich im Mai 2011 als ein internes
Verständigungsforum der theatersammelnden Institutionen Berlins sowie der um die Dokumentation
ihrer Arbeit bemühten Theater und Künstler. Berlin hat nicht nur eine reiche Theatervergangenheit, sondern eine Vielzahl von Materialien, die diese Vergangenheit bezeugen und die in sehr unterschiedlichen Institutionen aufbewahrt werden. Dies hat mit der Geschichte der Stadt wie mit der Spezifik des Theaters zu tun. Die Komplexität der gesammelten Materialien entspricht der Komplexität des Theaters, die Vielfalt
der Materialien der Vielfältigkeit des Theaters. Beides erschwert den Umgang mit den umfangreichen
und – typisch für die kollektive Kunstform Theater – äußerst unterschiedlichen Materialien, die in den
einzelnen Archiven aufbewahrt werden.</p>
Website: <a target="_blank" href="http://www.theaterarchive.de">www.theaterarchive.de</a>
</div>
