<?php // Set page title.
$this->headTitle($this->translate('Networks') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Networks')?></h2>

<a href="<?=$this->url('content-page', ['page' => 'netzwerke'])?>">Fachgesellschaften und Arbeitskreise</a><br>
<b>Gedächtnisinstitutionen der Darstellenden Künste</b><br>
<a href="<?=$this->url('content-page', ['page' => 'netzwerke3'])?>">Verbünde, Arbeitskreise etc.</a>
<br><br>

<p>In kurzen Portraits werden Ihnen Bibliotheken, Archive und Sammlungen
	der darstellenden Kunst mit ihren Sammelschwerpunkten vorgestellt.</p>

<div class="card">
<h4>
	<a target="_blank" href="http://www.adk.de/de/archiv/archivbestand/darstellende-kunst/">Akademie
		der Künste Berlin, Archiv Darstellende Kunst</a>
</h4>
<p>
	Das Archiv sammelt, bewahrt, erschließt Bestände von Regisseuren,
	Intendanten im Bereich Sprech- und Musiktheater, von Schauspielern,
	Tänzern und Choreographen, Bühnenbildnern, Kritikern,
	Theaterwissenschaftlern, Dramatikern, Dramaturgen, Kabarettisten und
	Komponisten vorrangig für den Bereich Kabarett. Mit Hilfe der Methode
	der Inszenierungsdokumentation werden im Bereich Theaterdokumentation
	Arbeitsprozesse und -ergebnisse aktueller Inszenierungen führender
	Regisseure des Sprech- und Musiktheaters festgehalten. <br>
	Die Anfänge
	des Archivs Darstellende Kunst gehen in die Jahre 1951/52 zurück. 1960
	wurden die ersten Nach- und Vorlässe übernommen. Der zeitliche Umfang
	der Bestände erstreckt sich vom 19. Jahrhundert bis in die unmittelbare
	Gegenwart. Das Archiv betreut 270 Personenbestände und 19 thematische
	Sammlungen, darunter etwa 1.300 Inszenierungsdokumentationen, das sind
	mehr als 1.800 laufende Meter (lfm.) Archivgut, über 25.000 Blatt
	großformatige Blätter und mehr als 35.000 Fotos.</p>
<p>Sammlungsschwerpunkte:
<ul>
	<li>Mitglieder der Akademie der Künste</li>
	<li>Theater in Berlin</li>
	<li>Theater im Exil</li>
	<li>Theater der DDR</li>
	<li>Theater der BRD</li>
	<li>Aktuelles Theater</li>
	<li>Ausdruckstanz</li>
	<li>Kabarett</li>
	<li>Kritik und Theaterwissenschaft</li>
	<li>Archive von Theatern und Verbänden</li>
	<li>Inszenierungsdokumentationen des Sprech- und Musiktheaters</li>
	<li>Dokumentation Theater in der Wende</li>
</ul>
</p>

Webseite: <a target="_blank" href="http://www.adk.de/de/archiv/archivbestand/darstellende-kunst/">www.adk.de/de/archiv/archivbestand/darstellende-kunst</a><br>
E-Mail: <a href="mailto:archivdarstellendekunst@adk.de">archivdarstellendekunst@adk.de</a>
</div>

<div class="card">
<h4>
	<a target="_blank" href="http://www.adk.de/de/archiv/bibliothek">Akademie der Künste
		Berlin, Bibliothek</a>
</h4>
<p>
	Die Bibliothek verfügt über einen Bestand von mehr als 600.000 Bänden
	und umfasst alle Sparten der Künste. Der Sammelschwerpunkt liegt auf
	Werken der Mitglieder und Preisträger der Akademie, ergänzt werden die
	Bestände um zahlreiche Sondersammlungen, besonders herausragend z.B.
	zum Expressionismus und zur Exilliteratur zwischen 1933 und 1945.<br>
	Darüber hinaus besitzt die Bibliothek umfangreiche Sammlungen von
	Bühnenmanuskripten, nationalen und internationalen
	Ausstellungskatalogen, seltenen Zeitschriften sowie Bibliotheken von
	Institutionen und Künstlervereinigungen.<br>
	 Ihren einzigartigen Charakter
	begründen über 300 Nachlassbibliotheken bedeutender Schriftsteller,
	Architekten und Künstler sowie bibliophiler Sammler und Repräsentanten
	der Kulturpolitik in der DDR und in der BRD.<br>
	Für das Portal des <i>Fachinformationsdienstes Darstellende Kunst</i> wurden
  fachspezifische	Nachlass- und Sammlungsbibliotheken ausgewählt, darunter z.B.
  Bertolt	Brecht, Bernhard Minetti, Herbert Ihering und Christoph Schlingensief.
</p>

Webseite: <a target="_blank" href="http://www.adk.de/de/archiv/bibliothek">www.adk.de/de/archiv/bibliothek</a><br>
E-Mail: <a href="mailto:Bibliothek@adk.de">Bibliothek@adk.de</a>
</div>

<div class="card">
<h4>
	<a target="_blank" href="http://www.mimecentrum.de">Internationales Theaterinstitut Deutschland, Mime Centrum Berlin, Mediathek für Tanz und Theater</a>
</h4>
<p>Das Mime Centrum Berlin ist ein öffentlicher Ort der Dokumentation,
	Information, der Forschung und praktischen Arbeit im Bereich Tanz und
	Theater.<br>
	Mit seinem Videostudio, einem großen Proben- und
	Workshop-Studio sowie einer umfangreichen Mediathek verbindet das Mime
	Centrum in seiner Arbeitsstruktur Möglichkeiten der praktischen und
	theoretischen Auseinandersetzung zu Fragen der Körperarbeit und zu
	Bewegungsmethoden in den Darstellenden Künsten.<br>
	Die Mediathek für Tanz
	und Theater mit mehr als 8000 Videodatenträgern, Buch- und
	Zeitschriftenbeständen gibt Einblick in nationale und internationale
	Entwicklungen der Darstellenden Kunst. Der Bestand der Mediathek wird
	kontinuierlich erweitert durch eigene Dokumentationen, die Übernahme
	von Sammlungen und Leihgaben von Künstlern, Festivals und Theatern.<br>
	Das
	Mime Centrum Berlin dient dem Austausch von Künstlern, Forschern,
	Journalisten und allen weiteren Interessenten. In öffentlichen Formaten
	wie Filmveranstaltungen, Lectures und Diskussionen bietet es die
	Möglichkeit zur Befragung und Kommunikation von aktuellen und
	historischen Ereignissen in Tanz und Theater.
</p>

Webseite: <a target="_blank" href="http://www.mimecentrum.de">www.mimecentrum.de</a><br>
E-Mail: <a href="mailto:mediathek@mimecentrum.de">mediathek@mimecentrum.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://www.geisteswissenschaften.fu-berlin.de/we07/institut/theaterhistorische_sammlungen/index.html">Freie Universität Berlin, Institut für Theaterwissenschaft,
	Theaterhistorische Sammlungen</a></h4>
<p>
 Das Institut für Theaterwissenschaft der Freien
	Universität bietet die Studiengänge Theaterwissenschaft (BA und MA),
	Tanzwissenschaft (MA), Filmwissenschaft (BA und MA), Musikwissenschaft
	an. Das Studium ist vorwiegend theoretisch und historisch-kritisch
	ausgerichtet, das Institut ist dabei in ein internationales und
	interdisziplinäres Forschungsumfeld eingebunden und pflegt umfangreiche
	Kontakte zu anderen fachverbundenen wissenschaftlichen und praktischen
	Einrichtungen.<br>
	 In den Theaterhistorischen Sammlungen des Instituts
	stehen dazu umfangreiche Archivbestände insbesondere zur Berliner
	Theatergeschichte des 18. bis 21. Jahrhunderts zur Verfügung
	(Schwerpunkt um 1900 bis 1950er Jahre). Sie sind grundsätzlich
	öffentlich zugänglich und werden unentgeltlich im Bereich der
	Institutsbibliothek zur Einsichtnahme vorgelegt. Mit der
	Theaterhistorischen Sammlung Walter Unruh, Dauerleihgabe des Landes
	Berlin, betreut das Institut eine der größten ehemaligen
	Privatsammlungen dieser Art. Darüber hinaus finden sich im
	Institutsarchiv weitere bedeutende Künstlernachlässe sowie umfangreiche
	Foto-, Theaterzettel- und Presseausschnittsammlungen. Insbesondere die
	Programmheftsammlung wird aktiv weitergeführt.<br>
	 Die Bestände sind nur
	teilweise in einer Datenbank erfasst. Eine detaillierte
	Bestandsübersicht steht auf der Homepage des Instituts zur Verfügung.
</p>

Webseite: <a target="_blank" href="https://www.geisteswissenschaften.fu-berlin.de/we07/institut/theaterhistorische_sammlungen/index.html">https://www.geisteswissenschaften.fu-berlin.de/we07/institut/theaterhistorische_sammlungen/index.html</a><br>
E-Mail: <a href="mailto:peter.jammerthal@fu-berlin.de">peter.jammerthal@fu-berlin.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">Deutsches Tanzfilminstitut Bremen</a></h4>
<p>Das Deutsche Tanzfilminstitut Bremen ist ein nationales
	Archiv zur Sammlung, Aufbereitung und Produktion von audiovisuellen
	Tanzdokumenten. 1988 als Nonprofit-Organisation gegründet, unterstützt
	das Institut durch die Bereitstellung der gesammelten Materialien die
	Arbeit von Choreografen, Tanzkompanien, Theatern, Fachjournalisten und
	Fernsehanstalten und hilft bei der Produktion, Restauration und
	Digitalisierung von Tanzvideos und Filmen.
</p>

Webseite: <a target="_blank" href="http://www.deutsches-tanzfilminstitut.de/">www.deutsches-tanzfilminstitut.de</a><br>
E-Mail: <a href="http://deutsches-tanzfilminstitut.de/web/?page_id=9118">Mailformular</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">Theatermuseum der Landeshauptstadt Düsseldorf</a></h4>
<p>  Das
	Theatermuseum ging aus dem 1938 gegründeten privaten Theaterarchiv des
	"Schauspielhaus Düsseldorf Dumont-Lindemann“ (1904-1933) hervor und
	befindet sich nach der Schenkung von Gustaf Lindemann seit 1947 im
	Besitz der Stadt. Schwerpunkt für Sammlung, Forschung, Dokumentation
	und Ausstellungen ist heute die Theatergeschichte Düsseldorfs und der
	Region seit dem 16. Jahrhundert. Der Bestand umfasst vielfältige
	theaterbezogenen Sammlungen: Fotos, die grafische Sammlung, Quellen zur
	Theaterpraxis, audiovisuelle Medien, Handschriften, die
	Presseausschnittsammlung, dreidimensionale Objekte und eine
	wissenschaftliche Spezialbibliothek, wobei die Bestände vorwiegend aus
	dem 20. und 21. Jahrhundert stammen.
</p>

Webseite: <a target="_blank" href="https://www.duesseldorf.de/theatermuseum/">www.duesseldorf.de/theatermuseum</a><br>
E-Mail: <a href="mailto:archiv.theatermuseum@duesseldorf.de">archiv.theatermuseum@duesseldorf.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://www.performing-arts.eu/">Universitätsbibliothek Frankfurt am Main -Fachinformationsdienst
	Darstellende Kunst</a></h4>
<p>In
	diesem Katalogausschnitt der UB Frankfurt finden Sie die für die
	Theater- und Filmwissenschaft relevanten Bücher und
	Nichtbuchmaterialien (AV-Medien, Noten, Illustrationen etc.) ab
	Erscheinungsjahr 1986 sowie Print- und Online-Zeitschriften (alle
	Erscheinungsjahre). <br>
	Der Bestand wird im Rahmen des
	<a target="_blank" href="https://www.performing-arts.eu/">Fachinformationsdienstes Darstellende Kunst</a> fortlaufend ergänzt.
</p>

Webseite: <a target="_blank" href="https://www.ub.uni-frankfurt.de/musik/">www.ub.uni-frankfurt.de/musik/</a><br>
E-Mail: <a href="mailto:slg-musik-theater@ub.uni-frankfurt.de">slg-musik-theater@ub.uni-frankfurt.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://www.staatstheater-hannover.de/de_DE/theatermuseum-willkommen">Theatermuseum Hannover</a></h4>
<p> Der Sammlungsschwerpunkt des Archivs des Theatermuseums
	Hannover liegt auf den Materialien und Dokumenten zu den Aufführungen
	der Landeshauptstadt Niedersachsen, genauer: auf die Spielstätten der
	derzeitigen Staatstheater Hannover (Opernhaus, Schauspielhaus und
	Ballhof), sowie deren Vorläuferinstitute. Material zu Aufführungen
	anderer Bühnen in Hannover oder von auswärtigen Spielstätten sind zwar
	zum Teil einzeln vorhanden, werden aber nicht systematisch gesammelt.
	Das Material setzt sich für die Sparten Oper, Schauspiel, Ballett und
	Konzert im Wesentlichen zusammen aus Programmhefte bzw. –zettel;
	Rollen- und Szenenfotos bzw. Dias; Rezensionen; Bühnenbildmodelle und
	Figurinen.
</p>

Webseite: <a target="_blank" href="https://www.staatstheater-hannover.de/de_DE/theatermuseum-willkommen">https://www.staatstheater-hannover.de/de_DE/theatermuseum-willkommen</a><br>
E-Mail: <a href="mailto:theatermuseum@staatstheater-hannover.de">theatermuseum@staatstheater-hannover.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.sk-kultur.de/tanz">Deutsches Tanzarchiv Köln- Auszug aus der archivinternen Datenbank
	des Deutschen Tanzarchivs Köln (TIS-Tanzinformationssystem)</a></h4>
<p>  Das Archiv beherbergt über 400
	Nachlässe und Sammlungen von Tänzern, Choreographen, Tanzpädagogen und
	Ballettkritikern (Harald Kreutzberg, Kurt Jooss, die Duncans, die
	Sacharoffs, Mary Wigman, Dore Hoyer, usw). <br>
	Die Fotosammlung umfasst
	über 300.000 Aufnahmen / Negative sowie Fotografennachlässe (Siegfried
	Enkelmann, Dietmar Dünhöft, Hans Rama, usw.).<br>
	 Ferner verfügt das Archiv
	über eine umfangreiche Kunstsammlung (Nachlässe von Ernst Oppler,
	Arthur Grunenberg etc.) sowie eine Kostüm- und Plakatsammlung.<br>
	 Die
	Dokumentation archiviert rund 650.000 Zeitungsausschnitte seit den
	1950er Jahren und auch zu Sachthemen wie Ausdruckstanz (1920er/1930er
	Jahre), sowie etwa 30.000 Programmhefte. Die Bibliothek umfasst ca.
	14.000 Titel und rund 20.000 Fachzeitschriftenhefte. Die Videothek
	betreut über 4.500 Filme: Kamera-Choreographien, filmische
	Inszenierungen, experimentelle Tanzfilme, Musicals, Dokumentationen,
	Bühnenaufzeichnungen. Angeschlossen ist das Tanzmuseum zur Präsentation
	der Bestände.</p>
<p>1948 von dem Tänzer und Pädagogen Kurt Peters gegründet, wird das
	Tanzarchiv seit 1986 von der SK Stiftung Kultur in gemeinsamer
	Trägerschaft mit der Stadt Köln als Informations-, Dokumentations- und
	Forschungszentrum für Tanz zugänglich gemacht.
</p>

Webseite: <a target="_blank" href="http://www.sk-kultur.de/tanz">www.sk-kultur.de/tanz</a><br>
E-Mail: <a href="mailto:tanzarchiv@sk-kultur.de">tanzarchiv@sk-kultur.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">Theaterwissenschaftliche Sammlung der Universität zu Köln</a></h4>

<p> Die Theaterwissenschaftliche Sammlung der Universität zu
	Köln ist ein internationales Dokumentations- und Forschungszentrum für
	Theatergeschichte und Medienkultur. Schwerpunkte der Sammlung liegen
	zum einen auf der deutschsprachigen Theaterkultur – mit einem
	umfassenden Kritiken- und Fotoarchiv, das durch eine vielseitige
	graphische Sammlung ergänzt wird –, zum anderen auf den Theater- und
	Medienformen unterschiedlicher Kulturen und Epochen.
</p>

Webseite: <a target="_blank" href="http://tws.phil-fak.uni-koeln.de/21345.html">tws.phil-fak.uni-koeln.de/21345.html</a><br>
E-Mail: <a href="mailto:info-tws@uni-koeln.de">info-tws@uni-koeln.de</a>
</div>

<div class="card">
<h4><a href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">Tanzarchiv Leipzig</a></h4>
<p>
	Gegründet 1957 von Kurt Petermann als Sammlung traditionell
	überlieferter Folklore erweiterte sich das Tanzarchiv Leipzig zu einer
	Dokumentationsstelle zu "allen Gebieten des Tanzes". Bis zu seinem Tod
	im Jahr 1984 etablierte Petermann das Archiv als eine anerkannte
	Einrichtung der Auseinandersetzung mit Tanz als kulturellem Phänomen
	und erreichte 1975 die Angliederung an die Akademie der Künste der DDR.
	Seit 1993 arbeitet das Tanzarchiv Leipzig als gemeinnütziger Verein,
	begründet von der Universität Leipzig und der Hochschule für Musik und
	Theater "Felix Mendelssohn Bartholdy". 2011 wurde das Tanzarchiv
	Leipzig in die Verantwortung der UBL übergeben. Die Bestände gliedern
	sich in eine Fachbibliothek und die Sammlungen des Tanzarchivs. Dazu
	gehören Filmaufnahmen aus der zweiten Hälfte des 20. Jh.,
	Literatursammlungen, Nachlässe und Teilnachlässe, Plakate, Fotografien,
	Postkarten, Mikrofilme und Archivmaterial. Die Bestände sind teilweise
	in einer Datenbank erschlossen, die in den Sondersammlungen und an den
	Computern in der UBL benutzt werden kann.</p>


<p>Bestand: <br>
Tanz in seiner Vielfalt; Tanz in Bezug zu anderen
	Wissenschaften, Künsten und Medien; Tanzgeschichte; Volks-, Kinder-,
	Gesellschafts-, Turnier- und Bühnentanz; Tanztherapie; Tanzwissenschaft
	Nachlässe / Sammlungen: Rudolf von Laban, Mary Wigman, Gret Palucca,
	Jenny Gertz, Fritz Böhme, Jean Weidt, Rudolf Liechtenhan, Ilse Loesch,
	Kurt Petermann, Uwe Scholz, Staatliches Tanzensemble und Staatliches
	Folkloreensemble der DDR u.v.a. ca. 10.000 Medieneinheiten: Bücher,
	Nachschlagewerke, Musikalien, in- und ausländische Periodika, Zeitungs-
	und Zeitschriftenartikel, MCs, Videos, DVDs, Fotografien, Dias,
	Plakate, Programmhefte, Postkarten, Grafiken</p>

Webseite: <a target="_blank" href="https://www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070">www.ub.uni-leipzig.de/forschungsbibliothek/historische-bestaende/archive/#c1070</a><br>
E-Mail: <a href="mailto:sondersammlungen@ub.uni-leipzig.de">sondersammlungen@ub.uni-leipzig.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.deutschestheatermuseum.de/">Deutsches Theatermuseum München, Bibliothek</a></h4>

<p> Das Deutsche
	Theatermuseum bewahrt nicht nur die Münchener Theatergeschichte,
	sondern ist deutschlandweit angelegt und dokumentiert darüber hinaus
	die europaweiten Verflechtungen des theatralen Kunstgeschehens.
	Insgesamt befinden sich ca. 250.000 grafische Blätter in der Sammlung
	sowie etwa 500.000 Autografen. Zum Barock besitzt das Deutsche
	Theatermuseum ein umfangreiches Konvolut an Originalgrafiken, und die
	wertvollsten Bestände der 130.000 Bände umfassenden Bibliothek reichen
	zurück bis in die Renaissance. Es verfügt außerdem über die weltweit
	umfangreichste Sammlung an Theaterfotografien einschließlich ihrer
	ersten Anfänge.
</p>

Webseite: <a target="_blank" href="http://www.deutschestheatermuseum.de/">www.deutschestheatermuseum.de</a><br>
E-Mail: <a href="mailto:bibliothek@deutschestheatermuseum.de">bibliothek@deutschestheatermuseum.de</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://sapa.swiss/">Stiftung SAPA, Schweizer Archiv der Darstellenden Künste</a></h4>

<p>Die Stiftung SAPA sammelt, dokumentiert, archiviert und verbreitet in der Schweiz
   produzierte, mit der Schweiz in Verbindung stehende oder für sie bedeutende
   Werke aus dem Bereich der Darstellenden Künste (Tanz, Theater, Performance).
   All diese Dokumente bilden die Helvetica der Darstellenden Künste. SAPA ist am
   1. Januar 2017 aus dem Zusammenschluss zweier Institutionen entstanden:
   <ul>
     <li>Das Schweizerische Tanzarchiv, das wiederum aus dem Zusammenschluss der
       Archives suisses de la danse (gegründet 1993 von Jean Pierre Pastori in
       Lausanne) und der mediathek tanz.ch (gegründet 2005 von Wolfgang Brunner
       und Eva Richterich in Zürich) hervorgegangen ist.</li>
     <li>Die Schweizerische Theatersammlung STS, gegründet 1927 als Privatinitiative
       von Theaterakteuren, wurde 1978 in eine Stiftung (mit drei öffentlichen
       Stiftungsträgern und der Schweizerischen Gesellschaft für Theaterkultur
       SGTK als Mitstifterin) überführt.</li>
  </ul>
</p>

Webseite: <a target="_blank" href="https://sapa.swiss/">https://sapa.swiss/</a>
</div>

<div class="card">
<h4><a target="_blank" href="http://www.theatermuseum.at">Theatermuseum Wien</a></h4>

<p>Im Gründungsjahr der Theatersammlung der
	Österreichischen Nationalbibliothek, 1922, bildete die aus dem Besitz
	des Burgschauspielers Hugo Thimig erworbene umfangreiche Büchersammlung
	jenen zentralen Bibliotheksbestand, um den sich die anderen Theatralia
	als non-book-materials gruppierten. Die aus diesen Anfängen
	hervorgegangene fachwissenschaftliche Studienbibliothek des
	Theatermuseums umfasst heute etwa 100.000 Bücher, Zeitschriftenbände,
	Bühnenmanuskripte und Theaterzettel mit den Sammlungsschwerpunkten
	Sprechtheater, Musiktheater, Tanz und Ballett, Figurentheater, Film,
	Fernsehen und Hörspiel.
</p>

Webseite: <a target="_blank" href="http://www.theatermuseum.at">www.theatermuseum.at</a><br>
E-Mail: <a href="mailto:bibliothek@theatermuseum.at">bibliothek@theatermuseum.at</a>
</div>

<div class="card">
<h4><a target="_blank" href="https://www.fidena.de">Deutsches Forum für Figurentheater und Puppenspielkunst</a></h4>

<p>Die Fachbibliothek des Deutsches Forum für Figurentheater und Puppenspielkunst (dfp) e.V. steht allen Interessierten vor Ort und über das
  <a href="https://www.fidena.de/portal/forschungszentrum/researcher-in-residence/mn_65" target="_blank">Researcher
  in Residence Stipendium</a> als Präsenzbestand zur Verfügung. Darüber hinaus wird ein digitaler Dokumentlieferdienst on-Demand angeboten.</p>
  <p>Die Bibliothek besitzt den Sammelschwerpunkt Figurentheater und Puppenspielkunst. Der Bestand umfasst allgemeine Publikationen zur
    Geschichte und Theorie des Puppen- und Objekttheaters, Theater- und Hochschulveröffentlichungen, Bildbände zum Puppen- und Objekttheater
    der Welt, Kataloge von Masken- und Figurenausstellungen; Bau- und Spielanleitungen; Veröffentlichungen über Puppenspiel in Therapie und
    Unterricht sowie über 1500 Stücke für das Puppentheater. Eine Besonderheit ist der Umfang an internationalen und deutschen Puppentheater-Zeitschriften.</p>
    <p>Zusätzlich zu dem Bestand über Figurentheater, wird auch Literatur zu verwandten Künsten wie der Bildenden und Darstellenden Kunst, neuen Medien und
    kulturpolitischen Schriften angeboten. Im Archiv des dfp werden Fotos, Festival- und Theaterprogramme, Rezensionen und andere Graue Literatur gesammelt.
    Der Schwerpunkt des Archivs liegt hierbei auf der deutschen Figurentheaterszene.</p>

Webseite: <a target="_blank" href="https://www.fidena.de">https://www.fidena.de</a>
</div>
