<?php // Set page title.
$this->headTitle($this->translate('Acquisition Strategy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Acquisition Strategy')?></h2>

<div class="card">
<p>The <i>SIS</i>’s acquisition and collection strategy was developed in collaboration with representatives of theatre and dance studies and aims to cover the following points:
</p>
<ul>
<li>Selected literature in the field which addresses widely diverse research topics (e.g. theatre ethnology, shadow puppetry)</li>
<li>Research literature published outside Europe, the United States and Great Britain</li>
<li>A selection of periodicals unique as a collection in Germany</li>
<li>Providing access to e-book packages issued by publishers in the field for interregional use by academics and others</li>
</ul>

<p>In collaboration with Specialised Information Service in other fields, namely
   <a target="_blank" href="https://www.musiconn.de/">musicology</a>,
    <a target="_blank" href="http://www.arthistoricum.net/">art history</a> and
     <a target="_blank" href="https://katalog.adlr.link/">media and communication studies</a>, we have reached agreements on how to further refine our acquisition strategy.</p>

<p>Here you will find a list of the <i>SIS</i>’s <a href="http://www.ub.uni-frankfurt.de/ne/fachlist.html?print=no&tf=99&monat=00000&fach=930">new acquisitions</a>
at the Frankfurt University Library.</p>
</div>
