<?php // Set page title.
$this->headTitle($this->translate('Acquisition Strategy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Erwerbungsprofil</h2>

<div class="card">
<p>Das Erwerbungs- und Sammlungsprofil des <i>FIDs Darstellende Kunst</i> wurde in Absprache mit Vertretern der Theater- und Tanzwissenschaft erarbeitet und deckt folgende Punkte ab
</p>
<ul>
<li>ausgewählte Fachliteratur, die inhaltlich entlegene Forschungsgebiete (z.B. Theaterethnologie, Schattenspiel) abbildet</li>
<li>Forschungsliteratur, die außerhalb Europas, den USA und GB publiziert wird</li>
<li>eine Auswahl an Zeitschriften mit einem Sammlungs-Alleinstellungsmerkmal in Deutschland</li>
<li>Bereitstellung von e-Book-Paketen fachrelevanter Verlage zur überregionalen Nutzung durch die Fachwelt</li>
</ul>

<p>Absprachen bezüglich eines geschärften Erwerbungsprofils wurden mit inhaltlich nahestehenden
Fachinformationsdiensten der <a target="_blank" href="https://www.bsb-muenchen.de/die-bayerische-staatsbibliothek/abteilungen/musikabteilung/">Musikwissenschaft</a>, der
<a target="_blank" href="http://www.arthistoricum.net/">Kunstgeschichte</a> und der <a target="_blank" href="https://katalog.adlr.link/">Medien-und
Kommunikationswissenschaft</a> getroffen. </p>

<p>Hier finden Sie die <a href="http://www.ub.uni-frankfurt.de/ne/fachlist.html?print=no&tf=99&monat=00000&fach=930">Neuerwerbungen</a> des <i>Fachinformationsdienstes Darstellende Kunst</i> an der
UB Frankfurt.</p>
</div>
