<?php // Set page title.
$this->headTitle($this->translate('Acquisition Strategy') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Erwerbungsprofil</h2>

<div class="card">
  <p>Der Fachinformationsdienst Darstellende Kunst (FID DK) wird seit 2015 von Universitätsbibliothek Johann Christian Senckenberg in Frankfurt am Main betreut.
    Mit dem Angebot des FID-Portal <a href="https://www.performing-arts.eu">www.performing-arts.eu</a> wurde ein komfortabler Zugang zu bislang proprietären
    Datenbeständen und relevantem Forschungs- und Quellenmaterial aufgebaut.</p>
  <p>Der Bestandsaufbau des FID DK erstreckt sich auf gedruckte und elektronische Monographien und Zeitschriften sowie
    <a target="_blank" href="https://darstellende-kunst.fid-lizenzen.de/">FID-Lizenzen</a>. Dabei orientiert sich das Erwerbungs- und Sammlungsprofil an den aktuellen Bedarfen
    bzw. Forschungsschwerpunkten der Fachwelt und wurde gemeinsam mit den Kooperationspartnern, dem Wissenschaftlichen Beirat sowie den Nutzer*innen des FID DK erarbeitet.</p>
  <ul>
    <li><b>Inhaltlich</b> erwirbt der FID DK das gesamte Spektrum der Fachliteratur zur performativer Kunst.</li>
    <li>Die <b>sprachliche</b> und <b>regionale</b> Ausrichtung der Erwerbung im FID DK ist transkulturell geprägt.
      Dabei werden auch Publikationen nicht gängiger europäischer Sprachen abgedeckt, vorausgesetzt es handelt sich inhaltlich um Spezialbedarf der Fachwelt.</li>
    <li>Die <b>Lizenzierung</b> relevanter Volltexte sowie die überregionale Bereitstellung <b>digitaler</b> Primärquellen durch den FID DK
      ergänzen die Grundversorgung an universitären und anderen wissenschaftlichen Bibliotheken.</li>
  </ul>
<p>Das Erwerbungsspektrum des FID DK ist komplementär zu den Profilen verwandter Fachinformationsdienste der
  <a target="_blank" href="https://www.musiconn.de/">Musikwissenschaft</a>, der
  <a target="_blank" href="http://www.arthistoricum.net/">Kunstgeschichte</a> und der
  <a target="_blank" href="https://katalog.adlr.link/">Medien-und Kommunikationswissenschaft</a>.
  Zudem besteht die Möglichkeit einen <a href="<?=$this->url('feedback-form', ['id' => 'AcquisitionRequest'])?>">Kaufvorschlag</a> über das FID-Portal abzusetzen.</p>
<p>Hier finden Sie die <a target="_blank" href="http://www.ub.uni-frankfurt.de/ne/fachlist.html?print=no&tf=99&monat=00000&fach=930">Neuerwerbungen</a> des Fachinformationsdienstes Darstellende Kunst der
Universitätsbibliothek Johann Christian Senckenberg, Frankfurt am Main.</p>
</div>
