<?php // Set page title.
$this->headTitle($this->translate('News') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>News Streaming</h2>
<div class="card">
The <i>SIS Performing Arts</i> has teamed up with the <a target="_blank" href="http://www.theater-wissenschaft.de/">Society for Theatre Studies</a> to
operate the Performing Arts News Service, which evaluates and edits news from the world of theatre and dance studies. The sources
thus provided can be subscribed to via an <a href="<?=$this->url('news-rss')?>">RSS feed</a>. You can integrate this feed into your browser and into
all common e-mail programmes. To set up an RSS feed, please use the Help function.
<br>
<a href="<?=$this->url('news-current')?>">News overview</a>
</div>

<h2>Newsletter</h2>
<div class="card">
Subscribe to our newsletter!<br>
We will send you current information from the <i>SIS</i>, related to research and teaching in theatre and dance studies, three to four times per year.<br>
<br>
<?=$this->flashmessages() ?>
<form accept-charset="UTF-8"  method="POST" action="<?=$this->url('content-page', ['page' => 'news'])?>">

<input type="radio" id="ein" name="action" value="EINTRAGEN">
<label style="vertical-align:middle;" for="ein"><?=$this->transEsc("mail_subscribe");?></label><br>
<input type="radio" id="aus" name="action"  value="AUSTRAGEN">
<label style="vertical-align:middle;" for="aus"><?=$this->transEsc("mail_unsubscribe");?></label><br>

<label for="subscriber"><?=$this->transEsc("mail_address"). ':';?></label><br>
<input id="subscriber" name="email" size="50" maxlength="100" value="" /><br>
<br>
<input class="btn btn-primary" align="left" name="submit" type="submit" value="<?=$this->transEsc('Send')?>">
</form>
<br>
<h4>Newsletter Archive</h4>
<ul>
<li><a href="<?=$this->imageLink('newsletter/2015_1_Newsletter.pdf')?>">Newsletter (2015, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2016_1_Newsletter.pdf')?>">Newsletter (2016, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2016_2_Newsletter.pdf')?>">Newsletter (2016, 2)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2017_1_Newsletter.pdf')?>">Newsletter (2017, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2017_2_Newsletter.pdf')?>">Newsletter (2017, 2)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2018_1_Newsletter.pdf')?>">Newsletter (2018, 1)</a></li>
</ul>
</div>
