<?php // Set page title.
$this->headTitle($this->translate('News') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Newsstream</h2>
<div class="card">
Zusammen mit der <a target="_blank" href="http://www.theater-wissenschaft.de/">Gesellschaft für Theaterwissenschaft</a> betreut der <i>FID Darstellende
Kunst</i> den Profildienst Darstellende Kunst. Fachrelevante Nachrichten aus der Theater-
und Tanzwissenschaft werden redaktionell ausgewertet und steht Ihnen als <a href="<?=$this->url('news-rss')?>">RSS-Feed</a>
zur Verfügung. Sie können diesen in ihrem Browser und in den gängigen Mail-Programmen
integrieren. Die RSS-Reader-Funktion richten Sie mittels der Hilfe-Funktion ein.<br>
<a href="<?=$this->url('news-current')?>">Zur News-Übersicht</a>
</div>

<h2>Newsletter</h2>
<div class="card">
Abonnieren Sie unseren Newsletter!<br>
Wir senden Ihnen drei bis vier Mal im Jahr aktuelle Informationen zum <i>FID</i> bzw. aus der Forschung
und Lehre der Theater- und Tanzwissenschaft zu. <br>
<br>
<?=$this->flashmessages() ?>
<form accept-charset="UTF-8"  method="POST" action="<?=$this->url('content-page', ['page' => 'news'])?>">

<input type="radio" id="ein" name="action" value="EINTRAGEN">
<label style="vertical-align:middle;" for="ein"><?=$this->transEsc("mail_subscribe");?></label><br>
<input type="radio" id="aus" name="action"  value="AUSTRAGEN">
<label style="vertical-align:middle;" for="aus"><?=$this->transEsc("mail_unsubscribe");?></label><br>

<label for="subscriber"><?=$this->transEsc("mail_address"). ':';?></label><br>
<input id="subscriber" name="email" size="50" maxlength="100" value="" /><br>
<br>
<input class="btn btn-primary" align="left" name="submit" type="submit" value="<?=$this->transEsc('Send')?>">
</form>
<br>
<h4>Newsletterarchiv</h4>
<ul>
<li><a href="<?=$this->imageLink('newsletter/2015_1_Newsletter.pdf')?>">Newsletter (2015, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2016_1_Newsletter.pdf')?>">Newsletter (2016, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2016_2_Newsletter.pdf')?>">Newsletter (2016, 2)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2017_1_Newsletter.pdf')?>">Newsletter (2017, 1)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2017_2_Newsletter.pdf')?>">Newsletter (2017, 2)</a></li>
<li><a href="<?=$this->imageLink('newsletter/2018_1_Newsletter.pdf')?>">Newsletter (2018, 1)</a></li>
</ul>
</div>
