<?=$this->headTitle('Statistics');?>
<h2><i class="fa fa-line-chart" aria-hidden="true"></i> <?=$this->transEsc('Statistics')?></h2>
<div class="card">
  Nutzungsstatistiken mit AWStats
  <ul>
    <li><a href="https://www.performing-arts.eu/awstats/awstats.pl?config=fiddk-sessions">Besuche OHNE die Länderstatistik</a></li>
    <li><a href="https://www.performing-arts.eu/awstats/awstats.pl?config=fiddk-countries">NUR Länderstatistik</a>, da alle anderen Statistiken wegen IP-Anonymisierung NICHT "fehlerfrei" sind.</li>
  </ul>
</div>
