<?php // Set page title.
$this->headTitle($this->translate('Search in SIS Portal') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2>Searches Using the <i>SIS Performing Arts</i> Web Portal</h2>

<div class="card">
<p>The <i>SIS Performing Arts</i> web portal offers a wide variety of search functions. It is provided to users as a web portal including all
  media whose index is based on library catalogues, archive indices, databases and other sources focussing specifically on the performing arts.</p>
<p>The list of hits is shown using a <a target="_blank" href="https://vufind-org.github.io/vufind/">VuFind</a> Discovery System with its search engine
program (<a target="_blank" href="https://lucene.apache.org/core/">Apache Lucene</a>).
Using the <a href="<?=$this->url('search-advanced')?>">Advanced Search</a> option, you have access to additional search options. For example, the list of hits can be
sorted by institution, by type of material or by collection.</p>
<p>If your search doesn’t bring useful results or if you need help searching, please feel free to
  contact <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>!
</p>
</div>
