<?php // Set page title.
$this->headTitle($this->translate('Search in SIS Portal') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Search in SIS Portal')?></h2>

<div class="card">
<p>
Das Suchportal des <i>Fachinformationsdienstes Darstellende Kunst</i> bietet Ihnen ein
breites Angebot an Suchfunktionen an. Sie recherchieren in einem medienübergreifenden
Portal, dessen Index auf Bibliothekskatalogen, Archivverzeichnissen, Datenbanken
und anderen Informationsquellen mit einem spezifischen Fokus auf die darstellende
Kunst basiert.</p>
<p>
Die Ausgabe der Trefferliste erfolgt mittels des <a target="_blank" href="https://vufind-org.github.io/vufind/">VuFind</a> Discovery System und der
Suchmaschinentechnologie (<a target="_blank" href="https://lucene.apache.org/core/">Apache Lucene</a>).
In der <a href="<?=$this->url('search-advanced')?>">Erweiterten Suche</a> stehen Ihnen zudem zusätzliche Suchfacetten zur
Verfügung. Die Trefferliste kann beispielsweise nach Institutionen, Materialart und
Sammlung gefiltert werden.
</p>

<p>Sie konnten keine relevanten Suchergebnisse erzielen oder benötigen Hilfe bei Ihrer
Recherche? Wenden Sie sich an <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>!
</p>
</div>
