<?php // Set page title.
$this->headTitle($this->translate('About us') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('About us')?></h2>

<div class="card">
<h4>Aufbau und Entwicklung</h4>
<p>An der <a target="_blank" href="http://www.ub.uni-frankfurt.de">Universitätsbibliothek Johann Christian Senckenberg</a> wird seit 2015 der
<i>Fachinformationsdienst (FID) Darstellende Kunst</i> für die Theater- und Tanzwissenschaft
aufgebaut. Hervorgegangen sind die von der DFG-geförderten <a target="_blank" href="http://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinformationsdienste_wissenschaft/">Fachinformationsdienste
für die Wissenschaft</a> aus dem System der Sondersammelgebiete, die durch dieses
Förderangebot abgelöst werden.
</p>

<p>In enger Abstimmung mit Vertretern der Theater- und Tanzwissenschaft wurden drei
wesentliche Kernaufgaben erarbeitet, die in der ersten Aufbauphase umgesetzt werden:
</p>

<ul>
<li>Entwicklung und Etablierung eines Nachweis- und Rechercheportals, das das gesamte
Spektrum fachwissenschaftlicher Informationsdienstleistungen für die Darstellenden
Künste abbildet.</li>
<li>ein fachspezifischer Bestandsaufbau mit geschärftem Sammlungsprofil</li>
<li>Vernetzung und Kommunikation mit der Fachwelt in Form von Workshops sowie einer
Kooperation mit der <a target="_blank" href="http://www.theater-wissenschaft.de/">Gesellschaft für Theaterwissenschaft</a></li>
</ul>
</div>

<div class="card">
<h4>Schnittstelle</h4>
<p>In der Zusammenführung und Vernetzung von Vertretern aus der Fachwelt mit ihren
Infrastrukturanbietern aus dem Bibliotheks- und Archivbereich bietet der <i>FID
Darstellende Kunst</i> einen einzigartigen Service als Koordinierungs- und Schnittstelle
an. Hierfür entwickelt und koordiniert der <i>FID</i> Workshops, Tagungen und veröffentlicht
Handreichungen und andere Materialien, die den Arbeitsprozess dokumentieren. Ziel des
Projektes ist es, die Position der Fächer der darstellenden Kunst langfristig zu stärken
und aus der Zusammenarbeit heraus weitere gemeinsame Projekte zu entwickeln.
</p>
</div>

<div class="card">
<h4>UB Frankfurt am Main / Abteilung Musik, Theater</h4>
<p>Die Erwerbung und Bereitstellung von Büchern und Materialien zur darstellenden Kunst
haben eine lange Tradition an der Universitätsbibliothek Johann Christian Senckenberg.
Über sechzig Jahre, von 1950 bis 2015, wurde an der UB Frankfurt das <a target="_blank" href="http://www.ub.uni-frankfurt.de/ssg/theater.html">Sondersammelgebiet
Theater und Filmkunst</a> betreut. Darüber hinaus bearbeitete und stellt die <a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html">Abteilung Musik,
Theater</a> wertvolle historische Sammlungen sowie Vor- und Nachlässe zur Nutzung bereit.<br>
Historisches Fundament der Spezialsammlungen zur darstellenden Kunst sind die Buch-
und Zeitschriftenbestände der <i>Rothschildschen Bibliothek</i> sowie die vielfältigen und
umfangreichen Sammlungen des <i>Manskopfschen Musikhistorischen Museums</i>, die nach Ende
des zweiten Weltkrieges in die Bibliothek integriert wurden und zur Gründung der
<i>Abteilung Musik, Theater</i> führten.<br>
Diese Erfahrungen und das Know-how auf dem Gebiet der Erwerbung und Erschließung
von Literatur und Dokumenten über die darstellenden Künste fließen in den neuen
Fachinformationsdienst ein und sind Gewähr für einen nachhaltigen Umgang mit den von
der DFG zur Verfügung gestellten Ressourcen.
</p>
</div>
