<? // Set page title.
$this->headTitle($this->translate('About us') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('About us')?></h2>
<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>

<h4>Aufbau und Entwicklung</h4>

<p>An der <a target="_blank" href="http://www.ub.uni-frankfurt.de">Universitätsbibliothek Johann Christian Senckenberg</a> wird seit 2015 der
<i>Fachinformationsdienst (FID) Darstellende Kunst</i> für die Theater- und Tanzwissenschaft
aufgebaut. Hervorgegangen sind die von der DFG-geförderten <a target="_blank" href="http://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinformationsdienste_wissenschaft/">Fachinformationsdienste
für die Wissenschaft</a> aus dem System der Sondersammelgebiete, die durch dieses
Förderangebot abgelöst werden.
</p>

<p>In enger Abstimmung mit Vertretern der Theater- und Tanzwissenschaft wurden drei
wesentliche Kernaufgaben erarbeitet, die in der ersten Aufbauphase umgesetzt werden:
</p>

<ul>
<li>Entwicklung und Etablierung eines Nachweis- und Rechercheportals, das das gesamte
Spektrum fachwissenschaftlicher Informationsdienstleistungen für die Darstellenden
Künste abbildet.</li>
<li>ein fachspezifischer Bestandsaufbau mit geschärftem Sammlungsprofil</li>
<li>Vernetzung und Kommunikation mit der Fachwelt in Form von Workshops sowie einer
Kooperation mit der <a target="_blank" href="http://www.theater-wissenschaft.de/">Gesellschaft für Theaterwissenschaft</a></li>
</ul>

<h4>Schnittstelle</h4>
<p>In der Zusammenführung und Vernetzung von Vertretern aus der Fachwelt mit ihren
Infrastrukturanbietern aus dem Bibliotheks- und Archivbereich bietet der <i>FID
Darstellende Kunst</i> einen einzigartigen Service als Koordinierungs- und Schnittstelle
an. Hierfür entwickelt und koordiniert der <i>FID</i> Workshops, Tagungen und veröffentlicht
Handreichungen und andere Materialien, die den Arbeitsprozess dokumentieren. Ziel des
Projektes ist es, die Position der Fächer der darstellenden Kunst langfristig zu stärken
und aus der Zusammenarbeit heraus weitere gemeinsame Projekte zu entwickeln.
</p>

<h4>UB Frankfurt am Main / Abteilung Musik, Theater</h4>
<p>Die Erwerbung und Bereitstellung von Büchern und Materialien zur darstellenden Kunst
haben eine lange Tradition an der Universitätsbibliothek Johann Christian Senckenberg.
Über sechzig Jahre, von 1950 bis 2015, wurde an der UB Frankfurt das <a target="_blank" href="http://www.ub.uni-frankfurt.de/ssg/theater.html">Sondersammelgebiet
Theater und Filmkunst</a> betreut. Darüber hinaus bearbeitete und stellt die <a target="_blank" href="http://www.ub.uni-frankfurt.de/musik/musik.html">Abteilung Musik,
Theater</a> wertvolle historische Sammlungen sowie Vor- und Nachlässe zur Nutzung bereit.<br>
Historisches Fundament der Spezialsammlungen zur darstellenden Kunst sind die Buch-
und Zeitschriftenbestände der <i>Rothschildschen Bibliothek</i> sowie die vielfältigen und
umfangreichen Sammlungen des <i>Manskopfschen Musikhistorischen Museums</i>, die nach Ende
des zweiten Weltkrieges in die Bibliothek integriert wurden und zur Gründung der
<i>Abteilung Musik, Theater</i> führten.<br>
Diese Erfahrungen und das Know-how auf dem Gebiet der Erwerbung und Erschließung
von Literatur und Dokumenten über die darstellenden Künste fließen in den neuen
Fachinformationsdienst ein und sind Gewähr für einen nachhaltigen Umgang mit den von
der DFG zur Verfügung gestellten Ressourcen.
</p>

<?
    } else {
?>
<h4>Setup and Development</h4>
<p>In 2015, the <a target="_blank" href="http://www.ub.uni-frankfurt.de/home_en.html">Johann Christian Senckenberg University Library</a> began
  setting up and developing the <i>Specialised Information Service (SIS) Performing Arts</i> for theatre and dance studies.
  The <a target="_blank" href="http://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinformationsdienste_wissenschaft/">Specialised
    Information Services (SIS)</a> subsidised by the German Research Foundation (DFG) originated from
    the Special Subject Collections (Sondersammelgebiete, SSG) which have now been replaced by this subsidised project.
</p>

<p>In close collaboration with experts in theatre and dance studies, three core tasks were defined with the aim
  of completion during the first phase of setup:
</p>

<ul>
<li>Development and setup of a web portal for academic research representing the full range of academic informational services for the performing arts.</li>
<li>A new and more targeted collection of works related to theatre and the performing arts</li>
<li>Networking and communication with experts in the discipline via workshops, and a collaboration
  with the <a target="_blank" href="http://www.theater-wissenschaft.de/">Society for Theatre Studies </a></li>
</ul>

<h4>Interface</h4>
<p>Bringing together and creating a network of people from the field using a library and archive infrastructure, the <i>SIS</i> offers a
  unique interface and coordination service. To this end, the <i>SIS</i> develops and coordinates workshops, conferences and publishes
  written informational texts and other materials which document the work process. The aim of the project is to strengthen the
  position of the performing arts in the long term, and to develop additional collaborations and joint projects.
</p>

<h4>Frankfurt am Main University Library / Department of Music, Theatre</h4>
<p>The Johann Christian Senckenberg University Library has a long history of purchasing
  and making available books and materials on the performing arts. For over 60 years,
  from 1950 to 2016, the University of Frankfurt has managed the Special Subject
  Collections Theatre and Film. In addition, the Department of Music, Theatre has made
  available valuable historical collections and inherited private collections. <br>
  The historical basis for the special collections in the performing arts was
  the <i>Rothschild Library</i>’s existing collection of books and periodicals as well as
  the wide-ranging and comprehensive collection owned by the <i>Manskopf Museum of Musical History</i>,
  which were taken over by the library at the end of the Second World War, leading to
  the founding of the Department of Music, Theatre. This background and the existing
  expertise in the purchasing and cataloguing of literature and documents on the performing
  arts benefit the new IS and ensure that the funds supplied by the German Research Foundation
  (DFG) will be responsibly put to use.
</p>
<?
  }
?>
