<?php // Set page title.
$this->headTitle($this->translate('About us') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>
<h2><?=$this->transEsc('About us')?></h2>

<div class="card">
<h4>Setup and Development</h4>
<p>In 2015, the <a target="_blank" href="https://www.ub.uni-frankfurt.de/home_en.html">Johann Christian Senckenberg University Library</a> began
  setting up and developing the <i>Specialised Information Service (SIS) Performing Arts</i> for theatre and dance studies.
  The <a target="_blank" href="https://www.dfg.de/en/research_funding/programmes/infrastructure/lis/funding_opportunities/informationservice_science/">Specialised
    Information Services (SIS)</a> subsidised by the German Research Foundation (DFG) originated from
    the Special Subject Collections (Sondersammelgebiete, SSG) which have now been replaced by this subsidised project.
</p>

<p>In close collaboration with experts in theatre and dance studies, three core tasks were defined with the aim
  of completion during the first phase of setup:
</p>

<ul>
<li>Development and setup of a web portal for academic research representing the full range of academic informational services for the performing arts.</li>
<li>A new and more targeted collection of works related to theatre and the performing arts</li>
<li>Networking and communication with experts in the discipline via workshops, and a collaboration
  with the <a target="_blank" href="https://www.theater-wissenschaft.de/">Society for Theatre Studies </a></li>
</ul>
</div>

<div class="card">
<h4>Interface</h4>
<p>Bringing together and creating a network of people from the field using a library and archive infrastructure, the <i>SIS</i> offers a
  unique interface and coordination service. To this end, the <i>SIS</i> develops and coordinates workshops, conferences and publishes
  written informational texts and other materials which document the work process. The aim of the project is to strengthen the
  position of the performing arts in the long term, and to develop additional collaborations and joint projects.
</p>
</div>

<div class="card">
<h4>Frankfurt am Main University Library / Department of Music, Theatre</h4>
<p>The Johann Christian Senckenberg University Library has a long history of purchasing
  and making available books and materials on the performing arts. For over 60 years,
  from 1950 to 2016, the University of Frankfurt has managed the Special Subject
  Collections Theatre and Film. In addition, the Department of Music, Theatre has made
  available valuable historical collections and inherited private collections. <br>
  The historical basis for the special collections in the performing arts was
  the <i>Rothschild Library</i>’s existing collection of books and periodicals as well as
  the wide-ranging and comprehensive collection owned by the <i>Manskopf Museum of Musical History</i>,
  which were taken over by the library at the end of the Second World War, leading to
  the founding of the Department of Music, Theatre. This background and the existing
  expertise in the purchasing and cataloguing of literature and documents on the performing
  arts benefit the new IS and ensure that the funds supplied by the German Research Foundation
  (DFG) will be responsibly put to use.
</p>
</div>
