<?php // Set page title.
$this->headTitle($this->translate('Links to from') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('Links to from')?></h2>
<div class="card">
Bei direkten oder indirekten Verweisen auf fremde Webseiten ("Hyperlinks"),
die außerhalb des Verantwortungsbereiches der UB Frankfurt liegen, würde eine
Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem die UB Frankfurt
von den Inhalten Kenntnis hat und es der UB Frankfurt technisch möglich und zumutbar
wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern. Die UB Frankfurt erklärt
hiermit ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den
zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zukünftige Gestaltung, die
Inhalte oder die Urheberschaft der gelinkten/verknüpften Seiten hat die UB Frankfurt keinerlei
Einfluss. Deshalb distanziert sich die UB Frankfurt hiermit ausdrücklich von allen Inhalten aller
gelinkten/verknüpften Seiten, die nach der Linksetzung verändert wurden. Diese Feststellung gilt
für alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie für
Fremdeinträge in von der UB Frankfurt eingerichteten Gästebüchern, Diskussionsforen und
Mailinglisten. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden,
die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein
 der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige
 Veröffentlichung lediglich verweist.
</div>
