<?php $formats = $data->getFormats();
$icon = $this->driver->getRecordIcon();  
$lang = $this->plugin('translate')->getTranslator()->getLocale();?>
<div class="entity">
  <i class="fa fa-solid <?=$icon?> fa-lg recordIcon"></i>
  <span class="small"><?=mb_strtoupper($this->transEsc($this->type))?></span>
</div>
<h4><?=$this->escapeHtml($data->getTitle())?></h4>
<?php if ($formats) :?>
  <?=implode(', ', $formats);?><br>
<?php endif; ?>
<?php if ($this->type == "Record"):
  $places = $data->getGeographicsCon();
  if (!empty($places)): ?>
  <?=$this->render('RecordDriver/DefaultRecord/data-places.phtml', ['data' => $places,'driver' => $this->driver]);?>
  <?php endif; ?>
<?php elseif ($this->type == "Person") :
  $prof = $data->getOccupation();
  $birth = $data->getBirthDate();
  $death = $data->getDeathDate();
  if ($birth || $death) : ?>
    <i class="fa fa-regular fa-calendar"></i>&nbsp;
      <?php if (!$death) : ?>
          <?='* ' . $this->driver->translateDate($birth, 'de')?>
      <?php elseif(!$birth) : ?>
          <?='† ' . $this->driver->translateDate($death, 'de')?>
      <?php else : ?>
          <?='* ' . $this->driver->translateDate($birth, 'de') . ' - † ' . $this->driver->translateDate($death, 'de')?>
      <?php endif; ?>
  <?php endif; ?>
  <?php if ($prof) : ?>
    <p><?=implode(' | ', $prof)?></p>
  <?php endif; ?>
  <?php elseif ($this->type == "Corporation") :
  $orga = $data->getOrgaDomain();?>
  <?php if ($orga) : ?>
    <p><?=implode(' | ', $orga)?></p>
  <?php endif; ?>
  <?php elseif ($this->type == "Event") :
  $places = $data->getEventPlace(); 
  $dates = $data->getEventDate();?>
  <?php if ($places || $dates): ?>
    <?php if ($dates): 
      $normDates = []; ?>
      <?php foreach ($dates as $date): ?>
        <?php $normDates[] = $this->driver->translateDate($date, $lang)?>
      <?php endforeach; ?>
      <div class="resultItemLine">
        <i class="fa fa-regular fa-calendar"></i>&nbsp;<?=$this->escapeHtml(implode(', ', $normDates))?>
      </div>
    <?php endif; ?>
    <?php if ($places): ?>
      <div class="resultItemLine">
        <i class="fa fa-regular fa-map-marker"></i>&nbsp;<?=$this->escapeHtml(implode(', ', $places))?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php if (isset($data->getInstitutions()[0])) :?>
<p><?="[" . $this->transEsc("dprov::" . $data->getInstitutions()[0]) . "]";?></p>
<?php endif; ?>