<h4><?=$this->transEsc('Similar Items')?></h4>
<?php $similarRecords = $this->tab->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <?php $perPage = 4 ?>
  <div id="similar-items-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#similar-items-carousel" data-slide-to="0" class="active"></li>
      <?php for($i = 1;$i < count($similarRecords) / $perPage;$i++): ?>
        <li data-target="#similar-items-carousel" data-slide-to="<?=$i ?>"></li>
      <?php endfor; ?>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <?php foreach ($similarRecords as $index => $data): ?>
          <div class="carousel-item">
            <a class="hover-overlay" href="<?=$this->recordLink()->getUrl($data)?>">
              <?php $thumb = $this->record($data)->getThumbnail('large'); ?>
              <?php if ($thumb) :?>
              <img src="<?=$thumb ?>" alt="<?=$data->getTitle() ?>" title="<?=$data->getTitle() ?>"/>
              <div class="content">
                <div class="contentDarker">
                <?php $formats = $data->getFormats(); ?>
                <b><?=$this->escapeHtml($data->getTitle())?></b>
                <?php if ($data->getFormats()) :?>
                  <p><?=implode(', ',$data->getFormats());?></p>
                <?php endif; ?>
                <p><?=$this->transEsc("Institution") . ': ' . implode(', ',$data->getInstitutions());?></p>
                </div>
              </div>
            <?php else: ?>
            <div class="content">
            </div>
            <p><?=$data->getTitle();?></p>
            <?php if ($data->getFormats()) :?>
              <p><?=implode(', ',$data->getFormats());?></p>
            <?php endif; ?>
            <p><?=$this->transEsc("Institution") . ': ' . implode(', ',$data->getInstitutions());?></p>
          <?php endif; ?>
            </a>
          </div>
          <?php if(($index + 1) % $perPage == 0 && $index < count($similarRecords) - 1): ?>
      </div>
      <div class="item">
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#similar-items-carousel" role="button" data-slide="prev" aria-label="<?=$this->transEsc('Prev') ?>">
      <span class="fa fa-chevron-left glyphicon-chevron-left" title="<?=$this->transEsc('Prev') ?>"></span>
    </a>
    <a class="right carousel-control" href="#similar-items-carousel" role="button" data-slide="next" aria-label="<?=$this->transEsc('Next') ?>">
      <span class="fa fa-chevron-right glyphicon-chevron-right" title="<?=$this->transEsc('Next') ?>"></span>
    </a>
  </div>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
<?php
  $script = <<<JS
var normalizeHeightCount = $('#similar-items-carousel img').length;
function normalizeHeights() {
  if(--normalizeHeightCount > 0) return;
  var tallest = 0;
  var items = $('#similar-items-carousel .hover-overlay');
  items.each(function() { //add heights to array
    if(tallest < $(this).height()) {
      tallest = $(this).height();
    }
  });
  items.css('min-height', (tallest+25) + 'px');
}
$('#similar-items-carousel img').load(normalizeHeights);
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
