<?php $similarRecords = $this->tab->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <?php $perPage = 4;
  $recordType = $this->driver->getRecordType();?>
  <div id="similar-items-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#similar-items-carousel" data-slide-to="0" class="active"></li>
      <?php for($i = 1;$i < count($similarRecords) / $perPage;$i++): ?>
        <li data-target="#similar-items-carousel" data-slide-to="<?=$i ?>"></li>
      <?php endfor; ?>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <?php foreach ($similarRecords as $index => $data): ?>
          <div class="carousel-item <?=$recordType?>Ls">
            <a class="hover-overlay record-cover-link" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($data))?>">
              <?php $thumb = $this->record($data)->getCoverDetails('similar-items', 'small')['html'];?>
              <?php if (strpos($thumb,"Cover/Unavailable") === false) :?>
              <?=$thumb?>
              <div class="content">
                <div class="contentDarker">
                  <?=$this->render("RecordTab/innercarousel.phtml", ['data' => $data,'driver' => $this->driver, 'type' => $recordType] );?>
                </div>
              </div>
            <?php else: ?>
            <div class="contentDarker">
              <?=$this->render("RecordTab/innercarousel.phtml", ['data' => $data,'driver' => $this->driver, 'type' => $recordType] );?>
            </div>
          <?php endif; ?>
            </a>
          </div>
          <?php if(($index + 1) % $perPage == 0 && $index < count($similarRecords) - 1): ?>
      </div>
      <div class="item">
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#similar-items-carousel" role="button" data-slide="prev" aria-label="<?=$this->transEscAttr('Prev') ?>">
      <span class="fa fa-chevron-left glyphicon-chevron-left" title="<?=$this->transEscAttr('Prev') ?>"></span>
    </a>
    <a class="right carousel-control" href="#similar-items-carousel" role="button" data-slide="next" aria-label="<?=$this->transEscAttr('Next') ?>">
      <span class="fa fa-chevron-right glyphicon-chevron-right" title="<?=$this->transEscAttr('Next') ?>"></span>
    </a>
  </div>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
<?php
  $script = $this->config()->ajaxCoversEnabled() ? "loadCovers();\n" : "";
  $script .= <<<JS
var normalizeHeightCount = $('#similar-items-carousel img').length;
function normalizeHeights() {
  if(--normalizeHeightCount > 0) return;
  var tallest = 0;
  var items = $('#similar-items-carousel .hover-overlay');
  items.each(function() { //add heights to array
    if(tallest < $(this).height()) {
      tallest = $(this).height();
    }
  });
  items.css('min-height', (tallest+25) + 'px');
}
$('#similar-items-carousel img').on('load', normalizeHeights);
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
