<?php
    // Set page title.
    $this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());

    $edm = $this->driver->getXML('edm');
?>
<!-- pre><?php //=$edm?></pre -->
<?=\VuFind\XSLT\Processor::process('record-edm.xsl', $edm);?>

<div class="solrTab"><table class="citation table table-striped">
  <?php foreach ($this->driver->getRawData() as $field => $values): ?>
    <tr>
      <th><?=$this->escapeHtml($field)?></th>
      <td>
        <?php foreach ((array)$values as $value): ?>
          <?=$this->escapeHtml(is_array($value) ? print_r($value, true) : $value)?><br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach;?>
</table></div>

<!-- do this with a view helper!
           <pre><?php //=formatXML($values);?></pre>  -->

<!-- Formats the full record field to a structured, highlighted, indented xml string to make debugging easier -->
<?php /**function formatXML($value) {

     $xml = new SimpleXMLElement($value);
     $dom = new DOMDocument("1.0","UTF-8");
     $dom->preserveWhiteSpace = false;
     $dom->formatOutput = true;
     $dom->loadXML($xml->asXML());
     $str = $dom->saveXML($dom->documentElement);
     $str = htmlentities($str, $encoding=ini_get("UTF-8"));
     $tag = '#0000BB';
     $att = '#FF4500';
     $find = array(
        '~(\s[a-z].*?="[a-zA-Z0-9\/#].*?")~', // Highlight attributes
        '~(&lt;(\?|[a-z]|_).*?&gt;)~',                // Highlight opening tag
        '~(&lt;/([a-z]|_).*?&gt;)~');            // Highlight closing tag
     $replace = array(
        '<span style="color:'.$att.';">$1</span>',
        '<span style="color:'.$tag.';">$1</span>',
        '<span style="color:'.$tag.';">$1</span>');
     return preg_replace($find, $replace, $str);
}
*/
?>
