---
# This file contains search specifications used by the authority module; for details
# on the workings of this file, see the comments in searchspecs.yaml.
#-----------------------------------------------------------------------------------

AllFields:
  DismaxFields:
    - heading_keywords^750
    - use_for_keywords^400
    - occupation^100
    - see_also_keywords^100
    - allfields
  DismaxParams:
    - [bq, (record_type:"Personal Name" OR record_type:"Corporate Name" OR record_type:"Event")^500]
    - [bq, (has_thumb:"true")^50]
  DismaxHandler: edismax

Heading:
  DismaxFields:
    - heading_keywords^750
    - use_for_keywords^400
    - see_also_keywords^100
  DismaxParams:
    - [bq, (record_type:"Personal Name" OR record_type:"Corporate Name" OR record_type:"Event")^500]
  DismaxHandler: edismax

MainHeading:
  DismaxFields:
    - heading_keywords^750
  DismaxParams:
    - [bq, (record_type:"Personal Name" OR record_type:"Corporate Name" OR record_type:"Event")^500]
  DismaxHandler: edismax

Agent:
  QueryFields:
    author_id:
      - [onephrase, 100]
    institution_id:
      - [onephrase, ~]

Event:
  QueryFields:
    event_id:
      - [onephrase, 50]

Work:
  QueryFields:
    work_id:
      - [onephrase, 50]
