---
# Listing of configured forms.
#
# Configured forms are listed in the top level 'forms' array and can accessed via the URL:
# /Feedback/Form/<form-id>
#
# The main Feedback form (id: FeedbackSite) can be accessed with a shorter URL /Feedback
#
# Form supports the following options:
#
#   enabled (boolean) Is the form enabled? (default = true)
#   useCaptcha (boolean) Should the form use Captcha validation? Requires the "feedback"
#                        option to be turned on in the config.ini [Captcha] form setting.
#                        (default = true, if Captcha turned on for feedback overall).
#   title (string) Form title (translation key)
#   onlyForLoggedUsers (boolean) Require the user to be logged in to see the form
#                                (default = false)
#   emailSubject (string) Email subject (translation key). (default = email_subject
#                         value from config.ini [Feedback] section, or 'VuFind Feedback')
#                         The subject may contain placeholders (for example %%receiver%%)
#                         that are replaced with submitted form values.
#   recipient
#     name (string)  Recipient name (default = recipient_name setting from config.ini
#                    [Feedback] section)
#     email (string) Recipient email address (default = recipient_email setting from
#                    config.ini [Feedback] section)
#   response (string) Reponse after form submit (translation key)
#   senderInfoRequired (boolean)  Require sender to fill out name and email fields
#
#   help
#     pre (string)  Help text displayed at the beginning of the form (translation key).
#     post (string) Help text displayed at the end of the form (translation key)
#
#   Help texts may contain HTML-formatting.
#
#   fields (array) List of form elements with the following options:
#
#     name (string)      Element name
#     label (string)     Element label (translation key)
#     required (boolean) Is the element required?
#     settings (array)   HTML attributes as key-value pairs, for example:
#       - [class, "custom-css-class another-class"]
#     type (string)      Element type (text|textarea|email|url|select)
#     help (string)      Element help text (translation key)
#
#     And for select elements one of:
#
#     options (array) List of select values (translation keys)
#
#     or
#
#     optionGroups (array) List of option groups with keys:
#       label (string) Group label (translation key)
#       options (array) List of select values (translation keys)
#
#-----------------------------------------------------------------------------------

forms:

  # Main Feedback form

  FeedbackSite:
    title: Send us your feedback!
    enabled: true
    useCaptcha: true
    #recipient:
    #  name: Your Library
    #  email: feedback@myuniversity.edu

    onlyForLoggedUsers: false
    emailSubject: FID Feedback
    response: Thank you for your feedback.
    senderInfoRequired: true

    #help:
    #  pre: feedback_help_pre
    #  post: feedback_help_post

    fields:
      - name: message
        type: textarea
        label: Comments
        required: true
        settings:
        # help: message_help

  # Example for an acquisition request form

  AcquisitionRequest:
    enabled: false
    title: Acquisition Request
    onlyForLoggedUsers: false
    emailSubject: FID Kaufvorschlag
    senderInfoRequired: true
    response: Thank you for your acquisition request.

    #recipient:
    #  name: Your Library
    #  email: feedback@myuniversity.edu

    help:
      pre: acquisition_request_info_pre
      post: acquisition_request_info_post

    fields:
      - name: title
        type: text
        label: Title
        required: true

      - name: author
        type: text
        label: Author
        required: true

      - name: publisher
        type: text
        label: Publisher
        required: true

      - name: isbn/issn
        type: text
        label: ISBN/ISSN
        required: false

      - name: Publication_Place
        type: text
        label: Place of Publication
        required: false

      - name: yearOfPublication
        type: text
        label: Year of Publication
        required: false

      - name: note
        type: textarea
        label: Add a Note
        required: false

  AskArchiveDTK:
    enabled: true
    title: AskAboutObject
    onlyForLoggedUsers: false
    senderInfoRequired: true
    emailSubject: Anfrage zu einem Objekt aus Ihrem Bestand via FID Darstellende Kunst
    response: Thank you for your request.

    recipient:
      name: Deutsches Tanzarchiv Köln
      email: tanzarchiv@sk-kultur.de

    help:
      pre: askArchiveDTK_info_pre

    fields:
      - name: Request
        type: textarea
        label: Your Request
        required: true

      - name: CallNumber
        type: text
        label: edm::dm2e:callNumber
        required: true

  AskArchiveMCB:
    enabled: true
    title: AskAboutObject
    onlyForLoggedUsers: false
    senderInfoRequired: true
    emailSubject: Anfrage zu einem Objekt aus Ihrem Bestand via FID Darstellende Kunst
    response: Thank you for your request.

    recipient:
      name: Christine Henniger
      email: c.henniger@iti-germany.de

    help:
      pre: askArchiveMCB_info_pre

    fields:
      - name: Request
        type: textarea
        label: Your Request
        required: true

      - name: CallNumber
        type: text
        label: edm::dm2e:callNumber
        required: true
