<? $account = $this->auth()->getManager(); ?>
<footer class="hidden-print">
  <hr/>
  <div class="footer-container">
    <div class="footer-column">
      <p><strong><?=$this->transEsc('FID Darstellende Kunst')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'uber'])?>"><?=$this->transEsc('About us')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'beirat'])?>"><?=$this->transEsc('Advisory Board')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'netzwerke'])?>"><?=$this->transEsc('Networks')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'dokumentation'])?>"><?=$this->transEsc('Documentation')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'trailer'])?>"><?=$this->transEsc('Videotrailer')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Subject Service')?></strong></p>
      <ul>
    <li><a href="<?=$this->url('content-page', ['page' => 'kontakt'])?>"><?=$this->transEsc('Contact')?></a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'suchen'])?>"><?=$this->transEsc('Search in SIS Portal')?></a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'faq'])?>"><?=$this->transEsc('FAQ')?></a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>"><?=$this->transEsc('News')?></a>&ensp;<font color="#4f81bd">/</font>&ensp;
      <a target="_blank" href="https://www.facebook.com/Fachinformationsdienst-Darstellende-Kunst-1740840716155321" aria-label="Facebook Link">
        <span class="fa fa-facebook-square"></span>
      </a>
    </li>
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('news-list', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-newspaper-o" aria-hidden="true"></i> <?=$this->transEsc("News")?></a>
        </li>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
        </li>
        <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
          <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Internal")?></a>
          <? else: ?>
            <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Internal")?></a>
          <? endif; ?>
        </li>
      <? endif; ?>
    </ul>
    </div>
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Librarian Services')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'contents'])?>"><?=$this->transEsc('Online Contents')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'neuerwerb'])?>"><?=$this->transEsc('Acquisition Strategy')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'fernleihe'])?>"><?=$this->transEsc('Interlibrary Loan')?></a></li>
        <li><a href="<?=$this->url('feedback-form', ['id' => 'AcquisitionRequest'])?>"><?=$this->transEsc('Acquisition Request')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Legal Information')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'impressum'])?>"><?=$this->transEsc('Website Information')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'copyright'])?>"><?=$this->transEsc('Copyright')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'verweise'])?>"><?=$this->transEsc('Links to from')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'datenschutz'])?>"><?=$this->transEsc('Data Privacy')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'haftung'])?>"><?=$this->transEsc('Liability Information')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <div class="poweredby bottom_logos">
        <?=$this->layout()->poweredBy ?>
      </div>
    </div>
  </div>
</footer>
