<div class="flex-statistics card">
  <div><i class="fa fa-chevron-circle-right" aria-hidden="true" style="padding-right: 10px;"></i> <?=$this->transEsc("Researching")?></div>
<?php foreach ($this->statistics as $key => $amount): ?>
  <?php if ($key == "Objects") {
          $url = $this->url('search-results');
          //$icon = "fa-cubes";
        } elseif ($key == "Agents") {
          $url = $this->url('agentsearch-results');
          //$icon = "fa-users";
        } else {
          $url = $this->url('eventsearch-results');
          //$icon = "fa-star-o";
        }?>
  <div>
    <a href="<?=$url?>">
      <?=$this->localizedNumber($amount) . ' ' . $this->transEsc($key)?>
    </a>
  </div>
<?php endforeach; ?>
<div>
  <!--hr>
<i class="fa fa-chevron-circle-right" aria-hidden="true" style="padding-right: 10px;"></i> <a href="<?//=$this->url("showcase-home")?>">
  <?//=$this->transEsc("Explore")?>
</a -->
</div>
</div>
