<div class="flex-statistics card">
  <h4><?=$this->transEsc("Researching")?><hr id="research"/></h4>
  <div class="flexing">
    <?php foreach ($this->statistics as $key => $amount): ?>
      <?php if ($key == "Resources") {
          $url = $this->url('search-results');
          $pic = "Resources.jpg";
        } elseif ($key == "Agents") {
          $url = $this->url('agentsearch-results');
          $pic = "Agents.jpg";
        } elseif ($key == "Events") {
          $url = $this->url('eventsearch-results');
          $pic = "Events.jpg";
        } else {
          $url = $this->url('worksearch-results');
          $pic = "Works.jpg";
        } ?>
        <figure class="showcase">
          <a href="<?=$url?>">
            <img src="<?=$this->imageLink($pic)?>">
          </a>
          <figcaption><h5><?=$this->transEsc($key)?><br/>
            <a href="<?=$url?>"><?=$this->localizedNumber($amount) . " " . $this->transEsc("Datensätze")?></a></h5>
          </figcaption>
        </figure>
    <?php endforeach; ?>
  </div>
</div>
