<?php
    $resources = $this->driver->getRelatedResources();
if ($resources) :
    $type = $this->driver->getRecordType();
    if ($data > 1) : ?>
    <ul class="list-group related">
        <?php foreach ($resources as $record) : ?>
            <?php $formats = $record->getFormats(); ?>
      <li class="list-group-item"><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record))?>"><?=$this->escapeHtml($record->getTitle())?></a>
            <?php if ($formats) :
                ?><?=" ("?><?=$this->escapeHtml(implode(" | ", $formats) . ")")?><?php
            endif; ?></li>
        <?php endforeach; ?>
  </ul>
  <a href="<?=$this->escapeHtmlAttr($this->url('search-results') . '?lookfor=' . $this->driver->getUniqueID() . '&type=' . $type)?>"><?=$this->translate("RelatedEntityHits", ['%%count%%' => $this->localizedNumber($data)]);?></a>
    <?php else : ?>
            <?php $record = $resources[0];
            $formats = $record->getFormats(); ?>
    <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record))?>"><?=$this->escapeHtml($record->getTitle())?></a>
            <?php if ($formats) :
                ?><?=" ("?><?=$this->escapeHtml(implode(" | ", $formats) . ")")?><?php
            endif; ?>
    <?php endif; ?>
<?php endif; ?>
