<img src="<?=$this->imageLink("icons/geo-alt.svg")?>" alt="Icon" width="16" height="16"></img><span property="location">
<?php $size = sizeof($data);
      $keys = array_keys($data);
foreach ($data as $key => $field): ?>
  <?php if ($key != 'undefinedPlace'): ?>
    <?=$this->escapeHtml(implode(' | ', $field)) . ' (' . $this->transEsc($key) .')'?>
  <?php else: ?>
    <?=$this->escapeHtml(implode(' | ', $field))?>
  <?php endif; ?>
  <?php if (array_search($key, $keys) < $size - 1): ?> ; <?php endif; ?>
<?php endforeach; ?></span>
