<div class="links">
  <h4 property="context"><?=$this->transEsc("More Links")?></h4>
  <table class="table">
    <caption class="sr-only"><?=$this->transEsc('More Links')?></caption>
    <?php foreach ($data as $k => $current):
    if (isset($current['id']) && isset($current['collection'])) :
    $abbr = $current['collection']['abbr'] ?? '';
    $name = $current['collection']['name'] ?? '';
    $icon = $current['collection']['icon'] ?? '';?>
      <tr><th><?php if ($icon): ?>
        <img class="external-icon" src="<?=$icon?>" alt="<?=$abbr?>"/>
        <?php elseif ($current['collection']['id'] == "http://isni.org"): ?>
          <span class="sr-only"><?="ISNI"?></span>
        <?php else: ?>
          <?=$abbr?>
        <?php endif;?></th>
        <td><a href="<?=$current['id']?>" target="_blank">
        <?php if ($name): ?>
          <?=$name?>
        <?php else: ?>
          <?=$current['id']?>
        <?php endif;?>
      </a></td></tr>
  <?php endif;
endforeach; ?>
  </table>
</div>