<?php
    $events = $this->driver->getRelatedEvents(); 
    if ($events):
      $type = $this->driver->getRecordType();
      $lang = $this->plugin('translate')->getTranslator()->getLocale();
      if ($data > 1): ?>
    <ul class="list-group related">
    <?php foreach ($events as $record): ?>
      <?php $eventDate = $record->getEventDate();?>
      <li class="list-group-item"><a href="<?=$this->recordLinker()->getUrl($record)?>"><?=$record->getTitle()?></a>
      <?php if (isset($eventDate[0])):?><?="("?><i class="fa fa-regular fa-calendar"></i>&nbsp;<?=$this->driver->translateDate($eventDate[0], $lang) . ")"?><?php endif;?></li>
    <?php endforeach; ?>
  </ul>
  <a href="<?=$this->url('eventsearch-results') . '?lookfor=' . $this->driver->getUniqueID() . '&type=' . $type?>"><?=$this->translate("RelatedEntityHits", ['%%count%%' => $this->localizedNumber($data)]);?></a>
  <?php else: ?>
    <?php $record = $events[0];
          $eventDate = $record->getEventDate();
          $lang = $this->plugin('translate')->getTranslator()->getLocale();?>
    <a href="<?=$this->recordLinker()->getUrl($record)?>"><?=$record->getTitle()?></a>
    <?php if (isset($eventDate[0])):?><?="("?><i class="fa fa-regular fa-calendar"></i>&nbsp;<?=$this->driver->translateDate($eventDate[0], $lang) . ")"?><?php endif;?></li>
  <?php endif; ?>
<?php endif; ?>