<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="media-body">

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $eventFields = $formatter->getData($driver, $formatter->getDefaults('event'));
    ?>
    <?php if (!empty($eventFields)): ?>
      <div class="card">
        <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>
        <table class="table table-striped">
          <caption class="sr-only"><?=$this->transEsc('Event Details')?></caption>
          <?php foreach ($eventFields as $current): ?>
            <tr><th><?=$this->transEsc('edm::' .$current['label'])?>:</th><td><?=$current['value']?></td></tr>
          <?php endforeach; ?>
        </table>
      </div>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>

  <?php //echo $this->render('search/results.phtml'); ?>
</div>
