<?php
  if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Akademie der Künste Berlin');
?>
<h2>Akademie der Künste Berlin</h2>
<p><a href="https://www.adk.de/de/akademie/index.htm"
    target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>
<p>Gegründet im Jahre 1696 gehört die Akademie der Künste in Berlin zu den ältesten
    europäischen Kulturinstituten. Sie ist eine internationale Gemeinschaft von Künstlern
    und hat in ihren sechs Sektionen Bildende Kunst, Baukunst, Musik, Literatur,
    Darstellende Kunst, Film- und Medienkunst derzeit insgesamt 418 Mitglieder. Mit über
    1200 Künstlernachlässen und einer umfangreichen Kunstsammlung und Bibliothek zählt
    das Archiv der Akademie zu den bedeutendsten interdisziplinären Archiven zur Kunst des 20. Jahrhunderts.</p>
<?php } else {
  // Set page title
  $this->headTitle('Academy of Arts Berlin');
?>
<h2>Academy of Arts Berlin</h2>
<p><a href="https://www.adk.de/de/akademie/index.htm"
    target="_blank" data-lightbox-ignore>Direct to the website</a></p>
<p>The Akademie der Künste in Berlin, founded in 1696, is one of the oldest cultural institutes
  in Europe. It is an international community of artists and has a current total of 418 members
  in its six Sections (Visual Arts, Architecture, Music, Literature, Performing Arts, Film and
  Media Arts). With over 1,200 bequests by artists and an extensive art collection and library,
  the Archive is one of the most important interdisciplinary archives of 20th century art.</p>
<?php } ?>
