<?php
  if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Adam Matthew Digital');
?>
<h2>Adam Matthew Digital</h2>
<img src="<?=$this->imageLink('logos_s/amd.png')?>" alt="Adam Matthew Digital"/>
<br/><br/>
<p><a href="https://www.amdigital.co.uk"
    target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>
<p></p>
<?php } else {
  // Set page title
  $this->headTitle('Adam Matthew Digital');
?>
<h2>Adam Matthew Digital</h2>
<img src="<?=$this->imageLink('logos_s/amd.png')?>" alt="Adam Matthew Digital"/>
<br/><br/>
<p><a href="https://www.amdigital.co.uk"
    target="_blank" data-lightbox-ignore>Direct to the website</a></p>
<p></p>
<?php } ?>
