<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Alexander Street Press: Drama Package und Theatre on Video');
?>
<h2>Alexander Street Press: Drama Package und Theatre on Video</h2>
<p><a href="http://alexanderstreet.com/" target="_blank" data-lightbox-ignore>Direkt zum Verlag</a></p>
<p>Der Datenbankanbieter Alexander Street Press bietet ein breites Portfolio Volltextdatenbanken und
    Videokollektionen für die Theater- und Tanzwissenschaft an.
    <p>Der FID Darstellende Kunst hat folgende sieben Datenbanken lizenziert:
        <ul>
            <li><b>Asian American Drama</b> vereint mehr als 250 Stücke, zusammen mit biographischen, Produktions- und Theaterinformationen.</li>
            <li><b>Black Drama: Second Edition</b> enthält die Volltexte von 1.462 Dramen von 233 Autoren aus Nordamerika, dem
                englischsprachigen Afrika und der Karibik von der Mitte des 19. Jahrhunderts bis heute.</li>
            <li><b>Latino Literature</b> enthält mehr als 100.000 Seiten Poesie, Kurzgeschichten, Romane und mehr als 450 Theaterstücke.</li>
            <li><b>North American Theatre Online</b> deckt Themen zum Theater von der Kolonialzeit bis zur Gegenwart ab.</li>
            <li><b>North American Women's Drama</b> enthält 1500 Stücke, die von US-Amerikanerinnen oder Kanadierinnen verfasst wurden.</li>
            <li><b>North American Indian Drama</b> enthält mehr als 240 Werke zur dramatischen Literatur nordamerikanischer
                Autoren indigener Abstammung des 20. Jahrhunderts.</li>
            <li><b>Theatre in Video</b> ist ein Online-Service mit Live-Aufnahmen und filmischen Adaptionen von über 250 Aufführungen
                vorwiegend englischsprachiger Theaterstücke im Streaming-Video-Verfahren.</li>
        </ul>
    </p>
</p>
<?php } else {
      // Set page title
      $this->headTitle('Alexander Street Press: Drama Package and Theatre on Video');
  ?>
<h2>Alexander Street Press: Drama Package and Theatre on Video</h2>
<p><a href="http://alexanderstreet.com/" target="_blank" data-lightbox-ignore>Go directly to their website</a></p>
<p>The database provider Alexander Street Press offers a broad portfolio of full text databases and video resources on theatre and dance studies.
    <p>The SIS Performing Arts has obtained licences for the following seven databases:
      <ul>
          <li><b>Asian American Drama</b> brings together more than 250 plays along with biographical, production-related and theatre information.</li>
          <li><b>Black Drama: Second Edition</b> includes the entire script of 1,462 plays by 233 playwrights from North America, English-speaking African
            nations and the Caribbean, dating from the mid-19th century to today. </li>
          <li><b>Latino Literature</b> comprises more than 100,000 pages of poetry, short stories, novels, and more than 450 plays.</li>
          <li><b>North American Theatre Online</b> covers theatre-related topics from the colonial period to the present.</li>
          <li><b>North American Women's Drama</b> comprises 1500 plays by American and Canadian women.</li>
          <li><b>North American Indian Drama</b> boasts more than 240 works of 20th century dramatic literature by indigenous North American authors.</li>
          <li><b>Theatre in Video</b> is an online service with streamed live recordings and film adaptations of over 250 performances
            of plays, mostly in English.</li>
      </ul>
    </p>
</p>
<?php } ?>
