<?php
  if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('BASE - Bielefeld Academic Search Engine');
?>
<h2>BASE - Bielefeld Academic Search Engine</h2>
<img src="<?=$this->imageLink('logos_s/base.gif')?>" alt="BASE - Bielefeld Academic Search Engine"/>
<br/><br/>
<p><a href="https://www.base-search.net"
    target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>
<p>BASE (Bielefeld Academic Search Engine) ist eine der weltweit größten Suchmaschinen
  für wissenschaftliche Web-Dokumente. Bei etwa 60% der in BASE indexierten Dokumente
  sind die Volltexte frei zugänglich (Open Access). Betreiberin der Suchmaschine BASE
  ist die Universitätsbibliothek Bielefeld.</p>
<p>Indexiert werden die Metadaten von Datenlieferanten mit wissenschaftlichen Inhalten
  – Zeitschriften, Repositorien, Digitale Sammlungen etc. –, die über eine
  OAI-Schnittstelle verfügen und die Metadaten über OAI-PMH bereitstellen.</p>
<?php } else {
  // Set page title
  $this->headTitle('BASE - Bielefeld Academic Search Engine');
?>
<h2>BASE - Bielefeld Academic Search Engine</h2>
<img src="<?=$this->imageLink('logos_s/base.gif')?>" alt="BASE - Bielefeld Academic Search Engine"/>
<br/><br/>
<p><a href="https://www.base-search.net"
    target="_blank" data-lightbox-ignore>Direct to the website</a></p>
<p>BASE (Bielefeld Academic Search Engine) is one of the world's most voluminous search
  engines especially for academic web resources. You can access the full texts of about
  60% of the indexed documents for free (Open Access). BASE is operated by Bielefeld
  University Library.</p>
<p>The metadata are indexing of all kinds of academically relevant resources – journals,
  institutional repositories, digital collections etc. – which provide an OAI interface
  and use OAI-PMH for providing their contents.</p>
<?php } ?>
