<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Deutsches Tanzfilminstitut Bremen');
?>
<h2>Deutsches Tanzfilminstitut Bremen</h2>
<img src="<?=$this->imageLink('logos_s/tfb.jpg')?>" alt="Deutsches Tanzfilminstitut"/><br/><br/>
<p><a href="http://www.deutsches-tanzfilminstitut.de/?cat=222"
    target="_blank" data-lightbox-ignore>Zur Webseite des Archives</a></p>
<p>Das Deutsche Tanzfilminstitut Bremen ist ein nationales Archiv zur Sammlung,
  Aufbereitung und Produktion von audiovisuellen Tanzdokumenten. 1988 als
  Nonprofit-Organisation gegründet, unterstützt das Institut durch die Bereitstellung
  der gesammelten Materialien die Arbeit von Choreografen, Tanzkompanien, Theatern,
  Fachjournalisten und Fernsehanstalten und hilft bei der Produktion,  Restauration
  und Digitalisierung von Tanzvideos und Filmen.</p>
<?php } else {
  // Set page title
  $this->headTitle('German Institute of Dance Film Bremen');
?>
  <h2>German Institute of Dance Film Bremen</h2>
  <img src="<?=$this->imageLink('logos_s/tfb.jpg')?>" alt="Deutsches Tanzfilminstitut"/><br/><br/>
  <p><a href="http://www.deutsches-tanzfilminstitut.de/?cat=222"
      target="_blank" data-lightbox-ignore>To the archive website</a></p>
  <p>The German Institute of Dance Video in Bremen is a national archive that collects,
    processes and produces audiovisual recordings of dance performances. It was founded
    in 1988 as a non-profit organisation with the aim of supporting the work of
    choreographers, dance companies, theatres, television production companies and
    journalists in the field by providing access to its video archive. It also assists
    in the production, restoration and digitalisation of dance videos and films.</p>
<?php } ?>
