<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Deutsches Theatermuseum München, Bibliothek');
?>
<h2>Deutsches Theatermuseum München, Bibliothek</h2>
<p><a href="http://www.bayerische-bibliographie.de/avanti/dtm/opac.html"
    target="_blank" data-lightbox-ignore>Direkt zum Katalog</a></p>
<p>Das Deutsche Theatermuseum in München hat es sich zur Aufgabe gemacht, die Theatergeschichte Münchens,
    Bayerns und Deutschlands möglichst lückenlos zu bewahren und zu dokumentieren. Darüber hinaus sammelt es -
    gemäß seiner Tradition - alle erreichbaren Objekte zur Weltgeschichte des Theaters, insbesondere, wenn sie
    Einflüsse auf oder durch das deutsche Theater belegen. Das Theatermuseum besitzt zudem die weltweit
    umfangreichste Sammlung an Theaterfotografien. Insgesamt bewahrt es unter anderem ca. 250.000 grafische Blätter,
    ca. 500.000 Autographen und ca. 4,3 Millionen Theaterfotografien. Die Bibliothek des Deutschen Theatermuseums
    ist eine Präsenzbibliothek und nimmt nur eingeschränkt am Fernleihverkehr teil.
    Eine umfassende Recherche ist daher nur vor Ort möglich.</p>
<?php } else {
  // Set page title
  $this->headTitle('German Theatre Museum Munich, Library');
?>
<h2>German Theatre Museum Munich, Library</h2>
<p><a href="http://www.bayerische-bibliographie.de/avanti/dtm/opac.html"
    target="_blank" data-lightbox-ignore>To the catalogue</a></p>
<p>The German Theatre Museum not only preserves the history of theatre in Munich, but in Germany as a whole.
  In addition, it documents the ties linking the theatre and cultural scenes in the various European countries.
  All in all, the collection consists of approximately 250,000 pages of graphics and approximately 500,000 original
  manuscripts. The German Theatre Museum houses an extensive collection of original graphics from the Baroque period,
  and the most valuable of the 130,000 volumes date back to the Renaissance. In addition, the Museum owns the largest
  collection of theatre photographs worldwide, including some dating from the dawn of the photographic era.</p>
<?php } ?>
