<?php
 if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    // Set page title
    $this->headTitle('Digitalisierungsprojekt Düsseldorfer Theaterzettel der Universitäts- und Landesbibliothek Düsseldorf');
?>

<h2>Digitalisierungsprojekt Düsseldorfer Theaterzettel der Universitäts- und Landesbibliothek Düsseldorf</h2>
<img src="<?=$this->imageLink('logos_s/dtz.png')?>" alt="Düsseldorfer Theaterzettel - ULB Düsseldorf"/><br/><br/>
<p><a href="http://digital.ub.uni-duesseldorf.de/theaterzettel" target="_blank" data-lightbox-ignore>Direkt zur Einrichtung</a></p>

<p>In dem von der Deutschen Forschungsgemeinschaft (DFG) geförderten Projekt werden ca. 13.000 Theaterzettel
    von Düsseldorfer Theatern aus den Jahren 1802 bis 1918 erschlossen und digitalisiert.
    Besonderes Augenmerk wird auf die Erschließungstiefe gelegt: So werden nicht nur die Regisseure,
    Autoren und Komponisten der jeweiligen Stücke in den Katalog aufgenommen, sondern nach Möglichkeit
    auch alle weiteren beteiligten Personen, vor allem die Schauspielerinnen und Schauspieler.</p>

<?php } else {
      // Set page title
      $this->headTitle('Digital Collections: Düsseldorf Playbills at the University and North Rhine-Westphalian State Library Düsseldorf');
?>

<h2>Digital Collections: Düsseldorf Playbills at the University and North Rhine-Westphalian State Library Düsseldorf</h2>
<img src="<?=$this->imageLink('logos_s/dtz.png')?>" alt="Düsseldorfer Theaterzettel - ULB Düsseldorf"/><br/><br/>
<p><a href="http://digital.ub.uni-duesseldorf.de/theaterzettel" target="_blank" data-lightbox-ignore>Direct to the website</a></p>

<p>The Düsseldorf Playbills (1902-1918) site is part of the Digital Collections funded by the German Research
    Foundation (DFG). Over 13.000 playbills are digitised and catalogued at the University and North Rhine-Westphalian
    State Library Düsseldorf (ULB). The content of the digitalised sources are indexed: title, stage director, author,
    composer, and others person like actor and actress.</p>

<?php } ?>
