<div id="logo-carousel" class="carousel slide" data-ride="carousel" data-interval="2000">
  <div class="carousel-inner">
      <div class="item active">
        <div class="col-md-3">
          <div class="carousel-item">
          <a href="https://www.adk.de/" target="_blank">
            <img src="<?=$this->imageLink('logos_s/adk.jpg')?>" alt="Akademie der Künste"/>
          </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://alexanderstreet.com/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/asp.jpg')?>" alt="Alexander Street Press"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.fidena.de" target="_blank">
          <img src="<?=$this->imageLink('logos_s/fdn.png')?>" alt="Deutsches Forum für Figurentheater und Puppenspielkunst"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.deutsches-tanzarchiv.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/dtk.png')?>" alt="Deutsches Tanzarchiv"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://www.deutsches-tanzfilminstitut.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/tfb.jpg')?>" alt="Deutsches Tanzfilminstitut"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://www.deutschestheatermuseum.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/dtm.png')?>" alt="Deutsches Theatermuseum"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://www.donjuanarchiv.at/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/kom.png')?>" alt="Don Juan Archiv Wien"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.ulb.hhu.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/dtz.png')?>" alt="Düsseldorfer Theaterzettel - ULB Düsseldorf"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.geisteswissenschaften.fu-berlin.de/we07/index.html" target="_blank">
            <img src="<?=$this->imageLink('logos_s/tsb.png')?>" alt="Freie Universität Berlin - Institut für Theaterwissenschaften"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.theater-wissenschaft.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/gtw.png')?>" alt="Gesellschaft für Theaterwissenschaften"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.ub.uni-frankfurt.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/fub.png')?>" alt="Goethe Universität Frankfurt"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://www.mimecentrum.iti-germany.de/de/mediathek" target="_blank">
          <img src="<?=$this->imageLink('logos_s/mcb.png')?>" alt="Mediathek für Theater und Tanz"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://sapa.swiss/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/sts.jpg')?>" alt="SAPA"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://tanzarchiv-leipzig.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/tal.jpg')?>" alt="Tanzarchiv Leipzig"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://tanzfonds.de/" target="_blank">
            <img src="<?=$this->imageLink('logos_s/tfe.png')?>" alt="Tanzfonds Erbe"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://teso.chadwyck.co.uk/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/tes.png')?>" alt="Teatro Espagnol del Siglo Oro"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://www.thesid.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/thesid.png')?>" alt="TheSiD - Theatersammlungen in Deutschland"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="http://tws.phil-fak.uni-koeln.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/slw.jpg')?>" alt="Theaterwissenschaftliche Sammlung Köln"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.duesseldorf.de/theatermuseum/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/tmd.jpg')?>" alt="Theatermuseum Düsseldorf"/>
        </a>
        </div>
        </div>
      </div>
      <div class="item">
        <div class="col-md-3">
          <div class="carousel-item">
        <a href="https://www.transcript-verlag.de/" target="_blank">
          <img src="<?=$this->imageLink('logos_s/tra.png')?>" alt="Transcript Verlag"/>
        </a>
        </div>
        </div>
      </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#logo-carousel" role="button" data-slide="prev" aria-label="<?=$this->transEsc('Prev') ?>">
    <span class="fa fa-chevron-left glyphicon-chevron-left" title="<?=$this->transEsc('Prev') ?>"></span>
  </a>
  <a class="right carousel-control" href="#logo-carousel" role="button" data-slide="next" aria-label="<?=$this->transEsc('Next') ?>">
    <span class="fa fa-chevron-right glyphicon-chevron-right" title="<?=$this->transEsc('Next') ?>"></span>
  </a>

</div>

<?php
  $script = <<<JS
$('.carousel .item').each(function(){
  var next = $(this).next();
  if (!next.length) {
    next = $(this).siblings(':first');
  }
  next.children(':first-child').clone().appendTo($(this));

  var next2 = next.next()
  if (next2.length>0) {
    next2.children(':first-child').clone().appendTo($(this));
  }
  else {
  	$(this).siblings(':first').children(':first-child').clone().appendTo($(this));
  }
  if (next2.next().length>0) {
    next2.next().children(':first-child').clone().appendTo($(this));
  }
  else {
    if (next2.length>0) {
    $(this).siblings(':first').children(':first-child').clone().appendTo($(this));
    } else {
    $(this).siblings(':nth-child(2)').children(':first-child').clone().appendTo($(this));
  }
  }
  });
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
