<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
  // Set page title
  $this->headTitle('Internationales Theaterinstitut Deutschland, Mime Centrum Berlin, Mediathek für Tanz und Theater');
?>
<h2>Internationales Theaterinstitut Deutschland, Mime Centrum Berlin, Mediathek für Tanz und Theater</h2>
<p><a href="http://archiv.mimecentrum.de/"
    target="_blank" data-lightbox-ignore>Direkt zum Katalog</a></p>
<p>Das MIME CENTRUM BERLIN (MCB) ist ein offener Ort der Produktion, Weiterbildung,
  der Kooperation und des internationalen Austausches. Es versteht sich als eine
  moderne Serviceinstitution für Theaterakteure sowie für die Vermittlung von
  Kunstprozeß und Öffentlichkeit.</p>
<p>Die Dokumentationsbasis des MCB besteht aus der Mediathek für Tanz und Theater.
  Die DOKUMENTATIONEN zu Künstlern, Gruppen, Festivals, zu europäischen Theaterschulen
  und Ausbildungszentren bilden einen Fundus an INFORMATIONEN und Kontakten. Darüber
  hinaus spielen VIDEOPRODUKTIONEN als Referenz- und Analysemedium für Bewegungstheater
  eine wichtige Rolle. Das Videostudio realisiert die Aufzeichnung von ausgewählten
  Aufführungen, erstellt Schnittfassungen und Dokumentationen.</p>
<?php } else {
    // Set page title
    $this->headTitle('Federal Republic of Germany Centre of the International Theatre Institute e.V., Mime Centrum Berlin,  Dance and Theatre Media Library');
?>
<h2>Federal Republic of Germany Centre of the International Theatre Institute e.V., Mime Centrum Berlin,  Dance and Theatre Media Library</h2>
<p><a href="http://archiv.mimecentrum.de/"
      target="_blank" data-lightbox-ignore>Direct to the catalogue</a></p>
<p>The Mime Centrum Berlin is a public institute dedicated to documentation, information, research and hands-on work in dance and theatre.</p>
<p>The Media Library, with its more than 8,000 videos, books and periodicals, provides visitors a view into developments in the performing
  arts at a national and international level. The media library’s collection of documents and other items is being continually expanded
  by its own documentations, acquisition of collections, and items on loan from artists, festivals and theatres.</p>
<?php } ?>
