<?php
 if ($this->plugin('translate')->getTranslator()->getLocale() == 'de') {
    // Set page title
    $this->headTitle('Medici.tv');
?>

<h2>Medici.tv</h2>
<img src="<?=$this->imageLink('logos_s/thulb.png')?>" alt="Medici.tv"/><br/><br/>
<p><a href="http://www.medici.tv" target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>

<p>Medici.tv wird häufig als einer der führenden Sender für klassische Musik bezeichnet. Die Plattform überträgt jährlich mehr als 150 Live-Auftritte internationaler Künstlerinnen, Künstler und Ensembles. Darüber hinaus umfasst ihr Video-on-Demand-Katalog über 4 000 Titel, darunter Konzerte, Opern, Ballette, Dokumentationen, Meisterkurse und Jazzprogramme, die in HD gestreamt werden können.</p>
<?php } else {
      // Set page title
      $this->headTitle('Medici.tv');
?>

<h2>Medici.tv</h2>
<img src="<?=$this->imageLink('logos_s/thulb.png')?>" alt="Medici.tv"/><br/><br/>
<p><a href="http://www.medici.tv" target="_blank" data-lightbox-ignore>Website</a></p>

<p>Medici.tv wird häufig als einer der führenden Sender für klassische Musik bezeichnet. Die Plattform überträgt jährlich mehr als 150 Live-Auftritte internationaler Künstlerinnen, Künstler und Ensembles. Darüber hinaus umfasst ihr Video-on-Demand-Katalog über 4 000 Titel, darunter Konzerte, Opern, Ballette, Dokumentationen, Meisterkurse und Jazzprogramme, die in HD gestreamt werden können.
<?php } ?>
