<?php
 if ($this->plugin('translate')->getTranslator()->getLocale() == 'de') {
    // Set page title
    $this->headTitle('Medici.tv');
?>

<h2>Medici.tv</h2>
<img src="<?=$this->imageLink('logos_s/medicitv.png')?>" alt="Medici.tv"/><br/><br/>
<p><a href="http://www.medici.tv" target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>

<p>Medici.tv wird häufig als einer der führenden Sender für klassische Musik bezeichnet. Die Plattform überträgt jährlich mehr als 150 Live-Auftritte internationaler Künstlerinnen, Künstler und Ensembles. Darüber hinaus umfasst ihr Video-on-Demand-Katalog über 4 000 Titel, darunter Konzerte, Opern, Ballette, Dokumentationen, Meisterkurse und Jazzprogramme, die in HD gestreamt werden können.</p>
<?php } else {
      // Set page title
      $this->headTitle('Medici.tv');
?>

<h2>Medici.tv</h2>
<img src="<?=$this->imageLink('logos_s/medicitv.png')?>" alt="Medici.tv"/><br/><br/>
<p><a href="http://www.medici.tv" target="_blank" data-lightbox-ignore>Website</a></p>

<p>Medici.tv is often referred to as one of the leading channels for classical music. The platform broadcasts more than 150 live performances by international artists and ensembles every year. In addition, its video-on-demand catalog includes over 4,000 titles, including concerts, operas, ballets, documentaries, master classes and jazz programs that can be streamed in HD.
<?php } ?>
