<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Theaterwissenschaftliche Sammlung der Universität zu Köln');
?>
<h2>Theaterwissenschaftliche Sammlung der Universität zu Köln</h2>
<img src="<?=$this->imageLink('logos_s/slw.jpg')?>" alt="Theaterwissenschaftliche Sammlung Köln"/><br/><br/>
<p><a href="http://tws.phil-fak.uni-koeln.de/"
    target="_blank" data-lightbox-ignore>Direkt zum Katalog</a></p>
<p>Die Theaterwissenschaftliche Sammlung der Universität zu Köln ist ein internationales
  Dokumentations- und Forschungszentrum für Theatergeschichte und Medienkultur.
  chwerpunkte der Sammlung liegen zum einen auf der deutschsprachigen Theaterkultur –
  mit einem umfassenden Kritiken- und Fotoarchiv, das durch eine vielseitige graphische
  Sammlung ergänzt wird –, zum anderen auf den Theater- und Medienformen unterschiedlicher
  Kulturen und Epochen. Die Bibliothek ist Teil der gemeinsamen Fachbibliothek Medienkultur
  und Theater. Sie ist eine reine Präsenzbibliothek; ein Entleihen der Bücher ist nicht möglich.
  Der vollständige Bestand der Bibliothek der Theaterwissenschaftlichen Sammlung kann über
  den <a href="http://www.ub.uni-koeln.de/" target="_blank" data-lightbox-ignore>Online-Katalog der Universitäts-
  und Stadtbibliothek</a> recherchiert werden (bitte den Suchmodus "Uni" auswählen). Bei Bedarf
  lässt sich der Teilbestand bis Erwerbungsjahr 2012 über den
  <a href="http://www.ub.uni-koeln.de/bibliotheken/38_429/" target="_blank" data-lightbox-ignore>Online-Katalog der
    Fachbibliothek Medienkultur und Theater</a> recherchieren.</p>
<?php } else {
  // Set page title //
  $this->headTitle('Theatre Collection of the University of Cologne');
?>
  <h2>Theatre Collection of the University of Cologne</h2>
  <img src="<?=$this->imageLink('logos_s/slw.jpg')?>" alt="Theaterwissenschaftliche Sammlung Köln"/><br/><br/>
  <p><a href="http://tws.phil-fak.uni-koeln.de/"
        target="_blank" data-lightbox-ignore>To the Catalogue</a></p>
    <p>The Theatre Collection of the University of Cologne is an international documentation
      and research centre for theatre history and media culture. The focal points of the Collection
      are German-speaking theatre culture – with an extensive archive of reviews and photos,
      supplemented by a wide-ranging collection of graphic art – and the approaches to theatre
      and media in various cultures and epochs.</p>
<?php } ?>
