<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Stiftung SAPA, Schweizer Archiv der Darstellenden Künste');
?>
<h2>Stiftung SAPA, Schweizer Archiv der Darstellenden Künste</h2>
<img src="<?=$this->imageLink('logos_s/sts.jpg')?>" alt="SAPA"/><br/><br/>
<p><a href="https://sapa.swiss/"
    target="_blank" data-lightbox-ignore>Zur SAPA-Webseite</a></p>
<p>Die Stiftung SAPA sammelt, dokumentiert, archiviert und verbreitet in der Schweiz
   produzierte, mit der Schweiz in Verbindung stehende oder für sie bedeutende
   Werke aus dem Bereich der Darstellenden Künste (Tanz, Theater, Performance).
   All diese Dokumente bilden die Helvetica der Darstellenden Künste. SAPA ist am
   1. Januar 2017 aus dem Zusammenschluss zweier Institutionen entstanden:
   <ul>
     <li>Das Schweizerische Tanzarchiv, das wiederum aus dem Zusammenschluss der
       Archives suisses de la danse (gegründet 1993 von Jean Pierre Pastori in
       Lausanne) und der mediathek tanz.ch (gegründet 2005 von Wolfgang Brunner
       und Eva Richterich in Zürich) hervorgegangen ist.</li>
     <li>Die Schweizerische Theatersammlung STS, gegründet 1927 als Privatinitiative
       von Theaterakteuren, wurde 1978 in eine Stiftung (mit drei öffentlichen
       Stiftungsträgern und der Schweizerischen Gesellschaft für Theaterkultur
       SGTK als Mitstifterin) überführt.</li>
  </ul>
</p>
<?php } else {
  // Set page title
  $this->headTitle('Stiftung SAPA, Schweizer Archiv der Darstellenden Künste');
?>
<h2>Stiftung SAPA, Schweizer Archiv der Darstellenden Künste</h2>
<img src="<?=$this->imageLink('logos_s/sts.jpg')?>" alt="SAPA"/><br/><br/>
<p><a href="https://sapa.swiss/"
    target="_blank" data-lightbox-ignore>Zur SAPA-Webseite</a></p>
<p>Die Stiftung SAPA sammelt, dokumentiert, archiviert und verbreitet in der Schweiz
   produzierte, mit der Schweiz in Verbindung stehende oder für sie bedeutende
   Werke aus dem Bereich der Darstellenden Künste (Tanz, Theater, Performance).
   All diese Dokumente bilden die Helvetica der Darstellenden Künste. SAPA ist am
   1. Januar 2017 aus dem Zusammenschluss zweier Institutionen entstanden:
   <ul>
     <li>Das Schweizerische Tanzarchiv, das wiederum aus dem Zusammenschluss der
       Archives suisses de la danse (gegründet 1993 von Jean Pierre Pastori in
       Lausanne) und der mediathek tanz.ch (gegründet 2005 von Wolfgang Brunner
       und Eva Richterich in Zürich) hervorgegangen ist.</li>
     <li>Die Schweizerische Theatersammlung STS, gegründet 1927 als Privatinitiative
       von Theaterakteuren, wurde 1978 in eine Stiftung (mit drei öffentlichen
       Stiftungsträgern und der Schweizerischen Gesellschaft für Theaterkultur
       SGTK als Mitstifterin) überführt.</li>
  </ul>
</p>
<?php } ?>
