<?php
 $this->headTitle('Teatro Español del Siglo de Oro'); ?>
 <h2>Teatro Español del Siglo de Oro</h2>
 <img src="<?=$this->imageLink('logos_s/tes.png')?>" alt="Teatro Espagnol del Siglo Oro"/><br/><br/>
 <?php
 if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>
<p><a href="http://www.nationallizenzen.de/angebote/nlproduct.2006-03-10.7433818373"
  target="_blank" data-lightbox-ignore>Direkt zum Produkt</a></p>
<p>850 Werke der 16 prominentesten Vertreter, u. a. Cervantes, Lope de Vega, Calderón de la Barca,
  des spanischen goldenen Zeitalters sind als Volltext recherchierbar. Die Periode zwischen 1500 und
  1700 bildet den Höhepunkt des intellektuellen und künstlerischen Schaffens in Spanien. Für die Auswahl
  zeichnet ein internationales Herausgeberteam verantwortlich.<br />
  Die Suche kann wahlweise über eine englische oder eine spanische Oberfläche erfolgen.
</p>
<?php } else {
?>
<p><a href="http://teso.chadwyck.co.uk/english/home/home"
  target="_blank" data-lightbox-ignore>Direct to this website</a></p>
<p>The full-text database Teatro Español del Siglo de Oro indexes 850 dramatic works from the 16 most
  prominent representatives of the Spanish Golden Age, including Gil Vicente, Tirso de Molina, Lope de
  Vega, Calderon de la Barca. The selection of the pieces is the responsibility of an international
  team of editors. The Siglo de Oro period between 1500 and 1700 was the high point of intellectual
  and artistic achievements in Spain. <br />
  The search can be made optionally via an English or a Spanish web interface.
</p>
<?php } ?>
