<?php
if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Freie Universität Berlin, Institut für Theaterwissenschaft, Theaterhistorische Sammlungen');
?>
<h2>Freie Universität Berlin, Institut für Theaterwissenschaft, Theaterhistorische Sammlungen</h2>
<img src="<?=$this->imageLink('logos_s/tsb.png')?>" alt="Freie Universität Berlin - Institut für Theaterwissenschaften"/><br/><br/>
<p><a href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/Sammlung_Walter_Unruh/IfT_Sammlungen_Bestandsliste_20160406.pdf"
    target="_blank" data-lightbox-ignore>Zur Bestandsübersicht</a></p>
<p>In den Theaterhistorischen Sammlungen des Instituts stehen dazu umfangreiche Archivbestände
  insbesondere zur Berliner Theatergeschichte des 18. Bis 21. Jahrhunderts zur Verfügung
  (Schwerpunkt um 1900 bis 1950er Jahre). Sie sind grundsätzlich öffentlich zugänglich und
  werden unentgeltlich im Bereich der Institutsbibliothek zur Einsichtnahme vorgelegt.
  Mit der Theaterhistorischen Sammlung Walter Unruh  betreut das Institut eine der größten
  ehemaligen Privatsammlungen dieser Art. Darüber hinaus finden sich im Institutsarchiv weitere
  bedeutende Künstlernachlässe sowie umfangreiche Foto-, Theaterzettel- und Presseausschnittsammlungen.
  Insbesondere die Programmheftsammlung wird aktiv weitergeführt.</p>
<?php } else {
    // Set page title
    $this->headTitle('Freie Universität Berlin, Institute of Theatre Studies, Historical Theatre Collections');
?>
<h2>Freie Universität Berlin, Institute of Theatre Studies, Historical Theatre Collections</h2>
<img src="<?=$this->imageLink('logos_s/tsb.png')?>" alt="Freie Universität Berlin - Institut für Theaterwissenschaften"/><br/><br/>
<p><a href="http://www.geisteswissenschaften.fu-berlin.de/we07/institut/sammlungen/index.html"
    target="_blank" data-lightbox-ignore>To the collection</a></p>
<p>The Institute’s Historical Theatre Collections include extensive archives, especially on the history of theatre
  in Berlin from the 18th to the 21st centuries, with a focus on the period from 1900-1950. They are all open to
  the public and as part of the Institute’s library, can be viewed free of charge. The Institute houses the Walter
  Unruh Historical Theatre Collection, on permanent loan from the Federal State of Berlin, one of the largest
  formerly private collections of this kind. In addition, the Institute’s archive contains additional significant
  inherited private collections left to it by artists, and extensive collections of photos, theatre bulletins and
  press excerpts. Special attention is being paid to continuing the collection of theatre programmes.</p>
<?php } ?>
