<?php
  if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
    $this->headTitle('Verbund deutscher Tanzarchive (VdT)');
?>
<h2>Verbund deutscher Tanzarchive (VdT)</h2>
<p><a href="http://www.tanzarchive.de/"
    target="_blank" data-lightbox-ignore>Direkt zur Webseite</a></p>
<p>Zum Verbund Deutscher Tanzarchive (VdT) haben sich 2007 die fünf führenden Institutionen – das Archiv Darstellende Kunst
  der Akademie der Künste Berlin, das Deutsche Tanzarchiv Köln, das Deutsche Tanzfilminstitut Bremen, das Mime Centrum Berlin
  und das Tanzarchiv Leipzig e.V.  – zur Bestanderhaltung und Erschließung von Quellen und Dokumenten zur Entwicklungs- und
  Aufführungsgeschichte der Kunstform Tanz in Deutschland nominell zusammengeschlossen.</p>
<?php } else {
  // Set page title
  $this->headTitle('Association of German Dance Archives (VDT)');
?>
<h2>Association of German Dance Archives (VDT)</h2>
<p><a href="http://www.tanzarchive.de/"
    target="_blank" data-lightbox-ignore>Go directly to their website</a></p>
<p>The Association of German Dance Archives (VDT) is the umbrella organisation created in 2007 by the five leading institutions
   – the Performing Arts Archive of the Berlin Academy of the Arts, the German Dance Archive in Cologne, the German Dance Film
   Institute in Bremen, the Leipzig Dance Archive, and the Berlin Mime Centrum – with the aim of preserving and cataloguing
   documents and other sources related to the history and development of dance as an art form in Germany. </p>
<?php } ?>
