<? // Set page title.
$this->headTitle($this->translate('FAQ') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<h2><?=$this->transEsc('FAQ')?></h2>

<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>

<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Wofür steht der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <p>Der an der UB Frankfurt beheimatete <i>Fachinformationsdienst (FID) Darstellende Kunst</i> bietet der Fachwelt der Theater- und
  Tanzwissenschaft einen effektiven und freien Zugang zu Informationsressourcen.<br/>
  Die Kernaufgaben des <i>FID</i>s sind der Ausbaus der Informationsinfrastruktur sowie die Entwicklung und Betreuung des
  <i>FID</i>-Portals <a href="http://www.performing-arts.eu/">http://www.performing-arts.eu/</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Wie finanziert sich der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <p>Das Projekt zum Aufbau eines <i>Fachinformationsdienstes Darstellende Kunst</i> wird seit 2015 von der Deutschen Forschungsgemeinschaft im Rahmen
  des Förderprogramms <a target="_blank" href="http://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinformationsdienste_wissenschaft/">Fachinformationsdienste für die Wissenschaft</a> finanziert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          An wen richtet sich der <i>FID Darstellende Kunst</i>?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <p><img src="<?=$this->imageLink('PA_Audience.png')?>" alt="Fokus" width="25%"/>
      Die inhaltliche Ausrichtung des <i>FIDs Darstellende Kunst</i> orientiert sich an Forschung und Lehre in all ihren Ausprägungen:
      <ul>
        <li>Theaterwissenschaft: Theater, Musiktheater</li>
        <li>Tanzwissenschaft: Tanz, Bühnentanz, performance studies, Bewegungswissenschaften</li>
        <li>Kleinkunst / popular theatre and entertainment: Zirkus, Varieté, Kabarett, Comedy</li>
        <li>Paratheatrale Grenzbereiche: Performance-Kunst, Aktions-und Medienkunst.</li>
      </ul>
       Die bereitgestellten Fachinformationen orientieren sich an den Ansprüchen und Wünschen eines wissenschaftlichen Publikums.
       Damit bietet der <i>FID Darstellende Kunst</i> für Studium, Forschung und Lehre ein breites Spektrum an Fachinformationen, bündelt diese
       und stellt sie in übersichtlicher Form bereit. Das <i>FID</i>-Portal steht allerdings allen interessierten Nutzern und Wissenschaftler*Innen
       anderer Fachrichtungen offen. Allerdings erhalten diese Nutzergruppen keinen Zugriff auf die lizenzierten Produkte im Portal.</p>
</div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Welche Ressourcen sind im <i>FID</i>-Portal lizenziert und wer hat darauf Zugriff?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <p>Der Fachinformationsdienst Darstellende Kunst hat in Kooperation mit dem <a target="_blank" href="http://www.fid-lizenzen.de">Kompetenzzentrum für Lizenzierung</a> folgende Lizenzpakete erworben:
      <ul>
        <li>die e-Book Frontlist Titel 2015-2017 des <a href="http://www.transcript-verlag.de/reihen/kulturwissenschaften/theater-und-tanzwissenschaft/">transcript-Verlags</a></li>
        <li/><a target="_blank" href="http://alexanderstreet.com/products/alexander-street-drama-package">Drama-Package</a> und
        <a target="_blank" href="https://alexanderstreet.com/products/theatre-video-series">Theatre in Video</a> vom Alexander-Street-Press Verlag.</li>
      </ul>
      Die Metadaten stehen frei im <i>FID</i>-Portal http://www.performing-arts.eu/ zur Verfügung. Autorisierte bzw. registrierte Nutzer können die
      Volltexte bzw. Videos direkt im Portal ansehen. Folgender Nutzerkreis ist zur Nutzung berechtigt:
      <ul>
        <li>Wissenschaftliches Personal</li>
        <li>Fachspezifische Institutionen (Archive, Sammlungen, Museen)</li>
        <li>Mitglieder der Fachgesellschaften für Theaterwissenschaft, Theatergeschichte und Tanzforschung.</li>
      </ul>
    </p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Wie kann ich mich für die Nutzung der <i>FID</i>-Lizenzen registrieren?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <p>Die Registrierung zur Nutzung der FID-Lizenzen erfolgt über unseren Kooperationspartner
      dem <a target="_blank" href="http://www.fid-lizenzen.de">Kompetenzzentrum für Lizenzierung</a>. Auf der eigenen
      <a target="_blank" href="http://darstellende-kunst.fid-lizenzen.de">FID Darstellende Kunst Webseite</a> können Sie anmelden. Hier
      erfahren Sie auch, welche Produkte lizenziert wurden und welcher Nutzerkreis darauf Zugriff hat.<br/>
      Eine <a target="_blank" href="<?=$this->imageLink('Anleitung_zur_Anmeldung_beim_FID.pdf')?>">Anleitung</a> für die Registrierung haben wir
      für Sie erstellt. Nach der Anmeldung können Sie sich im FID-Portal <a href="http://performing-arts.eu/">http://www.performing-arts.eu/</a> als
      authetifizierter Nutzer anmelden und erhalten Zugriff auf die lizenzierten Produkte.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Kann ich Kaufvorschläge einbringen?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <p>Ja. Um das gesamte Spektrum an Fachliteratur für die darstellende Kunst abdecken zu können, benötigen wir Ihre Mithilfe!
        Sie haben einen Titel nicht im <i>FID</i>-Portal gefunden oder Sie können Ihren Wunschtitel nicht über die Fernleihe beziehen?
        Melden Sie Ihren <a href="<?=$this->url('spages-kaufvorschlag')?>">Kaufvorschlag</a> an die <i>FID</i>-Redaktion. Wir werden Ihren Vorschlag prüfen und Ihnen eine Rückmeldung geben.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSeven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
          Warum läuft www.performing-arts.eu als Beta-Version?
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
      <p>Im Juni 2016 ist das <i>FID</i>-Portal nach über einem Jahr intensiver Arbeit für die Nutzung freigeschaltet wurden.
        Nicht alle Datenpakete konnten bis dahin adäquat eingepflegt und bearbeitet werden. Im Hintergrund wird weiter Aufbauarbeit geleistet,
        während für Sie unser „Schaufenster“ <a href="http://performing-arts.eu/">www.performing-arts.eu</a> sichtbar ist. Daher die Kennzeichnung der Betaphase.
      Sollten Sie Fehler entdecken oder Anregungen zur Umsetzung haben, melden Sie diese bitte an <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEight">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          Wie kann ich in www.performing-arts.eu recherchieren?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <p>Über den Suchschlitz auf der der Startseite des <i>FID</i>-Portals recherchieren Sie in allen verfügbaren Quellen. Die Ergebnisse sind in einem Relevanzranking sortiert.
      Sie können Ihre Suche nach bestimmten Suchkriterien eingrenzen, hierfür stehen Ihnen Facetten (Datengeber, Materialart, Sammlungen/Reihe, Datum)  zur Verfügung.
      Mit der <a href="<?=$this->url('search-advanced')?>">Erweiterten Suche</a> können Sie von Beginn an gezielt nach einem Autor, Titel und beispielsweise in einer bestimmten Sprache suchen.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingNine">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingNine" aria-expanded="false" aria-controls="collapseheadingNine">
          Was bedeuten die Suchfacetten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingNine">
      <p>Mithilfe von Facetten können Sie die Ergebnisliste Ihrer Suche nach bestimmten Kriterien eingrenzen, z. B. Datengeber, Materialart,
        Datum. Sie können mehrere Facetten kombinieren und auch wieder abwählen, um Ihre Suche zu verfeinern.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTen" aria-expanded="false" aria-controls="collapseheadingTen">
          Welche Angebote finde ich im <i>FID</i>-Portal www.performing-arts.eu?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTen">
      <p>Im <i>FID</i>-Portal wurden Datenquellen indexiert, die das gesamte Spektrum fachrelevanter Informationsversorgung abdecken:
      <ul>
        <li>fachspezifische Bibliothekskataloge wie der Fachausschnitt Theater und Tanz der Universitätsbibliothek Frankfurt/Main oder Bibliotheksbestände
          der Akademie der Künste Berlin</li>
        <li>Archivbestände der wichtigsten deutschsprachigen Sammlungen für die darstellende Kunst</li>
        <li><i>FID</i>-Lizenzen elektronischer Volltexte und e-Books für autorisierte Nutzer</li>
        <li><a target="_blank" href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/">erschlossene Inhaltsverzeichnisse</a> relevanter Zeitschriften aus dem Bereich
          Theater, Tanz und Performancekunst; hier ist eine Recherche auf Artikelebene (Überschrift und Autor) möglich</li>
        <li>Digitalisate und Volltexte aus Digitalisierungsprojekten wie dem DFG-Projekt
          <a target="_blank" href="http://digital.ub.uni-duesseldorf.de/theaterzettel">Düsseldorfer Theaterzettel</a> der Universitäts-
        und Landesbibliothek Düsseldorf oder dem <a target="_blank" href="http://www.donjuanarchiv.at/historischer-bestand/komplex-mauerbach.htmlKomplex">Mauerbach
          des Don Juan Archivs Wien</a></li>
     </ul>
     Das Angebot des <i>FID</i>-Portals wird sukzessive erweitert und die bereits indexierten Quellen regelmäßig aktualisiert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEleven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingEleven" aria-expanded="false" aria-controls="collapseheadingEleven">
         Was sind Metadaten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingEleven">
      <p>Metadaten sind (strukturierte) Daten, die eine Ressource, eine Entität, ein Objekt oder andere Daten beschreiben.<br/>
      Metadaten liefern also Informationen über Eigenschaften eines Dokuments, wie z.B. seinen Verfasser, den Zeitpunkt
      der Entstehung des Dokuments, das technische Format, Inhalt, Rechteinhaber usw. Diese Metadaten sind eine Sammlung von
      definierten Elementen, die dem Auffinden, der Verwendung sowie der Verwaltung einer Ressource, einer Entität etc. dienen.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwelve">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTwelve" aria-expanded="false" aria-controls="collapseheadingTwelve">
         Kann ich einen RSS-Feed zur Ergebnisliste meiner Suche einrichten?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTwelve">
      <p>Ja. Am unteren Ende der Ergbnisliste gehen Sie den Link '<i class="fa fa-bell"></i> RSS-Feed abonnieren'.<br/>
      Die Suche wird Ihnen nun als Feed bereitgestellt und regelmäßig in Ihrem Feedleser aktualisiert.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThirteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingThirteen" aria-expanded="false" aria-controls="collapseheadingThirteen">
          Werden mir ähnliche Treffer zu meiner Suche angezeigt?
        </a>
      </h4>
    </div>
    <div id="collapseheadingThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingThirteen">
      <p>Ja. Ihnen werden auf der Einzeltrefferebene ähnliche Einträge angezeigt. Hierfür gehen Sie zum unteren Ende des Datensatzes. Unter dem
        Reiter „Ähnliche Einträge“ werden diese aufgeführt.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFourteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFourteen" aria-expanded="false" aria-controls="collapseheadingFourteen">
          Wie kann ich mich über die aktuellen Entwicklungen des <i>FIDs Darstellende Kunst</i> informieren?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFourteen">
      <p>Abonnieren Sie den kostenlosen <a href="<?=$this->url('spages-news')?>">Newsletter des <i>FIDs Darstellende Kunst</i></a>.
      Sie werden in regelmäßigen Abständen über Neuerungen und Wissenswertes informiert.</p>
      <p>Gemeinsam mit der Gesellschaft für Theaterwissenschaft betreut der <i>FID Darstellende Kunst</i> den Profildienst Darstellende Kunst. Fachrelevante
      Nachrichten aus der Theater- und Tanzwissenschaft werden redaktionell ausgewertet und können als <a href="<?=$this->url('news-rss')?>">RSS-Feed</a> abonniert werden.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFifteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFifteen" aria-expanded="false" aria-controls="collapseheadingFifteen">
          An wen kann ich mich bei Fragen und Anregungen wenden?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFifteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFifteen">
      <p>Sie können uns Ihre Anregungen und Wünsche unter der E-Mail-Adresse <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a> schreiben
        oder über den <a href="http://performing-arts.eu/Feedback">Feedback-Button</a>
        im Portal <a href="http://performing-arts.eu/">www.performing-arts.eu</a> nutzen.</p>

      <p>Für spezifische Fragen hilft Ihnen das <i>FID</i>-Team auch gerne persönlich weiter:</p>

      <b>Projektleitung und Koordination</b><br/>
      Franziska Voß<br/>
      Tel: 069/ 798-39574<br/>
      <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Technische Realisierung</b><br/>
      Julia Beck<br/>
      Tel: 069/ 798-39387<br/>
      <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Grafische Gestaltung</b><br/>
      Axel Dörrer<br/>
      Tel: 069/ 798-39213<br/>
      <a href="mailto:a.doerrer@ub.uni-frankfurt.de">a.doerrer@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Bibliothekarische Dienstleistung</b><br/>
      Erzsébet Trautz<br/>
      Tel: 069/ 798-39244<br/>
      <a href="mailto:e.trautz@ub.uni-frankfurt.de">e.trautz@ub.uni-frankfurt.de</a>
    </div>
  </div>
</div>

<?
    } else {
?>

<div id="accordion" role="tablist" aria-multiselectable="false">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          What does <i>SIS Performing Arts</i> stand for?
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <p>The <i>Specialised Information Service (SIS) Performing Arts</i> is based at the University Library Frankfurt
        and offers people in the field of theatre and dance studies an effective and free way to access sources
        of information. The <i>SIS</i>’s main tasks are to expand the informational infrastructure and to develop and
        maintain the <i>SIS</i> web portal <a href="http://www.performing-arts.eu/">http://www.performing-arts.eu/</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Where does funding for the <i>SIS Performing Arts</i> come from?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <p>Since 2015, the project tasked with setting up the <i>Specialised Information Service (SIS) Performing Arts</i> has been funded by the
        German Research Foundation (DFG) as part of its
        <a target="_blank" href="http://www.dfg.de/en/research_funding/programmes/infrastructure/lis/funding_opportunities/informationservice_science/index.htmlSpecialised">Information Services Programme</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          For whom is the <i>SIS Performing Arts</i> intended?
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <p><img src="<?=$this->imageLink('PA_Audience_en.png')?>" alt="Focus" width="25%"/></p>
      <p>The aim of the <i>SIS Performing Arts</i>  is to fulfil the needs of researchers and those involved in university teaching in a variety of related fields:
      <ul>
        <li>Theatre studies: theatre, music theatre</li>
        <li>Dance theory: dance, concert dance, performance studies, kinesiology</li>
        <li>Popular theatre and entertainment: circus, variety shows, cabaret, comedy</li>
        <li>Niche topics related to theatre: performance art, happenings and media art.</li>
      </ul>
       The specialised information provided aims to fulfil the needs and wishes of the academic usership. To this end, the <i>SIS Performing Arts</i> offers a
       wide variety of information on the field for the purposes of students, researchers and university teaching, has brought the various sources together
       and provided a user-friendly platform for their use. The <i>SIS</i> web portal is also available to interested users and academics from other disciplines;
       however, these user groups do not have access to the licenced products within the web portal.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Which resources presented by the <i>SIS</i> web portal are licenced and who has access to them?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <p>The <i>Specialised Information Service (SIS) Performing Arts</i> has purchased the following licence packages
        with the help of the <a target="_blank" href="http://www.fid-lizenzen.de">Center of Competence for Licensing</a>:
      <ul>
        <li>the e-book frontlist title series (2015-2017) from <a target="_blank" href="http://www.transcript-verlag.de/en">transcript-Verlag</a></li>
        <li/>the <a target="_blank" href="http://alexanderstreet.com/products/alexander-street-drama-package">Drama Package</a> and
        <a target="_blank" href="https://alexanderstreet.com/products/theatre-video-series">Theatre in Video</a> packages from Alexander-Street-Press Verlag.</li>
      </ul>
      The metadata are freely accessible on the <i>SIS</i> web portal: <a href="http://www.performing-arts.eu/">www.performing-arts.eu/</a>.  Authorised and/or registered users can view the texts and videos in their entirety using the web portal.
      The following users are authorised:
      <ul>
        <li>Academic personnel and staff</li>
        <li>Institutions in the field (archives, collections, museums)</li>
        <li>Members of the professional associations for theatre studies, theatre history and dance research.</li>
      </ul>
    </p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          How can I register to use the <i>SIS</i> licences?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <p>To use the <i>SIS</i> licences, please register with our project partner, the <a target="_blank" href="http://www.fid-lizenzen.de">Center of Competence for Licensing</a>.
        You can register on the <a target="_blank" href="http://darstellende-kunst.fid-lizenzen.de"><i>SIS Performing Arts</i> website</a>. Here you will find information on which products are
        licenced and which users have access to them.<br/>
        We have put together a set of <a target="_blank" href="<?=$this->imageLink('Anleitung_zur_Anmeldung_beim_FID.pdf')?>">instructions</a> for registration.
        After registering, you can sign onto the <i>SIS</i> web portal <a href="http://performing-arts.eu/">http://www.performing-arts.eu/</a> as an authorised
        user and will have access to the licenced products.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Can I make suggestions for new acquisitions?
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <p>Yes.  To do justice to the entire range of literature in the field of performing arts, we need your help! If you have been unable to find a
        title you need using the <i>SIS</i> web portal, or if you are unable to receive it using the interlibrary loan programme, please send your
        <a href="<?=$this->url('spages-kaufvorschlag')?>">suggestion for a new acquisition</a> to the <i>SIS</i> editorial team. We will
        evaluate your suggestion and send you a response.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSeven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
        Why is the website www.performing-arts.eu only available as a beta version?
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
      <p>After over one year of intensive work, the <i>SIS</i> web portal was made accessible for use in June 2016. Unfortunately it was not possible
        for us to include and adequately process all data packages by that point. We are continuing the work of setting up the site, and in the
        meantime you can view the <a href="http://performing-arts.eu/">www.performing-arts.eu</a> page as a kind of showcase window. This is why the site is designated as a beta version.
        If you find any mistakes or if you have suggestions on the website setup and/or management, please send them to
        <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEight">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          How can I use the www.performing-arts.eu site for research?
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEight">
      <p>Using the search function on the main page of the <i>SIS</i> web portal, you can search the contents of all available sources. The results are sorted
        according to relevance. You can limit your search according to specific criteria using the various search options provided (data provider, type of
        material, collection/series, date). An <a href="<?=$this->url('search-advanced')?>">Advanced Search</a> allows you to tailor your search from
        the beginning, e.g. to look for a certain author or title in a specific language.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingNine">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingNine" aria-expanded="false" aria-controls="collapseheadingNine">
          What does faceted search mean?
        </a>
      </h4>
    </div>
    <div id="collapseheadingNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingNine">
      <p>Using the faceted search, you can limit the list of search results according to specific criteria, e.g. data provider, type of material,
        and date. You can combine several options and de-select them to further tailor your search.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTen" aria-expanded="false" aria-controls="collapseheadingTen">
          What is available on the <i>SIS</i> web portal www.performing-arts.eu?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTen">
      <p>The <i>SIS</i> portal has been used to index data sources which address the entire range of information relevant to the field:
        <ul>
          <li>Specialised library catalogues such as the University Frankfurt Library`s theatre and dance section or the Academy of the Arts Berlin Library’s collection</li>
          <li>The most significant archived books and other items housed by collections in the German-speaking world in the field of performing arts</li>
          <li>Licences obtained by the <i>SIS</i> to full texts and e-books, with access for authorised users</li>
          <li><a target="_blank" href="http://orsprod.rz.uni-frankfurt.de/LNG=DU/DB=3.6/">Catalogued tables of contents</a> of relevant periodicals in the field of
            theatre, dance and performance art, with the opportunity to search for specific articles (title and author)</li>
          <li>Digitalised materials and full texts from digitalisation projects such as the German Research Foundation-funded
            <a target="_blank" href="http://digital.ub.uni-duesseldorf.de/theaterzettel?lang=en">Theatre Playbills Project</a> by the Düsseldorf University
            and State Library, or the <a target="_blank" href="http://www.donjuanarchiv.at/historischer-bestand/komplex-mauerbach.htmlKomplex">Komplex Mauerbach by the Don Juan Archive Vienna</a></li>
        </ul>
        The sources available on the <i>SIS</i> web portal are being continually added to, and the sources already indexed are regularly updated.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEleven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingEleven" aria-expanded="false" aria-controls="collapseheadingEleven">
         What are metadata?
        </a>
      </h4>
    </div>
    <div id="collapseheadingEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingEleven">
      <p>Metadata are (structural) data which describe a resource, an entity, an object or other types of data.<br/>
        This means that metadata provide information about the features of a document, e.g. its author, the time of its creation,
        its technical format, its content, and who owns the rights to it. These metadata are a collection of defined elements
        which can be used to locate, use, and administer a resource, an entity, etc.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwelve">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingTwelve" aria-expanded="false" aria-controls="collapseheadingTwelve">
         Can I set up an RSS feed for the results of my search?
        </a>
      </h4>
    </div>
    <div id="collapseheadingTwelve" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingTwelve">
      <p>Yes. At the bottom of the list of results, you will find the following link: '<i class="fa fa-bell"></i> Get RSS Feed'.<br/>
         The search will now be displayed in the form of a feed and regularly updated in your RSS reader.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThirteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingThirteen" aria-expanded="false" aria-controls="collapseheadingThirteen">
          Will my list of results show almost-matches?
        </a>
      </h4>
    </div>
    <div id="collapseheadingThirteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingThirteen">
      <p>Yes, the list of individual results will include items similar to your search query.
        To find them, go to the bottom of the data set; the almost-matches will be listed there under “Similar Items”.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFourteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFourteen" aria-expanded="false" aria-controls="collapseheadingFourteen">
          How can I obtain information about current developments at the <i>SIS Performing Arts</i>?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFourteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFourteen">
      <p>You can subscribe to the free <a href="<?=$this->url('spages-news')?>"><i>SIS Performing Arts</i> newsletter</a>.
        You will receive information on new developments and on topics of interest at regular intervals. </p>
      <p>The <i>SIS Performing Arts</i> has teamed up with the Society for Theatre Studies to operate the Performing Arts News Service, which evaluates and edits news from the
        world of theatre and dance studies. The sources thus provided can be subscribed to via an <a href="<?=$this->url('news-rss')?>">RSS feed</a>.</p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFifteen">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseheadingFifteen" aria-expanded="false" aria-controls="collapseheadingFifteen">
          To whom should I send questions and suggestions?
        </a>
      </h4>
    </div>
    <div id="collapseheadingFifteen" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingheadingFifteen">
      <p>You can send your suggestions and requests to <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>, or click
        on the <a href="http://performing-arts.eu/Feedback">Feedback button</a> in the <a href="http://performing-arts.eu/">www.performing-arts.eu</a> portal.</p>

      <p>The <i>SIS</i> team would be glad to help you in person if you have specific questions:</p>

      <b>Project Leader and Coordinator</b><br/>
      Franziska Voß<br/>
      Tel: +49 69/ 798-39574<br/>
      <a href="mailto:f.voss@ub.uni-frankfurt.de">f.voss@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Technical Implementation</b><br/>
      Julia Beck<br/>
      Tel: +49 69/ 798-39387<br/>
      <a href="mailto:j.beck@ub.uni-frankfurt.de">j.beck@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Graphic Design</b><br/>
      Axel Dörrer<br/>
      Tel: +49 69/ 798-39213<br/>
      <a href="mailto:a.doerrer@ub.uni-frankfurt.de">a.doerrer@ub.uni-frankfurt.de</a>
      <br><br>

      <b>Library Services</b><br/>
      Erzsébet Trautz<br/>
      Tel: +49 69/798-39244<br/>
      <a href="mailto:e.trautz@ub.uni-frankfurt.de">e.trautz@ub.uni-frankfurt.de</a>
    </div>
  </div>
</div>

<?
    }
?>
