<? // Set page title.
$this->headTitle($this->translate('Search in SIS Portal') . ' - ' . $this->translate('FID Darstellende Kunst')); ?>

<?
    if ($this->plugin('translate')->getTranslator()->getLocale()=='de') {
?>

<h2><?=$this->transEsc('Search in SIS Portal')?></h2>

<p>
Das Suchportal des <i>Fachinformationsdienstes Darstellende Kunst</i> bietet Ihnen ein
breites Angebot an Suchfunktionen an. Sie recherchieren in einem medienübergreifenden
Portal, dessen Index auf Bibliothekskatalogen, Archivverzeichnissen, Datenbanken
und anderen Informationsquellen mit einem spezifischen Fokus auf die darstellende
Kunst basiert.<br>
Die Ausgabe der Trefferliste erfolgt mittels des <a target="_blank" href="https://vufind-org.github.io/vufind/">VuFind</a> Discovery System und der
Suchmaschinentechnologie (<a target="_blank" href="https://lucene.apache.org/core/">Apache Lucene</a>).
In der <a href="/Search/Advanced">Erweiterten Suche</a> stehen Ihnen zudem zusätzliche Suchfacetten zur
Verfügung. Die Trefferliste kann beispielsweise nach Institutionen, Materialart und
Sammlung gefiltert werden.
</p>

<p>Sie könnten keine relevanten Suchergebnisse erzielen oder benötigen Hilfe bei Ihrer
Recherche? Wenden Sie sich an <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>!
</p>

<?
    } else {
?>

<h2>Searches Using the <i>SIS Performing Arts</i> Web Portal</h2>

<p>The <i>SIS Performing Arts</i> web portal offers a wide variety of search functions. It is provided to users as a web portal including all
  media whose index is based on library catalogues, archive indices, databases and other sources focussing specifically on the performing arts.<br>
The list of hits is shown using a <a target="_blank" href="https://vufind-org.github.io/vufind/">VuFind</a> Discovery System with its search engine
program (<a target="_blank" href="https://lucene.apache.org/core/">Apache Lucene</a>).
Using the <a href="/Search/Advanced">Advanced Search</a> option, you have access to additional search options. For example, the list of hits can be
sorted by institution, by type of material or by collection.</p>
<p>If your search doesn’t bring useful results or if you need help searching, please feel free to
  contact <a href="mailto:redaktion@performing-arts.eu">redaktion@performing-arts.eu</a>!
</p>

<?
    }
?>
